const {test}=require('node:test');
const assert=require('node:assert/strict');
const vm=require('node:vm');
const fs=require('node:fs');
function game(){const elements=new Map(),context=new Proxy({createLinearGradient:()=>({addColorStop(){}}),createRadialGradient:()=>({addColorStop(){}})},{get:(o,k)=>o[k]||(()=>{})});const element=()=>({style:{},classList:{toggle(){},add(){},remove(){}},replaceChildren(){},append(){},addEventListener(){},getContext:()=>context});const sandbox={document:{querySelector:s=>{if(!elements.has(s))elements.set(s,element());return elements.get(s);},createElement:element},window:{addEventListener(){}},localStorage:{getItem:()=>0,setItem(){}},requestAnimationFrame(){},console};vm.createContext(sandbox);vm.runInContext(fs.readFileSync(__dirname+'/game.js','utf8'),sandbox);return code=>vm.runInContext(code,sandbox);}
test('all fourteen arenas remain finite under 30 seconds of physics and combat',()=>{const run=game();for(let n=0;n<14;n++){assert.equal(run(`loadLevel(${n});for(let i=0;i<3600;i++){mouse.x=player.p[1].x+Math.cos(i*.04)*200;mouse.y=player.p[1].y+Math.sin(i*.04)*200;step();}fighters.every(f=>f.p.every(p=>Number.isFinite(p.x)&&Number.isFinite(p.y)&&p.x>=28&&p.x<=W-28&&p.y<=552))`),true);}});
test('movement, jump, crouch and pause respond',()=>{const run=game();assert.ok(run('loadLevel(0);keys.add("KeyD");for(let i=0;i<60;i++)step();keys.clear();player.p[0].x')>330);assert.ok(run('loadLevel(0);for(let i=0;i<120;i++)step();keys.add("KeyW");for(let i=0;i<25;i++)step();keys.clear();player.p[0].y')<480);assert.ok(run('loadLevel(0);keys.add("KeyS");for(let i=0;i<120;i++)step();keys.clear();player.p[0].y')>490);assert.equal(run('pause();state'),'paused');assert.equal(run('pause();state'),'playing');});
test('AI can damage player; loss and retry work',()=>{const run=game();assert.ok(run('loadLevel(0);mouse.x=0;mouse.y=449;for(let i=0;i<3600;i++)step();player.hp')<100);assert.equal(run('player.hp=0;for(let i=0;i<160;i++)step();state'),'lost');assert.equal(run('loadLevel(0);player.hp'),100);});
test('winning unlocks next round and final victory completes campaign',()=>{const run=game();assert.equal(run('loadLevel(0);fighters[1].hp=0;for(let i=0;i<160;i++)step();state'),'won');assert.equal(run('unlocked'),1);assert.equal(run('loadLevel(levels.length-1);fighters.slice(1).forEach(f=>f.hp=0);for(let i=0;i<160;i++)step();state'),'complete');});
test('short key press moves a short distance and release stops walking',()=>{for(const key of ['KeyA','KeyD']){const run=game();const result=run(`loadLevel(0);fighters=[player];for(let i=0;i<120;i++)bodyStep(player);const startX=player.p[0].x;keys.add('${key}');for(let i=0;i<29;i++){time+=DT;bodyStep(player);}const releaseX=player.p[0].x;keys.clear();for(let i=0;i<120;i++){time+=DT;bodyStep(player);}({distance:releaseX-startX,drift:player.p[0].x-releaseX})`);assert.ok(Math.abs(result.distance)>10&&Math.abs(result.distance)<50,JSON.stringify(result));assert.ok(Math.abs(result.drift)<20,JSON.stringify(result));assert.equal(Math.sign(result.distance),key==='KeyD'?1:-1);}});
test('holding movement does not build runaway speed',()=>{const run=game();const distance=run('loadLevel(0);fighters=[player];keys.add("KeyD");const startX=player.p[0].x;for(let i=0;i<240;i++){time+=DT;bodyStep(player);}player.p[0].x-startX');assert.ok(distance>360&&distance<430,String(distance));});
test('idle and walking keep torso upright without vertical bouncing',()=>{for(const walking of [false,true]){const run=game();const result=run(`loadLevel(0);fighters=[player];keys.clear();if(${walking})keys.add('KeyD');let low=Infinity,high=-Infinity,tilt=0;for(let i=0;i<360;i++){time+=DT;bodyStep(player);low=Math.min(low,player.p[0].y);high=Math.max(high,player.p[0].y);tilt=Math.max(tilt,Math.abs(player.p[1].x-player.p[0].x));}({bounce:high-low,tilt})`);assert.ok(result.bounce<1,JSON.stringify(result));assert.ok(result.tilt<5,JSON.stringify(result));}});
test('jump lands once and settles without bouncing or auto jumping',()=>{const run=game();const result=run('loadLevel(0);fighters=[player];keys.add("KeyW");let airborne=false,landings=0,lastGrounded=true;for(let i=0;i<360;i++){bodyStep(player);if(!player.grounded)airborne=true;if(!lastGrounded&&player.grounded)landings++;lastGrounded=player.grounded;}({airborne,landings,y:player.p[0].y,vy:player.vy})');assert.equal(result.airborne,true);assert.equal(result.landings,1);assert.equal(result.y,487);assert.equal(result.vy,0);});
test('mouse turn tracks within 5 degrees in 100ms without overshoot',()=>{const run=game();const error=run('loadLevel(0);fighters=[player];bodyStep(player);mouse.x=player.p[1].x;mouse.y=player.p[1].y-250;for(let i=0;i<10;i++)bodyStep(player);Math.abs(wrap(player.angle+Math.PI/2))');assert.ok(error<5*Math.PI/180,String(error));});
test('impacts displace living fighters then settle; defeated bodies fall',()=>{const run=game();assert.ok(run('loadLevel(0);fighters=[player];bodyStep(player);impulse(player,120,-100);for(let i=0;i<20;i++)bodyStep(player);player.p[0].x')>295);assert.equal(run('for(let i=0;i<240;i++)bodyStep(player);player.vy'),0);assert.equal(run('player.p[0].y'),487);assert.ok(run('player.hp=0;for(let i=0;i<240;i++)bodyStep(player);player.p[1].y')>500);});
test('no input holds the sword still and knockback cannot create an attack',()=>{const run=game();const result=run('loadLevel(0);fighters=[player];bodyStep(player);const idleAngle=player.angle;for(let i=0;i<240;i++)bodyStep(player);const drift=Math.abs(player.angle-idleAngle);impulse(player,120,-100);for(let i=0;i<30;i++)bodyStep(player);({drift,turned:Math.abs(player.angle-idleAngle),attack:player.attackInput})');assert.equal(result.drift,0);assert.equal(result.turned,0);assert.equal(result.attack,false);});
test('a positioned guard blocks the first attack without automatic damage',()=>{const run=game();const result=run('loadLevel(0);for(let i=0;i<1800;i++){step();if(player.blocked)break;}({hp:player.hp,enemyHp:fighters[1].hp,clash:player.clash})');assert.equal(result.hp,100);assert.equal(result.enemyHp,80);assert.ok(result.clash>0);});
test('swept blades collide even if both endpoints of the swing miss the guard',()=>{const run=game();const result=run(`loadLevel(0);player.angle=player.aim=0;bodyStep(player);bodyStep(player);const enemy=makeFighter(440,true);bodyStep(enemy);enemy.oldChest={...enemy.p[1]};enemy.oldAngle=-2.4;enemy.angle=-3.9;enemy.oldTip=bladeAt(enemy,0).tip;enemy.oldBase=bladeAt(enemy,0).base;enemy.base=bladeAt(enemy,1).base;enemy.tip=bladeAt(enemy,1).tip;const start=bladesTouch(bladeAt(player,0),bladeAt(enemy,0),7);const end=bladesTouch(bladeAt(player,1),bladeAt(enemy,1),7);const blocked=resolveBlock(player,enemy);const stopped=player.angle;bodyStep(player);({start,end,blocked,enemyStopped:enemy.angle>-3.9,noRetry:!player.attackInput})`);assert.equal(result.start,false);assert.equal(result.end,false);assert.equal(result.blocked,true,JSON.stringify(result));assert.equal(result.enemyStopped,true,JSON.stringify(result));assert.equal(result.noRetry,true,JSON.stringify(result));});
test('parallel blades collide at their thickness, separated blades do not',()=>{const run=game();assert.equal(run('bladesTouch({base:{x:0,y:0},tip:{x:100,y:0}},{base:{x:20,y:4},tip:{x:120,y:4}},7)'),true);assert.equal(run('bladesTouch({base:{x:0,y:0},tip:{x:100,y:0}},{base:{x:20,y:20},tip:{x:120,y:20}},7)'),false);});
test('new mouse input resumes control after a stopped swing',()=>{const run=game();const delta=run('loadLevel(0);bodyStep(player);bodyStep(player);stopAtContact(player,0);const guard=player.angle;mouse.x=player.p[1].x;mouse.y=player.p[1].y-200;for(let i=0;i<10;i++)bodyStep(player);Math.abs(wrap(player.angle-guard))');assert.ok(delta>.5);});
test('continuous weapon contact cannot rewind walking, crouching or a falling body',()=>{const run=game();const result=run('loadLevel(0);bodyStep(player);player.root.y=300;keys.add("KeyD");keys.add("KeyS");let rewind=0;for(let i=0;i<180;i++){time+=DT;bodyStep(player);const x=player.root.x,y=player.root.y;stopAtContact(player,0);rewind+=Math.abs(x-player.root.x)+Math.abs(y-player.root.y);}({rewind,x:player.root.x,y:player.root.y,stance:player.stance})');assert.equal(result.rewind,0);assert.ok(result.x>410);assert.equal(result.y,487);assert.ok(result.stance<44);});
test('jump escapes continuous contact and reaches a useful height',()=>{const run=game();const result=run('loadLevel(0);bodyStep(player);keys.add("KeyW");let highest=487;for(let i=0;i<150;i++){time+=DT;bodyStep(player);stopAtContact(player,0);highest=Math.min(highest,player.root.y);}({highest,y:player.root.y})');assert.ok(result.highest<370);assert.equal(result.y,487);});
test('a blocked downward swing gives bounded recoil rather than launching fighters',()=>{const run=game();const result=run(`loadLevel(0);bodyStep(player);bodyStep(player);const defender=makeFighter(440,true);bodyStep(defender);defender.angle=defender.oldAngle=Math.PI;defender.oldChest={...defender.p[1]};Object.assign(defender,bladeAt(defender,1));defender.oldTip={...defender.tip};defender.angular=0;player.oldAngle=-.7;player.angle=.7;player.oldChest={...player.p[1]};player.oldTip=bladeAt(player,0).tip;Object.assign(player,bladeAt(player,1));player.angular=40;const rootBefore={...player.root};const blocked=resolveBlock(player,defender);const launch=player.vy,deflect=defender.vy,unchanged=player.root.x===rootBefore.x&&player.root.y===rootBefore.y;for(let i=0;i<30;i++)bodyStep(player);({blocked,launch,deflect,unchanged,height:player.root.y})`);assert.equal(result.blocked,true);assert.equal(result.unchanged,true);assert.ok(result.launch< -50&&result.launch>=-150,JSON.stringify(result));assert.ok(result.deflect>50&&result.deflect<=150,JSON.stringify(result));assert.ok(result.height>465&&result.height<487,JSON.stringify(result));});
test('already overlapping blades can rotate apart instead of locking',()=>{const run=game();const result=run('loadLevel(0);player.angle=player.aim=0;bodyStep(player);bodyStep(player);const other=makeFighter(440,true);bodyStep(other);other.oldChest={...other.p[1]};other.oldAngle=other.angle=Math.PI;Object.assign(other,bladeAt(other,1));other.oldTip={...other.tip};const initial=bladesTouch(bladeAt(player,0),bladeAt(other,0),7);player.angle=-.6;Object.assign(player,bladeAt(player,1));resolveBlock(player,other);({initial,angle:player.angle,recoil:player.recoil||0})');assert.equal(result.initial,true);assert.equal(result.angle,-.6);assert.equal(result.recoil,0);});
test('enemy reacts to a visible incoming swing after its observation delay',()=>{const run=game();const result=run('loadLevel(0);bodyStep(player);const enemy=makeFighter(390,true);player.angle=0;player.angular=0;enemyControl(enemy);enemy.ai.ready=0;player.angular=3;time=.01;enemyControl(enemy);const before=enemy.ai.mode;time=.4;const response=enemyControl(enemy);({before,after:enemy.ai.mode,move:response.move})');assert.ok(!['parry','evade'].includes(result.before));assert.ok(['parry','evade'].includes(result.after),JSON.stringify(result));assert.ok(result.move>0,'enemy should back away from player on its left');});
test('enemy pursues retreats faster and backs out when crowded',()=>{const run=game();const result=run('loadLevel(0);bodyStep(player);const enemy=makeFighter(650,true);player.walk=-205;let chase=enemyControl(enemy).move;enemy.p[1].x=player.p[1].x+30;player.walk=0;time=.5;enemy.ai.ready=10;const retreat=enemyControl(enemy).move;({chase,retreat})');assert.ok(result.chase< -1);assert.ok(result.retreat>0);});
test('enemy varies attacks and timing, and commits rather than tracking mid-swing',()=>{const run=game();const result=run('loadLevel(0);bodyStep(player);const enemy=makeFighter(410,true);player.angle=Math.PI;player.angular=0;const types=new Set(),durations=new Set(),modes=new Set();let committed=true;for(let i=0;i<2400;i++){time+=DT;enemyControl(enemy);modes.add(enemy.ai.mode);if(enemy.ai.mode==="windup"){types.add(enemy.ai.lastAttack);durations.add(Math.round(enemy.ai.until*100));}if(enemy.ai.mode==="strike"){const finish=enemy.ai.finish;player.p[1].y-=10;enemyControl(enemy);committed=committed&&enemy.ai.finish===finish;player.p[1].y+=10;}}({types:types.size,timings:durations.size,feint:modes.has("feint"),committed})');assert.equal(result.types,3);assert.ok(result.timings>5);assert.equal(result.feint,true);assert.equal(result.committed,true);});
test('defensive recovery can lead into a counterattack',()=>{const run=game();const result=run('loadLevel(0);bodyStep(player);const enemy=makeFighter(390,true);player.angle=0;player.angular=3;enemyControl(enemy);player.angular=0;time=1;enemyControl(enemy);({mode:enemy.ai.mode,duration:enemy.ai.until-time})');assert.equal(result.mode,'windup');assert.ok(result.duration<.4);});
test('mouse distance positions the sword tip while respecting both arm segments',()=>{const run=game();const result=run('loadLevel(0);fighters=[player];bodyStep(player);mouse.x=player.p[1].x+110;mouse.y=player.p[1].y;for(let i=0;i<40;i++)bodyStep(player);const error=Math.hypot(player.tip.x-mouse.x,player.tip.y-mouse.y),middle=player.extension;mouse.x=player.p[1].x+1000;for(let i=0;i<40;i++)bodyStep(player);const far=player.extension,upper=Math.hypot(player.p[5].x-player.p[1].x,player.p[5].y-player.p[1].y),fore=Math.hypot(player.p[6].x-player.p[5].x,player.p[6].y-player.p[5].y);mouse.x=player.p[1].x+20;for(let i=0;i<40;i++)bodyStep(player);({error,middle,far,near:player.extension,upper,fore})');assert.ok(result.error<.01);assert.ok(result.middle>28&&result.middle<30);assert.ok(result.far<=54&&result.far>53.9);assert.ok(result.near>=10&&result.near<10.1);assert.ok(Math.abs(result.upper-27)<.01);assert.ok(Math.abs(result.fore-28)<.01);});
test('archer and mage telegraph before firing their distinct projectiles',()=>{for(const kind of ['archer','mage']){const run=game();const result=run(`loadLevel(0);bodyStep(player);const ranged=makeFighter(800,true,'${kind}');rangedControl(ranged);time=.9;rangedControl(ranged);const charging=ranged.ai.mode,count=projectiles.length;time=3;rangedControl(ranged);({charging,count,type:projectiles[0]?.type})`);assert.equal(result.charging,'charge');assert.equal(result.count,0);assert.equal(result.type,kind==='archer'?'arrow':'spell');}});
test('arrows deflect off the blade and can damage their shooter',()=>{const run=game();const result=run('loadLevel(0);player.angle=player.aim=0;bodyStep(player);bodyStep(player);const archer=makeFighter(540,true,"archer");fighters=[player,archer];projectiles=[{x:430,y:449,vx:-440,vy:0,type:"arrow",owner:archer,enemy:true,life:6,damage:15}];let returned=false;for(let i=0;i<130;i++){time+=DT;projectileStep();if(projectiles[0]?.owner===player)returned=true;}({returned,hp:player.hp,enemyHp:archer.hp})');assert.equal(result.returned,true);assert.equal(result.hp,100);assert.equal(result.enemyHp,65);});
test('spells ignore the sword but can be dodged',()=>{for(const dodge of [false,true]){const run=game();const hp=run(`loadLevel(0);player.angle=player.aim=0;bodyStep(player);bodyStep(player);const mage=makeFighter(600,true,'mage');fighters=[player,mage];if(${dodge}){player.root.y=330;bodyStep(player);}projectiles=[{x:430,y:449,vx:-440,vy:0,type:'spell',owner:mage,enemy:true,life:6,damage:23}];for(let i=0;i<100;i++){time+=DT;projectileStep();}player.hp`);assert.equal(hp,dodge?100:77);}});
test('ranged enemies do not inflict invisible melee hits and retry clears shots',()=>{const run=game();assert.equal(run('loadLevel(10);const ranged=fighters[1];ranged.ranged'),true);assert.equal(run('projectiles.push({type:"spell"});loadLevel(11);projectiles.length'),0);assert.equal(run('fighters[1].kind'),'mage');});








