const {test}=require('node:test');
const assert=require('node:assert/strict');
const vm=require('node:vm');
const fs=require('node:fs');
function game(){const elements=new Map(),context=new Proxy({createLinearGradient:()=>({addColorStop(){}}),createRadialGradient:()=>({addColorStop(){}})},{get:(o,k)=>o[k]||(()=>{})});const element=()=>({style:{},classList:{toggle(){},add(){},remove(){}},replaceChildren(){},append(){},addEventListener(){},getContext:()=>context});const sandbox={document:{querySelector:s=>{if(!elements.has(s))elements.set(s,element());return elements.get(s);},createElement:element},window:{addEventListener(){}},localStorage:{getItem:()=>0,setItem(){}},requestAnimationFrame(){},console};vm.createContext(sandbox);vm.runInContext(fs.readFileSync(__dirname+'/game.js','utf8'),sandbox);return code=>vm.runInContext(code,sandbox);}
test('all ten arenas remain finite under 30 seconds of physics and combat',()=>{const run=game();for(let n=0;n<10;n++){assert.equal(run(`loadLevel(${n});for(let i=0;i<3600;i++){mouse.x=player.p[1].x+Math.cos(i*.04)*200;mouse.y=player.p[1].y+Math.sin(i*.04)*200;step();}fighters.every(f=>f.p.every(p=>Number.isFinite(p.x)&&Number.isFinite(p.y)&&p.x>=28&&p.x<=1172&&p.y<=552))`),true);}});
test('movement, jump, crouch and pause respond',()=>{const run=game();assert.ok(run('loadLevel(0);keys.add("KeyD");for(let i=0;i<60;i++)step();keys.clear();player.p[0].x')>330);assert.ok(run('loadLevel(0);for(let i=0;i<120;i++)step();keys.add("KeyW");for(let i=0;i<25;i++)step();keys.clear();player.p[0].y')<480);assert.ok(run('loadLevel(0);keys.add("KeyS");for(let i=0;i<120;i++)step();keys.clear();player.p[0].y')>490);assert.equal(run('pause();state'),'paused');assert.equal(run('pause();state'),'playing');});
test('AI can damage player; loss and retry work',()=>{const run=game();assert.ok(run('loadLevel(0);for(let i=0;i<3600;i++)step();player.hp')<100);assert.equal(run('player.hp=0;for(let i=0;i<160;i++)step();state'),'lost');assert.equal(run('loadLevel(0);player.hp'),100);});
test('winning unlocks next round and final victory completes campaign',()=>{const run=game();assert.equal(run('loadLevel(0);fighters[1].hp=0;for(let i=0;i<160;i++)step();state'),'won');assert.equal(run('unlocked'),1);assert.equal(run('loadLevel(9);fighters.slice(1).forEach(f=>f.hp=0);for(let i=0;i<160;i++)step();state'),'complete');});
test('short key press moves a short distance and release stops walking',()=>{for(const key of ['KeyA','KeyD']){const run=game();const result=run(`loadLevel(0);fighters=[player];for(let i=0;i<120;i++)bodyStep(player);const startX=player.p[0].x;keys.add('${key}');for(let i=0;i<29;i++){time+=DT;bodyStep(player);}const releaseX=player.p[0].x;keys.clear();for(let i=0;i<120;i++){time+=DT;bodyStep(player);}({distance:releaseX-startX,drift:player.p[0].x-releaseX})`);assert.ok(Math.abs(result.distance)>10&&Math.abs(result.distance)<50,JSON.stringify(result));assert.ok(Math.abs(result.drift)<20,JSON.stringify(result));assert.equal(Math.sign(result.distance),key==='KeyD'?1:-1);}});
test('holding movement does not build runaway speed',()=>{const run=game();const distance=run('loadLevel(0);fighters=[player];keys.add("KeyD");const startX=player.p[0].x;for(let i=0;i<240;i++){time+=DT;bodyStep(player);}player.p[0].x-startX');assert.ok(distance>180&&distance<350,String(distance));});
test('idle and walking keep torso upright without vertical bouncing',()=>{for(const walking of [false,true]){const run=game();const result=run(`loadLevel(0);fighters=[player];keys.clear();if(${walking})keys.add('KeyD');let low=Infinity,high=-Infinity,tilt=0;for(let i=0;i<360;i++){time+=DT;bodyStep(player);low=Math.min(low,player.p[0].y);high=Math.max(high,player.p[0].y);tilt=Math.max(tilt,Math.abs(player.p[1].x-player.p[0].x));}({bounce:high-low,tilt})`);assert.ok(result.bounce<1,JSON.stringify(result));assert.ok(result.tilt<5,JSON.stringify(result));}});
test('jump lands once and settles without bouncing or auto jumping',()=>{const run=game();const result=run('loadLevel(0);fighters=[player];keys.add("KeyW");let airborne=false,landings=0,lastGrounded=true;for(let i=0;i<360;i++){bodyStep(player);if(!player.grounded)airborne=true;if(!lastGrounded&&player.grounded)landings++;lastGrounded=player.grounded;}({airborne,landings,y:player.p[0].y,vy:player.vy})');assert.equal(result.airborne,true);assert.equal(result.landings,1);assert.equal(result.y,487);assert.equal(result.vy,0);});
test('mouse turn tracks within 5 degrees in 100ms without overshoot',()=>{const run=game();const error=run('loadLevel(0);fighters=[player];bodyStep(player);mouse.x=player.p[1].x;mouse.y=player.p[1].y-250;for(let i=0;i<10;i++)bodyStep(player);Math.abs(wrap(player.angle+Math.PI/2))');assert.ok(error<5*Math.PI/180,String(error));});
test('impacts displace living fighters then settle; defeated bodies fall',()=>{const run=game();assert.ok(run('loadLevel(0);fighters=[player];bodyStep(player);impulse(player,120,-100);for(let i=0;i<20;i++)bodyStep(player);player.p[0].x')>295);assert.equal(run('for(let i=0;i<240;i++)bodyStep(player);player.vy'),0);assert.equal(run('player.p[0].y'),487);assert.ok(run('player.hp=0;for(let i=0;i<240;i++)bodyStep(player);player.p[1].y')>500);});


