project_id = "guildmaster"

[functions.publish-party]
verify_jwt = true

[functions.arena-data]
verify_jwt = true

[functions.fight-arena]
verify_jwt = true

[functions.claim-guild-name]
verify_jwt = true
