const assert=require('node:assert/strict');
const fs=require('node:fs');
const vm=require('node:vm');

const ui=fs.readFileSync(require.resolve('../js/ui.js'),'utf8');
const css=fs.readFileSync(require.resolve('../styles.css'),'utf8');
assert.match(ui,/function combatEffectIcons\(/,'combatants render effects without opening the inspector');
assert.match(ui,/battleShout:\{icon:/,'Battle Shout has a visible party buff icon');
assert.match(ui,/shieldFaith:\{icon:/,'Shield of Faith has a visible buff icon');
assert.match(css,/#combatBody\{[^}]*overflow-y:auto!important/s,'the combat body itself is scrollable');
assert.match(css,/\.combatReport\{max-height:none!important;overflow:visible!important/,'Mission Report expands to show the complete party');
assert.match(css,/conic-gradient/,'timed combat effects use circular countdown visuals');
assert.match(css,/\.combatant\.combatMini\.enemy\{\s*height:auto!important;\s*min-height:108px!important;\s*max-height:none!important/s,'enemy cards grow instead of clipping effect icons');
assert.ok(ui.indexOf('id="combatReport"')<ui.indexOf('id="combatLog"'),'Mission Report appears above the combat log');
assert.match(ui,/function updateCombatReport\(/,'Mission Report values update without replacing the whole panel');
assert.doesNotMatch(ui,/statusRow\)statusRow\.innerHTML/,'effect rows are reconciled without being erased every render');
assert.doesNotMatch(ui,/el\.outerHTML\s*=\s*combatantHtml/,'existing combatant cards survive encounter-state replacement');
assert.match(ui,/if\(!\$\('combatLog'\)\)buildCombatStructure\(m\)/,'the full combat structure is created only when the view is opened');
assert.match(css,/#combatReport\{[^}]*order:2/s,'Mission Report is explicitly ordered above the combat log');
assert.match(css,/#combatLog\{[^}]*order:3/s,'Combat Log is explicitly ordered below the Mission Report');
assert.match(css,/\.combatGrid\{[^}]*max-height:none!important;[^}]*overflow:visible!important/s,'large parties expand the combat visualization instead of being cropped');
assert.match(css,/\.combatTeamPane\{[^}]*max-height:none!important;[^}]*overflow:visible!important/s,'combat team panes do not crop members beyond six');

const context={Date,Math,Object,Array,String,Number,Set,console,clamp:(v,a,b)=>Math.max(a,Math.min(b,v)),fmt:()=> '5s',ensureStatuses:u=>u.statuses||{},STATUS_EFFECTS:{bleed:{icon:'B',name:'Bleeding'}},COMBAT_BUFF_DURATIONS:{battleShout:30000,shieldFaith:24000}};
context.globalThis=context;vm.createContext(context);vm.runInContext(ui,context);
const effects=context.combatEffectIcons({statuses:{bleed:{type:'bleed',stacks:2,expiresAt:Date.now()+5000,duration:6000}},buffs:{battleShout:Date.now()+5000}},false);
assert.match(effects,/combatEffect bleed/,'Bleeding renders directly on the combat card');
assert.match(effects,/combatEffect battleShout/,'Battle Shout renders directly on every affected character card');
assert.equal(context.combatStructureKey({type:'quest',id:7,battle:{id:1}}),context.combatStructureKey({type:'quest',id:7,battle:{id:2}}),'a new encounter does not rebuild the entire combat view');
assert.match(ui,/function reconcileCombatants\(/,'combat cards are reconciled individually between encounters');
assert.doesNotMatch(ui,/logEl\.innerHTML\s*=/,'the combat log is not completely replaced during combat');
assert.match(ui,/Reuse the visible card slots/,'new encounters reuse existing enemy card elements');
console.log('Combat UI tests passed.');
