const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');

const root=path.join(__dirname,'..');
const core=fs.readFileSync(path.join(root,'js','core.js'),'utf8');
const combat=fs.readFileSync(path.join(root,'js','combat.js'),'utf8');
const index=fs.readFileSync(path.join(root,'index.html'),'utf8');

assert.match(core,/const CLASS_LEVEL_GROWTH=/,'class growth has one shared definition');
assert.match(core,/function naturalHeroBonus\(h\)/,'natural stats are derived from class, trait, and level');
assert.match(core,/value\*levels/,'natural stat growth accounts for every prior level');
assert.match(core,/recruit\.bonus=naturalHeroBonus\(recruit\)/,'higher-level recruits receive their complete natural growth');
assert.match(core,/return syncNaturalHeroBonus\(h\)/,'existing members migrate to deterministic natural growth');
assert.match(core,/s\.recruits=.*syncNaturalHeroBonus\(h\)/,'saved applicants migrate to deterministic natural growth');
assert.match(core,/value<=100\?value\*\(linearAt100\/100\):linearAt100\+logarithmicGain\*Math\.log/,'derived attribute bonuses stay linear through 100 and become logarithmic afterward');
assert.match(core,/strengthHpBonus\(str\).*diminishingAttributeBonus\(str,25,10\)/s,'STR uses the diminishing maximum-HP curve');
assert.match(core,/physicalDodgeFromDex\(dex\).*diminishingAttributeBonus\(dex,\.25,\.08\)/s,'DEX uses the diminishing physical-dodge curve');
assert.match(core,/magicalDodgeFromInt\(intel\).*diminishingAttributeBonus\(intel,\.25,\.08\)/s,'INT uses the diminishing magical-dodge curve');
assert.match(core,/intelligenceManaBonus\(intel\).*diminishingAttributeBonus\(intel,100,40\)/s,'INT uses the diminishing mana curve');
assert.match(core,/function applicantBatchSize\(\)\{return 4\+\(s\.up\.recruit\|\|0\)\}/,'recruitment starts with four applicants');
assert.match(core,/ITEM_RARITY_MULTIPLIER=\{Common:1,Uncommon:1\.15,Rare:1\.35,Epic:1\.60/,'equipment rarity strengthens primary values and Epic matches the next tier');
assert.match(core,/function equipmentTierMultiplier\(tier\)\{return Math\.pow\(1\.6/,'equipment primary values grow by sixty percent per tier');
assert.match(core,/weaponPower=equipmentPrimaryValue/,'weapon attack uses tier and item-rarity scaling');
assert.match(core,/it\.value=equipmentPrimaryValue\(profile\.base\+2/,'armor protection uses tier and item-rarity scaling');
assert.match(core,/s\.inventory\.forEach\(migrateItemToEquipmentCurve\)/,'existing saved equipment migrates to the new primary-value curve');
assert.match(core,/attempt<20[\s\S]*!usedNames\.has/,'new recruits avoid names already on the current roster and board');
assert.match(combat,/hero\.level\+\+;\s*syncNaturalHeroBonus\(hero\)/,'level-ups use the same deterministic growth calculation');
assert.match(combat,/hpScale=1\.12\+Math\.max\(0,level-1\)\*\.20/,'enemy health retains level-one balance and scales faster thereafter');
assert.match(combat,/gearDurabilityScale=.*equipmentTierMultiplier.*Math\.pow\(1\.6,contentTier-1\)/,'enemy health tracks the geometric equipment tier curve');
assert.match(index,/js\/core\.js\?build=20260903d/,'item icon routing changes invalidate the cached core script');
assert.match(index,/js\/economy\.js\?build=20260904f/,'inventory cleanup and item inspection invalidate the cached economy script');
assert.match(combat,/const atk=Math\.round\(\(tpl\.baseAttack\|\|12\)\*scale/,'enemy attack retains the gentler original scaling');
assert.match(combat,/Math\.min\(\.40,gap\*\.03\)/,'underlevelled parties face a capped three-percent-per-level enemy modifier');
assert.match(combat,/EXPEDITION_STAGE_SIZE\)\)\*\.07/,'each completed expedition stage adds seven percent enemy strength');
assert.match(combat,/partySize-1[\s\S]*return rnd\(minimum,maximum\)/,'later-tier enemy groups scale toward the party size');
assert.match(combat,/hpScale\*1\.15\*gapMult/,'dedicated bosses receive additional durability');
assert.match(combat,/champion\.maxHp\*3\.2/,'final area champions receive additional durability');

console.log('Deterministic hero growth and enemy durability scaling tests passed.');
