const {test}=require('node:test');
const assert=require('node:assert/strict');
const vm=require('node:vm');
const fs=require('node:fs');
function game(){const elements=new Map(),context=new Proxy({createLinearGradient:()=>({addColorStop(){}}),createRadialGradient:()=>({addColorStop(){}})},{get:(o,k)=>o[k]||(()=>{})});const element=()=>({style:{},classList:{toggle(){},add(){},remove(){}},replaceChildren(){},append(){},addEventListener(){},getContext:()=>context});const sandbox={document:{querySelector:s=>{if(!elements.has(s))elements.set(s,element());return elements.get(s);},createElement:element},window:{addEventListener(){}},localStorage:{getItem:()=>0,setItem(){}},requestAnimationFrame(){},console};vm.createContext(sandbox);vm.runInContext(fs.readFileSync(__dirname+'/game.js','utf8'),sandbox);return code=>vm.runInContext(code,sandbox);}
test('all ten arenas remain finite under 30 seconds of physics and combat',()=>{const run=game();for(let n=0;n<10;n++){assert.equal(run(`loadLevel(${n});for(let i=0;i<3600;i++){mouse.x=player.p[1].x+Math.cos(i*.04)*200;mouse.y=player.p[1].y+Math.sin(i*.04)*200;step();}fighters.every(f=>f.p.every(p=>Number.isFinite(p.x)&&Number.isFinite(p.y)&&p.x>=28&&p.x<=1172&&p.y<=552))`),true);}});
test('movement, jump, crouch and pause respond',()=>{const run=game();assert.ok(run('loadLevel(0);keys.add("KeyD");for(let i=0;i<60;i++)step();keys.clear();player.p[0].x')>350);assert.ok(run('loadLevel(0);for(let i=0;i<120;i++)step();keys.add("KeyW");for(let i=0;i<25;i++)step();keys.clear();player.p[0].y')<450);assert.ok(run('loadLevel(0);keys.add("KeyS");for(let i=0;i<120;i++)step();keys.clear();player.p[0].y')>490);assert.equal(run('pause();state'),'paused');assert.equal(run('pause();state'),'playing');});
test('AI can damage player; loss and retry work',()=>{const run=game();assert.ok(run('loadLevel(0);for(let i=0;i<3600;i++)step();player.hp')<100);assert.equal(run('player.hp=0;for(let i=0;i<160;i++)step();state'),'lost');assert.equal(run('loadLevel(0);player.hp'),100);});
test('winning unlocks next round and final victory completes campaign',()=>{const run=game();assert.equal(run('loadLevel(0);fighters[1].hp=0;for(let i=0;i<160;i++)step();state'),'won');assert.equal(run('unlocked'),1);assert.equal(run('loadLevel(9);fighters.slice(1).forEach(f=>f.hp=0);for(let i=0;i<160;i++)step();state'),'complete');});
