const ASSET='../guildmaster_test/images/';
const SAVE_KEY='guildmaster_dungeons_v1';
const $=s=>document.querySelector(s),clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),pick=a=>a[Math.floor(Math.random()*a.length)],uid=()=>Date.now()+Math.floor(Math.random()*999999);
const CLASSES={
  Warrior:{hp:145,atk:17,speed:1.0,stat:'STR',skill:'Cleave',icon:'warrior.png',weapon:'longsword.png'},
  Paladin:{hp:170,atk:13,speed:.85,stat:'STR',skill:'Holy Guard',icon:'paladin.png',weapon:'mace.png'},
  Rogue:{hp:105,atk:20,speed:1.35,stat:'DEX',skill:'Backstab',icon:'rogue.png',weapon:'dagger.png'},
  Ranger:{hp:115,atk:18,speed:1.2,stat:'DEX',skill:'Volley',icon:'ranger.png',weapon:'shortbow.png'},
  Mage:{hp:90,atk:25,speed:.8,stat:'INT',skill:'Fireball',icon:'mage.png',weapon:'wand.png'},
  Priest:{hp:105,atk:12,speed:.9,stat:'INT',skill:'Mend',icon:'priest.png',weapon:'scepter.png'}
};
const NAMES=['Dara Grey','Tarin Rook','Eira Ember','Soren Vale','Bryn Ironwood','Iris Ashfall','Joren Dawn','Mira Briar','Fen Marrow','Veya Duskwood','Nell Thorne','Garrick Stone','Lyra Hearth','Edric Frost','Leona Redfern','Alden Pike','Orin Blackthorn','Tessa Willow','Cora Flint','Rowan Voss'];
const REGIONS=[
  {name:'Greenwood Descent',bg:'greenwood-forest.png',enemies:[['Forest Goblin','forest-goblin.png'],['Grey Wolf','grey-wolf.png'],['Moss Slime','moss-slime.png']],boss:['The Briar Tyrant','thornback-boar.png']},
  {name:'Sunken Moonroad',bg:'sunfield-plains.png',enemies:[['Highway Bandit','highway-bandit.png'],['Pollen Sprite','pollen-sprite.png'],['Prairie Wolf','prairie-wolf.png']],boss:['The Gilded Raider','sunfield-raider.png']},
  {name:'Rotting Vault',bg:'rotting-vault.png',enemies:[['Crypt Warden','hill-brigand.png'],['Grave Wisp','briar-wisp.png'],['Ironback','ironback-bear.png']],boss:['The Hollow King','rockhorn-ram.png']},
  {name:'Ashen Crown',bg:'ashen-desert.png',enemies:[['Dune Reaver','greenwood-poacher.png'],['Dust Hawk','dust-hawk.png'],['Cinder Imp','spark-imp.png']],boss:['The Cinder Sovereign','redstone-harpy.png']}
];
const NODE_INFO={combat:['⚔','Battle','Enemies guard the road.'],elite:['☠','Elite','Hard fight. Better reward.'],event:['?','Event','A choice with consequences.'],camp:['🔥','Camp','Recover and prepare.'],treasure:['◆','Cache','Gold or equipment.'],merchant:['⚖','Trader','Spend run gold.'],boss:['♛','Region Boss','Defeat it to advance.']};
const PERKS=[['Ferocity','Party attack +12%','attack',.12],['Endurance','Party maximum HP +15%','hp',.15],['Haste','Party attack speed +10%','speed',.10],['Precision','Critical chance +8%','crit',.08],['Field Medicine','Heal 8% after each battle','heal',.08],['Treasure Sense','Gold rewards +20%','gold',.20]];
const ITEM_NAMES={Weapon:['Copper Longsword','Hunter Bow','Runic Hammer','Moonlit Dagger','Ember Wand','Oath Scepter'],Armor:['Padded Field Robes','Copper Mail','Ranger Leathers','Steel Cuirass'],Accessory:['Copper Band','Wooden Charm',"Poisoner's Toolkit",'Iron Amulet']};
let state=load(),battleTimer=null,draftSelection=[];
function fresh(){return{treasury:0,trophies:[],unlocks:['Warrior','Paladin','Rogue','Ranger','Mage','Priest'],history:[],upgrades:{supplies:0,recovery:0,armory:0},run:null}}
function load(){try{return Object.assign(fresh(),JSON.parse(localStorage.getItem(SAVE_KEY)||'null')||{})}catch{return fresh()}}
function save(){localStorage.setItem(SAVE_KEY,JSON.stringify(state))}
function toast(msg){const e=document.createElement('div');e.className='toast';e.textContent=msg;$('#toast').append(e);setTimeout(()=>e.remove(),2600)}
function heroPower(h){return Math.round(h.maxHp/5+h.atk*3+h.speed*20)}
function makeHero(level=1){const cls=pick(state.unlocks),base=CLASSES[cls],bonus=state.upgrades.armory||0;return{id:uid(),name:pick(NAMES),class:cls,level,xp:0,maxHp:Math.round(base.hp*(1+(level-1)*.13)),hp:Math.round(base.hp*(1+(level-1)*.13)),atk:Math.round(base.atk*(1+(level-1)*.11))+bonus*2,speed:base.speed,crit:.05,gear:{Weapon:{name:'Guild-Issue '+cls+' Weapon',power:5+bonus*3,icon:base.weapon},Armor:null,Accessory:null},kills:0,damage:0}}
function beginDraft(){draftSelection=[];const candidates=Array.from({length:6},()=>makeHero(1));state.draft=candidates;save();renderDraft()}
function toggleDraft(id){const i=draftSelection.indexOf(id);if(i>=0)draftSelection.splice(i,1);else if(draftSelection.length<2)draftSelection.push(id);renderDraft()}
function startRun(){if(draftSelection.length!==2)return;const heroes=state.draft.filter(h=>draftSelection.includes(h.id));state.run={id:uid(),started:Date.now(),region:0,step:0,encounters:0,gold:40+(state.upgrades.supplies||0)*20,heroes,perks:[],nodes:makeRegionMap(),mode:'map',pendingReward:null,battle:null,log:[]};delete state.draft;save();render()}
function makeNodes(){const pool=['combat','combat','event','camp','treasure','merchant','elite'];return Array.from({length:3},()=>pick(pool))}
function makeRegionMap(){return Array.from({length:5},makeNodes)}
function img(path,cls='portrait'){return `<img class="${cls}" src="${ASSET}${path}" alt="">`}
function heroCard(h){const hp=clamp(h.hp/h.maxHp*100,0,100),base=CLASSES[h.class];return `<div class="hero ${h.hp<=0?'dead':''}">${img('classes/'+base.icon)}<div><div class="name">${h.name}</div><div class="sub">${h.class} · Lv. ${h.level} · ${base.skill}</div><div class="bar"><i style="width:${hp}%"></i></div><div class="stats"><span>${Math.max(0,Math.ceil(h.hp))}/${h.maxHp} HP</span><span>${effectiveAtk(h)} ATK</span><span>${heroPower(h)} PWR</span></div></div><div class="gear"><span class="gearSlot">⚔ ${h.gear.Weapon?.name||'Empty'}</span><span class="gearSlot">▣ ${h.gear.Armor?.name||'Empty'}</span><span class="gearSlot">◇ ${h.gear.Accessory?.name||'Empty'}</span></div></div>`}
function header(){const r=state.run;return `<div class="topbar"><div class="title"><h1>Guildmaster: Dungeons</h1><p>${r?`${REGIONS[r.region]?.name||'Expedition Complete'} · ${r.heroes.length} adventurers · ${r.encounters} battles`:'Every expedition writes a new guild legend.'}</p></div><div class="resources"><span class="chip">Treasury <b>${state.treasury}g</b></span>${r?`<span class="chip">Run Gold <b>${r.gold}g</b></span><span class="chip">Region <b>${r.region+1}/4</b></span>`:`<span class="chip">Victories <b>${state.history.filter(x=>x.won).length}</b></span>`}</div></div>`}
function render(){clearInterval(battleTimer);battleTimer=null;$('#app').innerHTML=`<div class="shell">${header()}${state.run?renderRun():renderGuild()}</div>`;if(state.run?.mode==='combat')startBattleLoop()}
function renderGuild(){const ups=[['supplies','Expedition Supplies','Begin runs with +20 gold per rank',80],['recovery','Recovery Teams','Recover +10% run gold after defeat',120],['armory','Guild Armory','Starter weapons gain +3 power',150]];return `<div class="grid"><section class="panel"><div class="screenTitle"><h2>The Guild Endures</h2><p class="muted">Adventurers come and go. The treasury, discoveries, and their stories remain.</p></div><div class="actions" style="justify-content:center"><button class="btn primary" onclick="beginDraft()">Recruit a New Expedition</button></div><h3 style="margin-top:25px">Guild Investments</h3>${ups.map(([k,n,d,c])=>{const rank=state.upgrades[k]||0,cost=c*(rank+1);return `<div class="upgrade"><div><b>${n} · ${rank}/5</b><div class="muted">${d}</div></div><button class="btn" ${rank>=5||state.treasury<cost?'disabled':''} onclick="buyUpgrade('${k}',${cost})">${rank>=5?'Complete':cost+'g'}</button></div>`}).join('')}</section><aside class="panel"><h3>Hall of Heroes</h3><p class="muted">Victors retire. The fallen are remembered.</p><div class="hallList">${state.history.length?state.history.slice().reverse().map(x=>`<div class="history"><b>${x.won?'VICTORY':'FALLEN'} · ${x.party.join(', ')}</b><div class="muted">Reached ${x.region} · ${x.battles} battles · secured ${x.gold}g</div></div>`).join(''):'<div class="muted">No expeditions recorded yet.</div>'}</div><h3 style="margin-top:16px">Boss Trophies</h3><div class="muted">${state.trophies.length?state.trophies.join('<br>'):'No trophies recovered.'}</div></aside></div>`}
function buyUpgrade(k,cost){if(state.treasury<cost||(state.upgrades[k]||0)>=5)return;state.treasury-=cost;state.upgrades[k]=(state.upgrades[k]||0)+1;save();render()}
function renderDraft(){const candidates=state.draft||[];$('#app').innerHTML=`<div class="shell">${header()}<section class="panel"><div class="screenTitle"><h2>Choose the First Two</h2><p class="muted">These strangers will carry the expedition until death or victory. Select exactly two.</p></div><div class="heroGrid">${candidates.map(h=>`<button class="choice ${draftSelection.includes(h.id)?'good':''}" onclick="toggleDraft(${h.id})">${heroCard(h)}</button>`).join('')}</div><div class="actions" style="justify-content:center"><button class="btn" onclick="delete state.draft;render()">Cancel</button><button class="btn primary" ${draftSelection.length!==2?'disabled':''} onclick="startRun()">Begin with ${draftSelection.length}/2</button></div></section></div>`}
function renderRun(){const r=state.run;if(r.mode==='map')return renderMap();if(r.mode==='combat')return renderCombat();if(r.mode==='reward')return renderReward();if(r.mode==='recruit')return renderRecruit();return renderMap()}
function renderSidebar(){const r=state.run;return `<aside class="panel"><h3>Expedition Party</h3><div class="heroGrid">${r.heroes.map(heroCard).join('')}</div><h3 style="margin-top:15px">Run Boons</h3><div class="muted">${r.perks.length?r.perks.map(p=>'◆ '+p.name).join('<br>'):'No boons yet.'}</div><div class="actions"><button class="btn danger" onclick="confirmAbandon()">Abandon Run</button></div></aside>`}
function renderMap(){const r=state.run,reg=REGIONS[r.region];return `<div class="grid"><section class="panel map" style="background-image:url('${ASSET}backgrounds/${reg.bg}')"><div class="regionHead"><div class="eyebrow">REGION ${r.region+1} · STEP ${Math.min(6,r.step+1)}/6</div><h2>${reg.name}</h2><p class="muted">Choose the party's next destination. The whole region lies ahead.</p></div><div class="path">${r.nodes.map((row,rowIndex)=>`<div class="pathRow">${row.map(type=>{const n=NODE_INFO[type],active=rowIndex===r.step;return `<button class="node ${active?'current':rowIndex<r.step?'done':''}" ${active?'':`disabled`} onclick="chooseNode('${type}')"><span class="nodeIcon">${n[0]}</span><span class="nodeName">${n[1]}</span><div class="nodeDesc">${n[2]}</div></button>`}).join('')}</div>`).join('')}<div class="pathRow"><button class="node ${r.step>=5?'current':''}" ${r.step>=5?'':'disabled'} onclick="chooseNode('boss')"><span class="nodeIcon">♛</span><span class="nodeName">${reg.boss[0]}</span><div class="nodeDesc">Region Boss</div></button></div></div></section>${renderSidebar()}</div>`}
function chooseNode(type){if(type==='combat'||type==='elite'||type==='boss')return beginCombat(type);if(type==='camp'){state.run.heroes.forEach(h=>h.hp=Math.min(h.maxHp,h.hp+h.maxHp*.35));toast('The party recovered 35% health.');return advanceNode()}if(type==='treasure')return treasureEvent();if(type==='merchant')return merchantEvent();return storyEvent()}
function enemyUnit(name,icon,level,elite=false,boss=false){const scale=1+(level-1)*.22;return{id:uid(),name,icon,level,maxHp:Math.round((boss?390:elite?175:105)*scale),hp:Math.round((boss?390:elite?175:105)*scale),atk:Math.round((boss?25:elite?18:12)*scale),speed:boss?1.05:elite?1:.85,boss,elite,progress:0}}
function beginCombat(type){const r=state.run,reg=REGIONS[r.region],level=1+r.region*5+r.step,boss=type==='boss',elite=type==='elite',count=boss?1:Math.min(4,2+Math.floor(r.region/2)+(elite?1:0));const enemies=Array.from({length:count},()=>{const e=boss?reg.boss:pick(reg.enemies);return enemyUnit(e[0],e[1],level,elite,boss)});r.battle={type,enemies,heroProgress:{},log:[`${boss?'Boss battle':'Battle'} begins.`]};r.mode='combat';save();render()}
function effectiveAtk(h){const perk=state.run?.perks.filter(p=>p.type==='attack').reduce((a,p)=>a+p.value,0)||0;return Math.round((h.atk+(h.gear.Weapon?.power||0))*(1+perk))}
function startBattleLoop(){if(battleTimer)return;battleTimer=setInterval(combatTick,260)}
function combatTick(){const r=state.run,b=r?.battle;if(!r||r.mode!=='combat'||!b)return;const livingH=r.heroes.filter(h=>h.hp>0),livingE=b.enemies.filter(e=>e.hp>0);if(!livingH.length)return endRun(false);if(!livingE.length)return winBattle();r.heroes.forEach(h=>{if(h.hp<=0)return;b.heroProgress[h.id]=(b.heroProgress[h.id]||0)+h.speed*(1+r.perks.filter(p=>p.type==='speed').reduce((a,p)=>a+p.value,0));if(b.heroProgress[h.id]>=4){b.heroProgress[h.id]=0;const target=pick(livingE),crit=Math.random()<h.crit+r.perks.filter(p=>p.type==='crit').reduce((a,p)=>a+p.value,0),dmg=Math.round(effectiveAtk(h)*(crit?1.75:1)*(.86+Math.random()*.28));target.hp-=dmg;h.damage+=dmg;if(target.hp<=0)h.kills++;b.log.unshift(`${h.name} hits ${target.name} for ${dmg}${crit?' critical':''}.`)}});b.enemies.forEach(e=>{if(e.hp<=0)return;e.progress+=e.speed;if(e.progress>=4){e.progress=0;const target=pick(livingH),dmg=Math.round(e.atk*(.82+Math.random()*.3));target.hp-=dmg;b.log.unshift(`${e.name} hits ${target.name} for ${dmg}.`)}});const priest=livingH.find(h=>h.class==='Priest');if(priest&&Math.random()<.045){const target=[...livingH].sort((a,b)=>a.hp/a.maxHp-b.hp/b.maxHp)[0],heal=Math.round(priest.atk*1.5);target.hp=Math.min(target.maxHp,target.hp+heal);b.log.unshift(`${priest.name} mends ${target.name} for ${heal}.`)}b.log=b.log.slice(0,14);save();updateCombatDom()}
function unitCard(u,enemy=false){const hp=clamp(u.hp/u.maxHp*100,0,100),path=enemy?'enemies/'+u.icon:'classes/'+CLASSES[u.class].icon;return `<div class="unit ${enemy?'enemy':''} ${u.hp<=0?'dead':''}" id="unit-${u.id}"><div class="unitName">${enemy?u.level+' ':''}${u.name}</div><div class="bar"><i style="width:${hp}%"></i></div>${img(path)}<div class="sub">${Math.max(0,Math.ceil(u.hp))}/${u.maxHp} HP</div></div>`}
function renderCombat(){const r=state.run,b=r.battle,reg=REGIONS[r.region];return `<section class="panel combatField" style="background-image:url('${ASSET}backgrounds/${reg.bg}')"><div class="regionHead"><div class="eyebrow">${b.type==='boss'?'REGION BOSS':b.type==='elite'?'ELITE BATTLE':'BATTLE'}</div><h2>${reg.name}</h2></div><div class="combatSides"><div class="combatSide">${r.heroes.map(h=>unitCard(h)).join('')}</div><div class="combatSide">${b.enemies.map(e=>unitCard(e,true)).join('')}</div></div><div class="combatLog">${b.log.join('<br>')}</div></section>`}
function updateCombatDom(){const r=state.run,b=r?.battle;if(!b)return;[...r.heroes,...b.enemies].forEach(u=>{const e=$(`#unit-${u.id}`);if(!e)return;const fill=e.querySelector('.bar i'),sub=e.querySelector('.sub');fill.style.width=clamp(u.hp/u.maxHp*100,0,100)+'%';sub.textContent=`${Math.max(0,Math.ceil(u.hp))}/${u.maxHp} HP`;e.classList.toggle('dead',u.hp<=0)});const log=$('.combatLog');if(log)log.innerHTML=b.log.join('<br>')}
function winBattle(){clearInterval(battleTimer);battleTimer=null;const r=state.run,b=r.battle,boss=b.type==='boss',elite=b.type==='elite';r.encounters++;const gold=Math.round((18+r.region*22+r.step*6)*(elite?1.8:boss?3:1)*(1+r.perks.filter(p=>p.type==='gold').reduce((a,p)=>a+p.value,0)));r.gold+=gold;r.heroes.forEach(h=>{if(h.hp>0){h.xp++;if(h.xp%2===0){h.level++;h.maxHp=Math.round(h.maxHp*1.12);h.hp=Math.min(h.maxHp,h.hp+Math.round(h.maxHp*.25));h.atk=Math.round(h.atk*1.1)}const heal=r.perks.filter(p=>p.type==='heal').reduce((a,p)=>a+p.value,0);h.hp=Math.min(h.maxHp,h.hp+h.maxHp*heal)}});if(boss){state.trophies.push(`${REGIONS[r.region].boss[0]} defeated`);r.battle=null;if(r.region===REGIONS.length-1)return endRun(true);r.mode='recruit';r.recruitChoices=Array.from({length:3},()=>makeHero(1+(r.region+1)*5));save();render();return}r.pendingReward=makeRewards(elite);r.battle=null;r.mode='reward';save();render()}
function makeItem(elite=false){const r=state.run,tier=r.region+1,slot=pick(['Weapon','Armor','Accessory']),rarity=Math.random()<(elite?.35:.12)?'Rare':Math.random()<.35?'Uncommon':'Common',mult={Common:1,Uncommon:1.25,Rare:1.6}[rarity];return{id:uid(),slot,name:pick(ITEM_NAMES[slot]),rarity,power:Math.round((slot==='Weapon'?8:5)*Math.pow(1.55,tier-1)*mult),icon:slot==='Weapon'?pick(['longsword.png','dagger.png','shortbow.png','wand.png']):slot==='Armor'?'padded-field-robes.png':'ring.png'}}
function makeRewards(elite){return[{kind:'item',item:makeItem(elite)},{kind:'gold',amount:35+state.run.region*30},{kind:'perk',perk:pick(PERKS)}]}
function renderReward(){const r=state.run;return `<section class="panel"><div class="screenTitle"><h2>Choose One Reward</h2><p class="muted">Everything else is left behind.</p></div><div class="choiceGrid">${r.pendingReward.map((x,i)=>x.kind==='item'?`<button class="choice" onclick="takeReward(${i})">${img(`items/${x.item.slot==='Accessory'?'accessories':x.item.slot.toLowerCase()}/${x.item.icon}`,'itemIcon')}<strong class="rarity-${x.item.rarity}">${x.item.name}</strong><div class="muted">${x.item.rarity} ${x.item.slot}<br>+${x.item.power} ${x.item.slot==='Weapon'?'Attack':'Power'}</div></button>`:x.kind==='gold'?`<button class="choice" onclick="takeReward(${i})"><span class="big">◉</span><strong>${x.amount} Run Gold</strong><div class="muted">Spend it now or risk carrying it home.</div></button>`:`<button class="choice" onclick="takeReward(${i})"><span class="big">◆</span><strong>${x.perk[0]}</strong><div class="muted">${x.perk[1]} for this run.</div></button>`).join('')}</div></section>`}
function takeReward(i){const x=state.run.pendingReward[i];if(x.kind==='gold')state.run.gold+=x.amount;else if(x.kind==='perk'){state.run.perks.push({name:x.perk[0],type:x.perk[2],value:x.perk[3]});if(x.perk[2]==='hp')state.run.heroes.forEach(h=>{const gain=Math.round(h.maxHp*x.perk[3]);h.maxHp+=gain;h.hp+=gain})}else equipBest(x.item);state.run.pendingReward=null;advanceNode()}
function equipBest(item){const heroes=state.run.heroes.filter(h=>h.hp>0),h=[...heroes].sort((a,b)=>(a.gear[item.slot]?.power||0)-(b.gear[item.slot]?.power||0))[0]||state.run.heroes[0];h.gear[item.slot]=item;toast(`${h.name} equipped ${item.name}.`)}
function advanceNode(){const r=state.run;r.step++;r.mode='map';save();render()}
function renderRecruit(){const r=state.run;return `<section class="panel"><div class="screenTitle"><h2>A Survivor Joins the Road</h2><p class="muted">Recruit one adventurer before entering ${REGIONS[r.region+1].name}.</p></div><div class="heroGrid">${r.recruitChoices.map((h,i)=>`<button class="choice" onclick="takeRecruit(${i})">${heroCard(h)}</button>`).join('')}</div></section>`}
function takeRecruit(i){const r=state.run,h=r.recruitChoices[i],hpBonus=r.perks.filter(p=>p.type==='hp').reduce((a,p)=>a+p.value,0);if(hpBonus){h.maxHp=Math.round(h.maxHp*(1+hpBonus));h.hp=h.maxHp}r.heroes.push(h);r.region++;r.step=0;r.nodes=makeRegionMap();r.mode='map';delete r.recruitChoices;r.heroes.forEach(hero=>hero.hp=Math.max(1,Math.min(hero.maxHp,hero.hp+hero.maxHp*.35)));save();render()}
function treasureEvent(){const item=makeItem(false),gold=30+state.run.region*25;showOverlay('An Abandoned Cache',`<p class="muted">The party can only carry one prize safely.</p><div class="choiceGrid"><button class="choice" onclick="eventItem(${JSON.stringify(item).replace(/"/g,'&quot;')})"><strong>${item.name}</strong><div class="muted">${item.rarity} ${item.slot} · +${item.power} power</div></button><button class="choice" onclick="eventGold(${gold})"><strong>${gold} Gold</strong><div class="muted">Add it to the run purse.</div></button></div>`)}
function eventItem(item){equipBest(item);closeOverlay();advanceNode()}function eventGold(n){state.run.gold+=n;closeOverlay();advanceNode()}
function storyEvent(){const h=pick(state.run.heroes),events=[['A Broken Oath',`${h.name} finds the banner of a failed expedition.`,`Honor the fallen`,`Party gains 10% maximum HP`,`Strip it for valuables`,`Gain 55 gold`],['The Narrow Bridge','Something follows beneath the bridge.','Cross carefully','Heal the most wounded hero','Set an ambush','Gain 12% party attack'],['A Familiar Voice',`${h.name} hears someone calling from the dark.`,'Follow the voice','Gain a random item','Keep moving','Gain 40 gold']];const e=pick(events);showOverlay(e[0],`<p>${e[1]}</p><div class="choiceGrid"><button class="choice" onclick="resolveStory(0)"><strong>${e[2]}</strong><div class="muted">${e[3]}</div></button><button class="choice" onclick="resolveStory(1)"><strong>${e[4]}</strong><div class="muted">${e[5]}</div></button></div>`)}
function resolveStory(i){if(i===0){if(Math.random()<.5){state.run.perks.push({name:'Oathbound',type:'hp',value:.1});state.run.heroes.forEach(h=>{h.maxHp=Math.round(h.maxHp*1.1);h.hp=Math.min(h.maxHp,h.hp+h.maxHp*.2)})}else equipBest(makeItem(false))}else{if(Math.random()<.5)state.run.gold+=55;else state.run.perks.push({name:'Ambush Training',type:'attack',value:.12})}closeOverlay();advanceNode()}
function merchantEvent(){const items=[makeItem(),makeItem()],cost=45+state.run.region*25;showOverlay('The Road Trader',`<p class="muted">Run gold spent here cannot reach the guild—but it may keep this party alive.</p><div class="choiceGrid">${items.map((it,i)=>`<button class="choice" ${state.run.gold<cost?'disabled':''} onclick="buyRunItem(${JSON.stringify(it).replace(/"/g,'&quot;')},${cost})"><strong>${it.name}</strong><div class="muted">${it.rarity} · ${cost}g</div></button>`).join('')}<button class="choice" onclick="closeOverlay();advanceNode()"><strong>Leave</strong><div class="muted">Keep your gold.</div></button></div>`)}
function buyRunItem(item,cost){if(state.run.gold<cost)return;state.run.gold-=cost;equipBest(item);closeOverlay();advanceNode()}
function showOverlay(title,body){document.body.insertAdjacentHTML('beforeend',`<div class="overlay" id="overlay"><section class="panel modal"><h2>${title}</h2>${body}</section></div>`)}function closeOverlay(){$('#overlay')?.remove()}
function confirmAbandon(){showOverlay('Abandon this expedition?',`<p>The party will disband. The guild recovers a portion of its ${state.run.gold} run gold.</p><div class="actions"><button class="btn" onclick="closeOverlay()">Continue Run</button><button class="btn danger" onclick="closeOverlay();endRun(false)">Abandon Expedition</button></div>`)}
function endRun(won){clearInterval(battleTimer);battleTimer=null;const r=state.run,recovery=won?1:Math.min(.7,.2+(state.upgrades.recovery||0)*.1),secured=Math.round(r.gold*recovery),names=r.heroes.map(h=>h.name);state.treasury+=secured;state.history.push({won,party:names,region:REGIONS[Math.min(r.region,3)].name,battles:r.encounters,gold:secured,date:Date.now()});if(state.history.length>30)state.history.shift();state.run=null;save();$('#app').innerHTML=`<div class="shell">${header()}<section class="panel banner"><h2>${won?'Expedition Conquered':'The Expedition Is Lost'}</h2><p>${won?`${names.join(', ')} retire as legends.`:`${names.join(', ')} will not return to the road.`}</p><p class="muted">${secured} gold reached the guild treasury. A new expedition will require new adventurers.</p><button class="btn primary" onclick="render()">Return to Guild</button></section></div>`}
render();
