const ASSET='../guildmaster/images/';
const ITEM_DATA_URL='../guildmaster/data/items.json';
const SAVE_KEY='guildmaster_dungeons_v1';
const $=s=>document.querySelector(s),clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),pick=a=>a[Math.floor(Math.random()*a.length)],uid=()=>Date.now()+Math.floor(Math.random()*999999);
const CLASSES={
  Warrior:{hp:145,atk:17,speed:1.0,stat:'STR',skill:'Cleave',icon:'warrior.png',weapon:'longsword.png',armor:'Heavy',weapons:['Longsword','Greatsword','Battle Axe','Greataxe','Warhammer','Mace','Spear','Halberd']},
  Paladin:{hp:170,atk:13,speed:.85,stat:'STR',skill:'Holy Guard',icon:'paladin.png',weapon:'mace.png',armor:'Heavy',weapons:['Longsword','Greatsword','Mace','Warhammer','Spear','Holy Sword']},
  Rogue:{hp:105,atk:20,speed:1.35,stat:'DEX',skill:'Backstab',icon:'rogue.png',weapon:'dagger.png',armor:'Light',weapons:['Dagger','Knife','Dirk','Kris','Shortsword','Twin Blades']},
  Ranger:{hp:115,atk:18,speed:1.2,stat:'DEX',skill:'Volley',icon:'ranger.png',weapon:'shortbow.png',armor:'Medium',weapons:['Shortbow','Longbow','Recurve Bow','Light Crossbow','Heavy Crossbow','Hunting Bow','Spear']},
  Mage:{hp:90,atk:25,speed:.8,stat:'INT',skill:'Fireball',icon:'mage.png',weapon:'wand.png',armor:'Light',weapons:['Oak Staff','Arcane Staff','Wand','Crystal Wand','Orb','Spellbook','Scepter']},
  Priest:{hp:105,atk:12,speed:.9,stat:'INT',skill:'Mend',icon:'priest.png',weapon:'scepter.png',armor:'Light',weapons:['Oak Staff','Holy Staff','Scepter','Wand']}
};
const ABILITIES={
  Warrior:{name:'Cleave',cost:20,cooldown:6,maxMana:50,regen:3},Paladin:{name:'Holy Guard',cost:24,cooldown:8,maxMana:60,regen:3},
  Rogue:{name:'Backstab',cost:18,cooldown:5,maxMana:45,regen:4},Ranger:{name:'Volley',cost:22,cooldown:7,maxMana:50,regen:3.5},
  Mage:{name:'Fireball',cost:28,cooldown:7,maxMana:80,regen:6},Priest:{name:'Mend',cost:25,cooldown:6,maxMana:75,regen:5}
};
const NAMES=['Dara Grey','Tarin Rook','Eira Ember','Soren Vale','Bryn Ironwood','Iris Ashfall','Joren Dawn','Mira Briar','Fen Marrow','Veya Duskwood','Nell Thorne','Garrick Stone','Lyra Hearth','Edric Frost','Leona Redfern','Alden Pike','Orin Blackthorn','Tessa Willow','Cora Flint','Rowan Voss'];
const REGIONS=[
  {name:'Greenwood Descent',bg:'greenwood-forest.png',enemies:[['Forest Goblin','forest-goblin.png'],['Grey Wolf','grey-wolf.png'],['Moss Slime','moss-slime.png']],boss:['The Briar Tyrant','thornback-boar.png']},
  {name:'Sunken Moonroad',bg:'sunfield-plains.png',enemies:[['Highway Bandit','highway-bandit.png'],['Pollen Sprite','pollen-sprite.png'],['Prairie Wolf','prairie-wolf.png']],boss:['The Gilded Raider','sunfield-raider.png']},
  {name:'Rotting Vault',bg:'rotting-vault.png',enemies:[['Crypt Warden','hill-brigand.png'],['Grave Wisp','briar-wisp.png'],['Ironback','ironback-bear.png']],boss:['The Hollow King','rockhorn-ram.png']},
  {name:'Ashen Crown',bg:'ashen-desert.png',enemies:[['Dune Reaver','greenwood-poacher.png'],['Dust Hawk','dust-hawk.png'],['Cinder Imp','spark-imp.png']],boss:['The Cinder Sovereign','redstone-harpy.png']}
];
const NODE_INFO={combat:['⚔','Battle','Enemies guard the road.'],elite:['☠','Elite','Hard fight. Better reward.'],event:['?','Event','A choice with consequences.'],camp:['🔥','Camp','Recover and prepare.'],treasure:['◆','Cache','Gold or equipment.'],merchant:['⚖','Trader','Spend run gold.'],boss:['♛','Region Boss','Defeat it to advance.']};
const PERKS=[['Ferocity','Party attack +12%','attack',.12],['Endurance','Party maximum HP +15%','hp',.15],['Haste','Party attack speed +10%','speed',.10],['Precision','Critical chance +8%','crit',.08],['Field Medicine','Heal 8% after each battle','heal',.08],['Treasure Sense','Gold rewards +20%','gold',.20]];
const ITEM_NAMES={Weapon:['Copper Longsword','Hunter Bow','Runic Hammer','Moonlit Dagger','Ember Wand','Oath Scepter'],Armor:['Padded Field Robes','Copper Mail','Ranger Leathers','Steel Cuirass'],Accessory:['Copper Band','Wooden Charm',"Poisoner's Toolkit",'Iron Amulet']};
let state=load(),battleTimer=null,draftSelection=[];
let battleFrame=null,lastCombatTick=performance.now(),ITEM_DATA={weapons:{},armorProfiles:{}};
let RACE_DATA={},SUBCLASS_DATA={};
const CHARACTER_BASE={Warrior:{str:17,dex:9,int:5,def:15,mdef:7,block:1},Ranger:{str:8,dex:18,int:7,def:9,mdef:8,block:0},Mage:{str:4,dex:8,int:21,def:5,mdef:15,block:0},Priest:{str:9,dex:6,int:17,def:11,mdef:15,block:0},Rogue:{str:7,dex:20,int:6,def:7,mdef:8,block:0},Paladin:{str:15,dex:7,int:11,def:18,mdef:13,block:2}};
const CHARACTER_RARITIES=['Common','Uncommon','Rare','Epic','Legendary'];
const CHARACTER_TRAITS=['Brave','Stalwart','Quick','Tough','Clever','Balanced','Reckless','Cautious','Hotheaded','Iron-Skinned','Arcane-Touched','Bloodthirsty','Gentle'];
const ITEM_RARITY_MULTIPLIER={Common:1,Uncommon:1.15,Rare:1.35,Epic:1.6,Legendary:1.85,Mythic:2.15};
const ITEM_STAT_KEYS=['hp','str','dex','int','def','mdef','block','regen','mana','manaRegen','attackSpeed','lifesteal','fire','ice','poison','lightning','holy','dark','armorPen','parry','critChance','critDamage','accuracy','elementalDamage','healingPower','statusChance','cleave','counter','damageVariance','damageBonus','healBonus','threatBonus','physicalDodgeBonus','magicalDodgeBonus','cooldownReduction'];
const PERCENT_STATS=new Set(['armorPen','parry','critChance','critDamage','accuracy','elementalDamage','healingPower','statusChance','cleave','counter','damageVariance','damageBonus','healBonus','physicalDodgeBonus','magicalDodgeBonus','cooldownReduction']);
const STAT_LABELS={hp:'HP',str:'STR',dex:'DEX',int:'INT',def:'DEF',mdef:'MDEF',block:'Block',regen:'HP Regen',mana:'Mana',manaRegen:'Mana Regen',attackSpeed:'Attack Speed',lifesteal:'Lifesteal',fire:'Fire Res',ice:'Ice Res',poison:'Poison Res',lightning:'Lightning Res',holy:'Holy Res',dark:'Dark Res',armorPen:'Armor Pen',parry:'Parry',critChance:'Crit Chance',critDamage:'Crit Damage',accuracy:'Accuracy',elementalDamage:'Elemental Damage',healingPower:'Healing Power',statusChance:'Status Chance',cleave:'Cleave',counter:'Counter',damageVariance:'Damage Variance',damageBonus:'Damage',healBonus:'Healing',threatBonus:'Threat',physicalDodgeBonus:'Physical Dodge',magicalDodgeBonus:'Magic Dodge',cooldownReduction:'Cooldown Recovery'};
function fresh(){return{treasury:0,trophies:[],unlocks:['Warrior','Paladin','Rogue','Ranger','Mage','Priest'],history:[],upgrades:{supplies:0,recovery:0,armory:0},run:null}}
function load(){try{return Object.assign(fresh(),JSON.parse(localStorage.getItem(SAVE_KEY)||'null')||{})}catch{return fresh()}}
function save(){localStorage.setItem(SAVE_KEY,JSON.stringify(state))}
function toast(msg){const e=document.createElement('div');e.className='toast';e.textContent=msg;$('#toast').append(e);setTimeout(()=>e.remove(),2600)}
function heroPower(h){return Math.round(h.maxHp/5+h.atk*3+h.speed*20)}
function makeHero(level=1,forcedClass=null){const cls=forcedClass||pick(state.unlocks),base=CLASSES[cls],ability=ABILITIES[cls],bonus=state.upgrades.armory||0,races=Object.keys(RACE_DATA);return{id:uid(),name:pick(NAMES),class:cls,race:pick(races)||'Human',rarity:pick(CHARACTER_RARITIES.slice(0,3)),trait:pick(CHARACTER_TRAITS),subclass:null,level,xp:0,maxHp:Math.round(base.hp*(1+(level-1)*.13)),hp:Math.round(base.hp*(1+(level-1)*.13)),maxMana:ability.maxMana,mana:ability.maxMana,manaRegen:ability.regen,abilityCooldown:0,atk:Math.round(base.atk*(1+(level-1)*.11))+bonus*2,speed:base.speed,crit:.05,gear:{Weapon:{name:'Guild-Issue '+cls+' Weapon',slot:'Weapon',rarity:'Common',tier:1,weaponPower:5+bonus*3,weaponTemplate:Object.keys(ITEM_DATA.weapons).find(n=>n.toLowerCase().replace(/ /g,'')===base.weapon.replace('.png','').replace('-',''))||null,image:`images/items/weapons/${base.weapon}`},Armor:null,Accessory:null},kills:0,damage:0}}
function classRoster(level){return state.unlocks.map(cls=>makeHero(level,cls))}
function ensureHeroResources(h){const a=ABILITIES[h.class];h.race=h.race||'Human';h.rarity=h.rarity||'Common';h.trait=h.trait||'Balanced';h.subclass=h.subclass??null;h.maxMana=h.maxMana||a.maxMana;h.mana=Math.min(h.maxMana,h.mana??h.maxMana);h.manaRegen=h.manaRegen||a.regen;h.abilityCooldown=Math.max(0,h.abilityCooldown||0);return h}
function beginDraft(){draftSelection=[];state.draft=classRoster(1);save();renderDraft()}
function toggleDraft(id){const i=draftSelection.indexOf(id);if(i>=0)draftSelection.splice(i,1);else if(draftSelection.length<2)draftSelection.push(id);renderDraft()}
function startRun(){if(draftSelection.length!==2)return;const heroes=state.draft.filter(h=>draftSelection.includes(h.id));state.run={id:uid(),started:Date.now(),region:0,step:0,encounters:0,gold:40+(state.upgrades.supplies||0)*20,heroes,perks:[],nodes:makeRegionMap(),mode:'map',pendingReward:null,battle:null,log:[]};delete state.draft;save();render()}
function makeNodes(){const pool=['combat','combat','event','camp','treasure','merchant','elite'];return Array.from({length:3},()=>pick(pool))}
function makeRegionMap(){return Array.from({length:5},makeNodes)}
function img(path,cls='portrait'){return `<img class="${cls}" src="${ASSET}${path}" alt="">`}
function heroCard(h){ensureHeroResources(h);const hp=clamp(h.hp/h.maxHp*100,0,100),base=CLASSES[h.class];return `<div class="hero ${h.hp<=0?'dead':''}" onclick="event.stopPropagation();inspectHero(${h.id})" role="button" tabindex="0" title="Inspect ${h.name}">${img('classes/'+base.icon)}<div><div class="name">${h.name}</div><div class="sub">${h.race} · ${h.class} · Lv. ${h.level} · ${h.rarity}</div><div class="bar"><i style="width:${hp}%"></i></div><div class="stats"><span>${Math.max(0,Math.ceil(h.hp))}/${h.maxHp} HP</span><span>${effectiveAtk(h)} ATK</span><span>${heroPower(h)} PWR</span></div></div><div class="gear">${['Weapon','Armor','Accessory'].map((slot,i)=>`<span class="gearSlot" onclick="event.stopPropagation();inspectGear(${h.id},'${slot}')">${['⚔','▣','◇'][i]} ${h.gear[slot]?.name||'Empty '+slot}</span>`).join('')}</div><span class="inspectHint">Click character or gear to inspect</span></div>`}
function findHero(id){return state.run?.heroes.find(h=>h.id===id)||(state.draft||[]).find(h=>h.id===id)||(state.run?.recruitChoices||[]).find(h=>h.id===id)}
function heroSheetStats(h){const base=CHARACTER_BASE[h.class],gear=gearStats(h),race=RACE_DATA[h.race]||{},mult=race.mult||{},flat=race.flat||{},level=Math.max(0,h.level-1),scaled=(key,growth=1)=>Math.round(((base[key]||0)+level*growth+(gear[key]||0))*(mult[key]||1));return{hp:h.maxHp,mana:h.maxMana,str:scaled('str',1.5),dex:scaled('dex',1.5),int:scaled('int',1.5),def:scaled('def',1),mdef:scaled('mdef',1),block:(base.block||0)+(gear.block||0)+(flat.block||0),manaRegen:h.manaRegen+gear.manaRegen+(flat.manaRegen||0),attackSpeed:(h.speed*(1+gear.attackSpeed/100+(flat.attackSpeed||0))),crit:h.crit+gear.critChance,regen:gear.regen+(flat.regen||0),physicalDodge:gear.physicalDodgeBonus+(flat.physicalDodge||0),magicalDodge:gear.magicalDodgeBonus+(flat.magicalDodge||0)}}
function inspectHero(id){const h=findHero(id);if(!h)return;const z=heroSheetStats(h),race=RACE_DATA[h.race]||{},sub=(SUBCLASS_DATA[h.class]||[]).find(x=>x.id===h.subclass);showOverlay(h.name,`<div class="characterInspect"><div class="characterIdentity">${img('classes/'+CLASSES[h.class].icon)}<div><h3>${h.name}</h3><div class="muted">${sub?.name||h.class} · ${h.race} · Level ${h.level} · <span class="rarity-${h.rarity}">${h.rarity}</span></div><div class="muted">${h.trait} · ${ABILITIES[h.class].name}</div></div></div><div class="statSheet">${[['HP',z.hp],['Mana',z.mana],['Mana Regen',z.manaRegen],['Attack',effectiveAtk(h)],['Attack Speed',z.attackSpeed.toFixed(2)+'×'],['STR',z.str],['DEX',z.dex],['INT',z.int],['DEF',z.def],['MDEF',z.mdef],['Block',z.block],['Crit',(z.crit*100).toFixed(1)+'%'],['HP Regen',z.regen],['Physical Dodge',(z.physicalDodge*100).toFixed(1)+'%'],['Magic Dodge',(z.magicalDodge*100).toFixed(1)+'%']].map(([k,v])=>`<div class="sheetStat"><span>${k}</span><strong>${v}</strong></div>`).join('')}</div><section class="inspectSection"><h3>Race · ${h.race}</h3><b>${race.passive||'Heritage'}</b><p class="muted">${race.desc||'No racial modifier.'}</p></section>${sub?`<section class="inspectSection"><h3>${sub.name}</h3><p>${sub.passive}</p><p class="muted">${sub.active}</p></section>`:''}<section class="inspectSection"><h3>Equipment</h3><div class="inspectLoadout">${['Weapon','Armor','Accessory'].map(slot=>{const it=h.gear[slot];return `<button class="gearInspectCard" onclick="closeOverlay();inspectGear(${h.id},'${slot}')"><span>${slot}</span><strong>${it?.name||'Empty'}</strong><small>${it?itemStatLines(it).join(' · '):'Nothing equipped'}</small></button>`}).join('')}</div></section></div><div class="actions"><button class="btn" onclick="closeOverlay()">Close</button></div>`)}
function inspectGear(heroId,slot){const h=findHero(heroId),it=h?.gear?.[slot];if(!h)return;if(!it)return showOverlay('Empty '+slot,`<p class="muted">${h.name} has nothing equipped in this slot.</p><div class="actions"><button class="btn" onclick="closeOverlay();inspectHero(${h.id})">Back to character</button></div>`);showOverlay(it.name,`<div class="selectedItem">${itemArt(it)}<div><div class="name rarity-${it.rarity||'Common'}">${it.name}</div><div class="muted">Tier ${it.tier||1} · ${it.rarity||'Common'} ${slot}${it.armorClass?' · '+it.armorClass:''}</div><div class="itemStats">${itemStatLines(it).map(s=>`<span>${s}</span>`).join('')}</div></div></div><div class="inspectSection"><h3>Equipped by ${h.name}</h3><p class="muted">${it.damageType?`${it.damageType} damage · `:''}${it.weaponTemplate||it.armorClass||slot}</p></div><div class="actions"><button class="btn" onclick="closeOverlay();inspectHero(${h.id})">Back to character</button><button class="btn" onclick="closeOverlay()">Close</button></div>`)}
function header(){const r=state.run;return `<div class="topbar"><div class="title"><h1>Guildmaster: Dungeons</h1><p>${r?`${REGIONS[r.region]?.name||'Expedition Complete'} · ${r.heroes.length} adventurers · ${r.encounters} battles`:'Every expedition writes a new guild legend.'}</p></div><div class="resources"><span class="chip">Treasury <b>${state.treasury}g</b></span>${r?`<span class="chip">Run Gold <b>${r.gold}g</b></span><span class="chip">Region <b>${r.region+1}/4</b></span>`:`<span class="chip">Victories <b>${state.history.filter(x=>x.won).length}</b></span>`}</div></div>`}
function render(){clearInterval(battleTimer);battleTimer=null;cancelAnimationFrame(battleFrame);battleFrame=null;$('#app').innerHTML=`<div class="shell">${header()}${state.run?renderRun():renderGuild()}</div>`;if(state.run?.mode==='combat')startBattleLoop()}
function renderGuild(){const ups=[['supplies','Expedition Supplies','Begin runs with +20 gold per rank',80],['recovery','Recovery Teams','Recover +10% run gold after defeat',120],['armory','Guild Armory','Starter weapons gain +3 power',150]];return `<div class="grid"><section class="panel"><div class="screenTitle"><h2>The Guild Endures</h2><p class="muted">Adventurers come and go. The treasury, discoveries, and their stories remain.</p></div><div class="actions" style="justify-content:center"><button class="btn primary" onclick="beginDraft()">Recruit a New Expedition</button></div><h3 style="margin-top:25px">Guild Investments</h3>${ups.map(([k,n,d,c])=>{const rank=state.upgrades[k]||0,cost=c*(rank+1);return `<div class="upgrade"><div><b>${n} · ${rank}/5</b><div class="muted">${d}</div></div><button class="btn" ${rank>=5||state.treasury<cost?'disabled':''} onclick="buyUpgrade('${k}',${cost})">${rank>=5?'Complete':cost+'g'}</button></div>`}).join('')}</section><aside class="panel"><h3>Hall of Heroes</h3><p class="muted">Victors retire. The fallen are remembered.</p><div class="hallList">${state.history.length?state.history.slice().reverse().map(x=>`<div class="history"><b>${x.won?'VICTORY':'FALLEN'} · ${x.party.join(', ')}</b><div class="muted">Reached ${x.region} · ${x.battles} battles · secured ${x.gold}g</div></div>`).join(''):'<div class="muted">No expeditions recorded yet.</div>'}</div><h3 style="margin-top:16px">Boss Trophies</h3><div class="muted">${state.trophies.length?state.trophies.join('<br>'):'No trophies recovered.'}</div></aside></div>`}
function buyUpgrade(k,cost){if(state.treasury<cost||(state.upgrades[k]||0)>=5)return;state.treasury-=cost;state.upgrades[k]=(state.upgrades[k]||0)+1;save();render()}
function renderDraft(){const candidates=state.draft||[];$('#app').innerHTML=`<div class="shell">${header()}<section class="panel"><div class="screenTitle"><h2>Choose the First Two</h2><p class="muted">Inspect each recruit, then select exactly two.</p></div><div class="heroGrid">${candidates.map(h=>`<div class="choice recruitChoice ${draftSelection.includes(h.id)?'good':''}">${heroCard(h)}<button class="btn ${draftSelection.includes(h.id)?'good':'gold'}" onclick="toggleDraft(${h.id})">${draftSelection.includes(h.id)?'Selected ✓':'Select '+h.class}</button></div>`).join('')}</div><div class="actions" style="justify-content:center"><button class="btn" onclick="delete state.draft;render()">Cancel</button><button class="btn primary" ${draftSelection.length!==2?'disabled':''} onclick="startRun()">Begin with ${draftSelection.length}/2</button></div></section></div>`}
function renderRun(){const r=state.run;if(r.mode==='map')return renderMap();if(r.mode==='combat')return renderCombat();if(r.mode==='reward')return renderReward();if(r.mode==='recruit')return renderRecruit();return renderMap()}
function renderSidebar(){const r=state.run;return `<aside class="panel"><h3>Expedition Party</h3><div class="heroGrid">${r.heroes.map(heroCard).join('')}</div><h3 style="margin-top:15px">Run Boons</h3><div class="muted">${r.perks.length?r.perks.map(p=>'◆ '+p.name).join('<br>'):'No boons yet.'}</div><div class="actions"><button class="btn danger" onclick="confirmAbandon()">Abandon Run</button></div></aside>`}
function renderMap(){const r=state.run,reg=REGIONS[r.region];return `<div class="grid"><section class="panel map" style="background-image:url('${ASSET}backgrounds/${reg.bg}')"><div class="regionHead"><div class="eyebrow">REGION ${r.region+1} · STEP ${Math.min(6,r.step+1)}/6</div><h2>${reg.name}</h2><p class="muted">Choose the party's next destination. The whole region lies ahead.</p></div><div class="path">${r.nodes.map((row,rowIndex)=>`<div class="pathRow">${row.map(type=>{const n=NODE_INFO[type],active=rowIndex===r.step;return `<button class="node ${active?'current':rowIndex<r.step?'done':''}" ${active?'':`disabled`} onclick="chooseNode('${type}')"><span class="nodeIcon">${n[0]}</span><span class="nodeName">${n[1]}</span><div class="nodeDesc">${n[2]}</div></button>`}).join('')}</div>`).join('')}<div class="pathRow"><button class="node ${r.step>=5?'current':''}" ${r.step>=5?'':'disabled'} onclick="chooseNode('boss')"><span class="nodeIcon">♛</span><span class="nodeName">${reg.boss[0]}</span><div class="nodeDesc">Region Boss</div></button></div></div></section>${renderSidebar()}</div>`}
function chooseNode(type){if(type==='combat'||type==='elite'||type==='boss')return beginCombat(type);if(type==='camp'){state.run.heroes.forEach(h=>h.hp=Math.min(h.maxHp,h.hp+h.maxHp*.35));toast('The party recovered 35% health.');return advanceNode()}if(type==='treasure')return treasureEvent();if(type==='merchant')return merchantEvent();return storyEvent()}
function enemyUnit(name,icon,level,elite=false,boss=false){const scale=1+(level-1)*.22;return{id:uid(),name,icon,level,maxHp:Math.round((boss?390:elite?175:105)*scale),hp:Math.round((boss?390:elite?175:105)*scale),atk:Math.round((boss?25:elite?18:12)*scale),speed:boss?1.05:elite?1:.85,boss,elite,progress:0}}
function beginCombat(type){const r=state.run,reg=REGIONS[r.region],level=1+r.region*5+r.step,boss=type==='boss',elite=type==='elite',count=boss?1:Math.min(4,2+Math.floor(r.region/2)+(elite?1:0));const enemies=Array.from({length:count},()=>{const e=boss?reg.boss:pick(reg.enemies);return enemyUnit(e[0],e[1],level,elite,boss)});r.heroes.forEach(h=>{ensureHeroResources(h);h.abilityCooldown=0});r.battle={type,enemies,heroProgress:{},log:[`${boss?'Boss battle':'Battle'} begins.`]};r.mode='combat';save();render()}
function itemStats(it){const out=Object.fromEntries(ITEM_STAT_KEYS.map(k=>[k,0]));if(!it)return out;if(it.stat)out[it.stat]=(out[it.stat]||0)+(it.value||0);if(it.secondaryStat)out[it.secondaryStat]=(out[it.secondaryStat]||0)+(it.secondaryValue||0);if(it.tertiaryStat)out[it.tertiaryStat]=(out[it.tertiaryStat]||0)+(it.tertiaryValue||0);Object.entries(it.extraStats||{}).forEach(([k,v])=>out[k]=(out[k]||0)+v);ITEM_STAT_KEYS.forEach(k=>{if(k==='critChance')out[k]+=it.weaponCritChance||it[k]||0;else if(k!=='hp'&&k!=='str'&&k!=='dex'&&k!=='int'&&k!=='def'&&k!=='mdef'&&k!=='mana'&&k!=='manaRegen'&&k!=='regen'&&k!=='attackSpeed'&&k!=='lifesteal'&&k!=='fire'&&k!=='ice'&&k!=='poison'&&k!=='lightning'&&k!=='holy'&&k!=='dark')out[k]+=it[k]||0});return out}
function gearStats(h){const out=Object.fromEntries(ITEM_STAT_KEYS.map(k=>[k,0]));Object.values(h.gear||{}).filter(Boolean).forEach(it=>{const stats=itemStats(it);ITEM_STAT_KEYS.forEach(k=>out[k]+=stats[k]||0)});return out}
function itemStatLines(it){const lines=[];if(it.weaponPower)lines.push(`+${it.weaponPower} Attack`);const stats=itemStats(it);ITEM_STAT_KEYS.forEach(k=>{const v=stats[k];if(!v)return;lines.push(`${v>0?'+':''}${PERCENT_STATS.has(k)?Math.round(v*100)+'%':v} ${STAT_LABELS[k]||k}`)});return lines}
function effectiveAtk(h){const perk=state.run?.perks.filter(p=>p.type==='attack').reduce((a,p)=>a+p.value,0)||0,gs=gearStats(h),primary=CLASSES[h.class].stat.toLowerCase();return Math.round((h.atk+(h.gear.Weapon?.weaponPower||h.gear.Weapon?.power||0)+(gs[primary]||0)*.75)*(1+perk+gs.damageBonus))}
function startBattleLoop(){if(battleTimer)return;lastCombatTick=performance.now();battleTimer=setInterval(combatTick,260);battleFrame=requestAnimationFrame(animateCombatMeters)}
function animateCombatMeters(now){const r=state.run,b=r?.battle;if(!b||r.mode!=='combat')return;const elapsed=Math.min(.26,(now-lastCombatTick)/1000);r.heroes.forEach(h=>{const e=$(`#unit-${h.id}`);if(!e||h.hp<=0)return;const gs=gearStats(h),speed=h.speed*(1+gs.attackSpeed/100)*(1+r.perks.filter(p=>p.type==='speed').reduce((a,p)=>a+p.value,0)),attack=Math.min(4,(b.heroProgress[h.id]||0)+speed*elapsed/0.26),mana=Math.min(h.maxMana,h.mana+(h.manaRegen+gs.manaRegen)*elapsed),cooldown=Math.max(0,(h.abilityCooldown||0)-elapsed*(1+gs.cooldownReduction)),bars=e.querySelectorAll('.bar i');if(bars[1])bars[1].style.width=clamp(mana/h.maxMana*100,0,100)+'%';if(bars[2])bars[2].style.width=clamp((1-cooldown/ABILITIES[h.class].cooldown)*100,0,100)+'%';if(bars[3])bars[3].style.width=clamp(attack/4*100,0,100)+'%'});b.enemies.forEach(u=>{const e=$(`#unit-${u.id}`),bar=e?.querySelectorAll('.bar i')[1];if(bar)bar.style.width=clamp(((u.progress||0)+u.speed*elapsed/0.26)/4*100,0,100)+'%'});battleFrame=requestAnimationFrame(animateCombatMeters)}
function castHeroAbility(h,livingH,livingE,b){const a=ABILITIES[h.class],gs=gearStats(h);if(!a||h.abilityCooldown>0||h.mana<a.cost)return false;const wounded=livingH.some(x=>x.hp/x.maxHp<.9);if((h.class==='Priest'||h.class==='Paladin')&&!wounded)return false;h.mana-=a.cost;h.abilityCooldown=a.cooldown;let message='';if(h.class==='Priest'){const target=[...livingH].sort((x,y)=>x.hp/x.maxHp-y.hp/y.maxHp)[0],heal=Math.round(effectiveAtk(h)*1.8*(1+gs.healingPower+gs.healBonus));target.hp=Math.min(target.maxHp,target.hp+heal);message=`${h.name} casts Mend on ${target.name} for ${heal}.`}else if(h.class==='Paladin'){const target=[...livingH].sort((x,y)=>x.hp/x.maxHp-y.hp/y.maxHp)[0],heal=Math.round(effectiveAtk(h)*1.15*(1+gs.healingPower+gs.healBonus));target.hp=Math.min(target.maxHp,target.hp+heal);message=`${h.name} invokes Holy Guard, restoring ${heal} health.`}else{const targets=(h.class==='Warrior'||h.class==='Ranger')?livingE.filter(x=>x.hp>0):[pick(livingE.filter(x=>x.hp>0))];const mult=({Warrior:1.05,Ranger:.9,Rogue:2.15,Mage:2}[h.class]||1.5)*(1+gs.elementalDamage+gs.statusChance*.25);let total=0;targets.forEach(target=>{const dmg=Math.round(effectiveAtk(h)*mult*(.9+Math.random()*.2));target.hp-=dmg;total+=dmg;if(target.hp<=0)h.kills++});h.damage+=total;message=`${h.name} uses ${a.name} for ${total} damage${targets.length>1?' across the enemy line':''}.`}b.log.unshift(message);return true}
function combatTick(){lastCombatTick=performance.now();const r=state.run,b=r?.battle;if(!r||r.mode!=='combat'||!b)return;const livingH=r.heroes.filter(h=>h.hp>0),livingE=b.enemies.filter(e=>e.hp>0);if(!livingH.length)return endRun(false);if(!livingE.length)return winBattle();r.heroes.forEach(h=>{if(h.hp<=0)return;const gs=gearStats(h);h.mana=Math.min(h.maxMana,h.mana+(h.manaRegen+gs.manaRegen)*.26);h.hp=Math.min(h.maxHp,h.hp+gs.regen*.26);h.abilityCooldown=Math.max(0,(h.abilityCooldown||0)-.26*(1+gs.attackSpeed/200));if(castHeroAbility(h,livingH,livingE,b))return;b.heroProgress[h.id]=(b.heroProgress[h.id]||0)+h.speed*(1+gs.attackSpeed/100)*(1+r.perks.filter(p=>p.type==='speed').reduce((a,p)=>a+p.value,0));if(b.heroProgress[h.id]>=4){b.heroProgress[h.id]=0;const target=pick(livingE.filter(x=>x.hp>0)),crit=Math.random()<h.crit+gs.critChance+r.perks.filter(p=>p.type==='crit').reduce((a,p)=>a+p.value,0),variance=.14+(gs.damageVariance||0),dmg=Math.round(effectiveAtk(h)*(crit?1.75+gs.critDamage:1)*(1-variance+Math.random()*variance*2));target.hp-=dmg;h.hp=Math.min(h.maxHp,h.hp+dmg*gs.lifesteal/100);h.damage+=dmg;if(target.hp<=0)h.kills++;b.log.unshift(`${h.name} hits ${target.name} for ${dmg}${crit?' critical':''}.`)}});b.enemies.forEach(e=>{if(e.hp<=0)return;e.progress+=e.speed;if(e.progress>=4){e.progress=0;const target=pick(livingH),gs=gearStats(target);if(Math.random()<gs.parry){b.log.unshift(`${target.name} parries ${e.name}.`);return}const dmg=Math.max(1,Math.round(e.atk*(.82+Math.random()*.3)*100/(100+gs.def*3)));target.hp-=dmg;b.log.unshift(`${e.name} hits ${target.name} for ${dmg}.`)}});b.log=b.log.slice(0,14);save();updateCombatDom()}
function unitCard(u,enemy=false){const hp=clamp(u.hp/u.maxHp*100,0,100),path=enemy?'enemies/'+u.icon:'classes/'+CLASSES[u.class].icon,attack=enemy?u.progress||0:state.run.battle.heroProgress[u.id]||0;if(enemy)return `<div class="unit enemy ${u.hp<=0?'dead':''}" id="unit-${u.id}"><div class="unitName">Lv. ${u.level} · ${u.name}</div>${img(path)}<div class="meterLabel"><span>Health</span><span class="hpText">${Math.max(0,Math.ceil(u.hp))}/${u.maxHp}</span></div><div class="bar"><i style="width:${hp}%"></i></div><div class="meterLabel"><span>Attack</span><span>incoming</span></div><div class="bar attackBar"><i style="width:${clamp(attack/4*100,0,100)}%"></i></div></div>`;const a=ABILITIES[u.class],mana=clamp(u.mana/u.maxMana*100,0,100),cd=clamp((1-(u.abilityCooldown||0)/a.cooldown)*100,0,100);return `<div class="unit ${u.hp<=0?'dead':''}" id="unit-${u.id}"><div class="unitName">${u.name}<small>${u.class}</small></div>${img(path)}<div class="meterLabel"><span>Health</span><span class="hpText">${Math.max(0,Math.ceil(u.hp))}/${u.maxHp}</span></div><div class="bar"><i style="width:${hp}%"></i></div><div class="meterLabel"><span>Mana</span><span class="manaText">${Math.floor(u.mana)}/${u.maxMana}</span></div><div class="bar mana"><i style="width:${mana}%"></i></div><div class="abilityLine"><span>${a.name} · ${a.cost} MP</span><span class="cooldownText">${u.abilityCooldown>0?u.abilityCooldown.toFixed(1)+'s':'READY'}</span></div><div class="bar cooldown"><i style="width:${cd}%"></i></div><div class="bar attackBar" title="Basic attack timer"><i style="width:${clamp(attack/4*100,0,100)}%"></i></div></div>`}
function renderCombat(){const r=state.run,b=r.battle,reg=REGIONS[r.region];r.heroes.forEach(ensureHeroResources);b.heroProgress=b.heroProgress||{};return `<section class="panel combatField" style="background-image:url('${ASSET}backgrounds/${reg.bg}')"><div class="regionHead"><div class="eyebrow">${b.type==='boss'?'REGION BOSS':b.type==='elite'?'ELITE BATTLE':'BATTLE'}</div><h2>${reg.name}</h2></div><div class="combatSides"><div class="combatSide">${r.heroes.map(h=>unitCard(h)).join('')}</div><div class="combatSide">${b.enemies.map(e=>unitCard(e,true)).join('')}</div></div><div class="combatLog">${b.log.join('<br>')}</div></section>`}
function updateCombatDom(){const r=state.run,b=r?.battle;if(!b)return;[...r.heroes,...b.enemies].forEach(u=>{const e=$(`#unit-${u.id}`);if(!e)return;const bars=e.querySelectorAll('.bar i'),enemy=!u.class,attack=enemy?u.progress||0:b.heroProgress[u.id]||0;if(bars[0])bars[0].style.width=clamp(u.hp/u.maxHp*100,0,100)+'%';const hpText=e.querySelector('.hpText');if(hpText)hpText.textContent=`${Math.max(0,Math.ceil(u.hp))}/${u.maxHp}`;if(enemy){if(bars[1])bars[1].style.width=clamp(attack/4*100,0,100)+'%'}else{const a=ABILITIES[u.class];if(bars[1])bars[1].style.width=clamp(u.mana/u.maxMana*100,0,100)+'%';if(bars[2])bars[2].style.width=clamp((1-(u.abilityCooldown||0)/a.cooldown)*100,0,100)+'%';if(bars[3])bars[3].style.width=clamp(attack/4*100,0,100)+'%';e.querySelector('.manaText').textContent=`${Math.floor(u.mana)}/${u.maxMana}`;e.querySelector('.cooldownText').textContent=u.abilityCooldown>0?u.abilityCooldown.toFixed(1)+'s':'READY'}e.classList.toggle('dead',u.hp<=0)});const log=$('.combatLog');if(log)log.innerHTML=b.log.join('<br>')}
function winBattle(){clearInterval(battleTimer);battleTimer=null;const r=state.run,b=r.battle,boss=b.type==='boss',elite=b.type==='elite';r.encounters++;const gold=Math.round((18+r.region*22+r.step*6)*(elite?1.8:boss?3:1)*(1+r.perks.filter(p=>p.type==='gold').reduce((a,p)=>a+p.value,0)));r.gold+=gold;r.heroes.forEach(h=>{if(h.hp>0){h.xp++;if(h.xp%2===0){h.level++;h.maxHp=Math.round(h.maxHp*1.12);h.hp=Math.min(h.maxHp,h.hp+Math.round(h.maxHp*.25));h.atk=Math.round(h.atk*1.1)}const heal=r.perks.filter(p=>p.type==='heal').reduce((a,p)=>a+p.value,0);h.hp=Math.min(h.maxHp,h.hp+h.maxHp*heal)}});if(boss){state.trophies.push(`${REGIONS[r.region].boss[0]} defeated`);r.battle=null;if(r.region===REGIONS.length-1)return endRun(true);r.mode='recruit';r.recruitChoices=classRoster(1+(r.region+1)*5);save();render();return}r.pendingReward=makeRewards(elite);r.battle=null;r.mode='reward';save();render()}
function equipmentPrimaryValue(base,tier,rarity){return Math.round(base*Math.pow(1.6,Math.max(0,tier-1))*(ITEM_RARITY_MULTIPLIER[rarity]||1))}
function rollRarity(tier,elite){const n=Math.random()-(elite?.15:0)-tier*.025;return n<.025?'Mythic':n<.08?'Legendary':n<.2?'Epic':n<.42?'Rare':n<.72?'Uncommon':'Common'}
function applyRarityAffixes(it){const rank=['Common','Uncommon','Rare','Epic','Legendary','Mythic'].indexOf(it.rarity);if(rank>=2){const pool=['lifesteal','regen','mana','manaRegen','attackSpeed','fire','ice','poison','lightning','holy','dark','str','dex','int','mdef'];it.secondaryStat=pick(pool);it.secondaryValue=['lifesteal','attackSpeed'].includes(it.secondaryStat)?2+rank:['regen','manaRegen'].includes(it.secondaryStat)?Math.max(1,Math.floor(rank/2)):2+rank*2}if(rank>=4){const pool=['regen','manaRegen','attackSpeed','def','mdef','critChance','critDamage'];it.tertiaryStat=pick(pool);it.tertiaryValue=PERCENT_STATS.has(it.tertiaryStat)?.03+rank*.01:2+rank}return it}
function makeItem(elite=false){const tier=state.run.region+1,rarity=rollRarity(tier,elite),kind=pick(['Weapon','Armor','Accessory']);if(kind==='Weapon'&&Object.keys(ITEM_DATA.weapons).length){const name=pick(Object.keys(ITEM_DATA.weapons)),w=ITEM_DATA.weapons[name],it={id:uid(),slot:'Weapon',name,rarity,tier,weaponTemplate:name,weaponPower:equipmentPrimaryValue(w.base+2,tier,rarity),stat:w.scale,value:Math.max(1,Math.round((2+tier*.7)*(1+['Common','Uncommon','Rare','Epic','Legendary','Mythic'].indexOf(rarity)*.08))),damageType:w.type,image:w.image,...Object.fromEntries(['armorPen','parry','critDamage','accuracy','elementalDamage','healingPower','statusChance','cleave','counter','damageVariance'].map(k=>[k,w[k]||0])),weaponCritChance:w.critChance||0};return applyRarityAffixes(it)}if(kind==='Armor'&&Object.keys(ITEM_DATA.armorProfiles).length){const choices=Object.entries(ITEM_DATA.armorProfiles).filter(([,p])=>(p.tier||1)<=tier),[name,p]=pick(choices);return applyRarityAffixes({id:uid(),slot:'Armor',name,rarity,tier,armorClass:p.armorClass,stat:p.stat,value:equipmentPrimaryValue(p.base+2,tier,rarity),block:p.block||0,image:`images/items/armor/${itemSlug(name)}.png`})}const ring=Math.random()<.5,name=ring?pick(['Band','Signet','Ring']):pick(['Charm','Pendant','Amulet']),stat=ring?pick(['str','dex','int','def','mdef']):pick(['hp','mana','mdef','int']);return applyRarityAffixes({id:uid(),slot:'Accessory',name,rarity,tier,stat,value:equipmentPrimaryValue(stat==='hp'?16:stat==='mana'?10:4.8,tier,rarity),image:`images/items/accessories/${ring?'ring':'amulet'}.png`})}
function makeRewards(elite){return[{kind:'item',item:makeItem(elite)},{kind:'gold',amount:35+state.run.region*30},{kind:'perk',perk:pick(PERKS)}]}
function itemFolder(slot){return slot==='Weapon'?'weapons':slot==='Armor'?'armor':'accessories'}
function itemSlug(name){return String(name||'default').toLowerCase().replace(/['’]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')}
function itemArt(it){const src=it.image?`../guildmaster/${it.image}`:`${ASSET}items/${itemFolder(it.slot)}/${itemSlug(it.name)}.png`;return `<span class="itemIcon"><img src="${src}" alt="" onerror="this.style.display='none';this.nextElementSibling.style.display='grid'"><span class="itemFallback">${it.slot==='Weapon'?'⚔':it.slot==='Armor'?'▣':'◇'}</span></span>`}
function renderReward(){const r=state.run;return `<section class="panel rewardsPanel"><div class="screenTitle"><div class="eyebrow">VICTORY SPOILS</div><h2>Choose One Reward</h2><p class="muted">Everything else is left behind.</p></div><div class="choiceGrid">${r.pendingReward.map((x,i)=>x.kind==='item'?`<button class="choice rewardChoice" onclick="takeReward(${i})">${itemArt(x.item)}<strong class="rarity-${x.item.rarity}">${x.item.name}</strong><div class="rewardType">Tier ${x.item.tier} · ${x.item.rarity} ${x.item.slot}</div><div class="itemStats">${itemStatLines(x.item).map(s=>`<span>${s}</span>`).join('')}</div><span class="choiceHint">Choose who equips it →</span></button>`:x.kind==='gold'?`<button class="choice rewardChoice" onclick="takeReward(${i})"><span class="big">◉</span><strong>${x.amount} Run Gold</strong><div class="muted">Spend it now or risk carrying it home.</div><span class="choiceHint">Take reward →</span></button>`:`<button class="choice rewardChoice" onclick="takeReward(${i})"><span class="big">◆</span><strong>${x.perk[0]}</strong><div class="muted">${x.perk[1]} for this run.</div><span class="choiceHint">Take boon →</span></button>`).join('')}</div></section>`}
function takeReward(i){const x=state.run.pendingReward[i];if(x.kind==='item')return chooseEquipTarget(x.item);if(x.kind==='gold')state.run.gold+=x.amount;else if(x.kind==='perk'){state.run.perks.push({name:x.perk[0],type:x.perk[2],value:x.perk[3]});if(x.perk[2]==='hp')state.run.heroes.forEach(h=>{const gain=Math.round(h.maxHp*x.perk[3]);h.maxHp+=gain;h.hp+=gain})}state.run.pendingReward=null;advanceNode()}
function canEquip(h,item){if(item.slot==='Weapon')return !Object.keys(ITEM_DATA.weapons).length||CLASSES[h.class].weapons?.includes(item.name);if(item.slot==='Armor'){const order={Light:1,Medium:2,Heavy:3};return (order[item.armorClass]||1)<=(order[CLASSES[h.class].armor]||1)}return true}
function statComparison(item,old){const next=itemStats(item),prev=itemStats(old),lines=[];if(item.weaponPower||old?.weaponPower){const d=(item.weaponPower||0)-(old?.weaponPower||old?.power||0);if(d)lines.push(`<b class="${d>0?'gain':'loss'}">${d>0?'+':''}${d} Attack</b>`)}ITEM_STAT_KEYS.forEach(k=>{const d=(next[k]||0)-(prev[k]||0);if(!d)return;lines.push(`<b class="${d>0?'gain':'loss'}">${d>0?'+':''}${PERCENT_STATS.has(k)?Math.round(d*100)+'%':d} ${STAT_LABELS[k]}</b>`)});return lines.join('')||'<span class="muted">No stat change</span>'}
function chooseEquipTarget(item){const heroes=state.run.heroes.filter(h=>h.hp>0);showOverlay('Equip '+item.name,`<div class="selectedItem">${itemArt(item)}<div><div class="name rarity-${item.rarity}">${item.name}</div><div class="muted">Tier ${item.tier} · ${item.rarity} ${item.slot}</div><div class="itemStats">${itemStatLines(item).map(s=>`<span>${s}</span>`).join('')}</div></div></div><p class="muted">Choose a compatible adventurer. Their current ${item.slot.toLowerCase()} will be replaced.</p><div class="equipGrid">${heroes.map(h=>{const old=h.gear[item.slot],allowed=canEquip(h,item);return `<button class="choice equipChoice" ${allowed?'':'disabled'} onclick="equipReward(${item.id},${h.id})">${img('classes/'+CLASSES[h.class].icon)}<strong>${h.name}</strong><div class="muted">${h.class}${allowed?'':' · Cannot equip'}</div><div class="gearCompare"><span>${old?.name||'Empty slot'}</span>${allowed?statComparison(item,old):'<b class="loss">Incompatible equipment type</b>'}</div></button>`}).join('')}</div><div class="actions"><button class="btn" onclick="closeOverlay()">Back to rewards</button></div>`)}
function equipReward(itemId,heroId){const item=state.run.pendingReward.find(x=>x.item?.id===itemId)?.item,hero=state.run.heroes.find(h=>h.id===heroId);if(!item||!hero||!canEquip(hero,item))return;const oldStats=gearStats(hero),hpRatio=hero.hp/hero.maxHp,manaRatio=hero.mana/hero.maxMana;hero.gear[item.slot]=item;const newStats=gearStats(hero);hero.maxHp=Math.max(1,hero.maxHp+(newStats.hp-oldStats.hp));hero.hp=Math.max(1,hero.maxHp*hpRatio);hero.maxMana=Math.max(0,hero.maxMana+(newStats.mana-oldStats.mana));hero.mana=hero.maxMana*manaRatio;state.run.pendingReward=null;closeOverlay();toast(`${hero.name} equipped ${item.name}.`);advanceNode()}
function equipBest(item){const heroes=state.run.heroes.filter(h=>h.hp>0),h=[...heroes].sort((a,b)=>(a.gear[item.slot]?.power||0)-(b.gear[item.slot]?.power||0))[0]||state.run.heroes[0];h.gear[item.slot]=item;toast(`${h.name} equipped ${item.name}.`)}
function advanceNode(){const r=state.run;r.step++;r.mode='map';save();render()}
function renderRecruit(){const r=state.run;return `<section class="panel"><div class="screenTitle"><h2>A Survivor Joins the Road</h2><p class="muted">Inspect the candidates and recruit one before entering ${REGIONS[r.region+1].name}.</p></div><div class="heroGrid">${r.recruitChoices.map((h,i)=>`<div class="choice recruitChoice">${heroCard(h)}<button class="btn gold" onclick="takeRecruit(${i})">Recruit ${h.class}</button></div>`).join('')}</div></section>`}
function takeRecruit(i){const r=state.run,h=r.recruitChoices[i],hpBonus=r.perks.filter(p=>p.type==='hp').reduce((a,p)=>a+p.value,0);if(hpBonus){h.maxHp=Math.round(h.maxHp*(1+hpBonus));h.hp=h.maxHp}r.heroes.push(h);r.region++;r.step=0;r.nodes=makeRegionMap();r.mode='map';delete r.recruitChoices;r.heroes.forEach(hero=>hero.hp=Math.max(1,Math.min(hero.maxHp,hero.hp+hero.maxHp*.35)));save();render()}
function treasureEvent(){const item=makeItem(false),gold=30+state.run.region*25;showOverlay('An Abandoned Cache',`<p class="muted">The party can only carry one prize safely.</p><div class="choiceGrid"><button class="choice" onclick="eventItem(${JSON.stringify(item).replace(/"/g,'&quot;')})"><strong>${item.name}</strong><div class="muted">${item.rarity} ${item.slot} · +${item.power} power</div></button><button class="choice" onclick="eventGold(${gold})"><strong>${gold} Gold</strong><div class="muted">Add it to the run purse.</div></button></div>`)}
function eventItem(item){equipBest(item);closeOverlay();advanceNode()}function eventGold(n){state.run.gold+=n;closeOverlay();advanceNode()}
function storyEvent(){const h=pick(state.run.heroes),events=[['A Broken Oath',`${h.name} finds the banner of a failed expedition.`,`Honor the fallen`,`Party gains 10% maximum HP`,`Strip it for valuables`,`Gain 55 gold`],['The Narrow Bridge','Something follows beneath the bridge.','Cross carefully','Heal the most wounded hero','Set an ambush','Gain 12% party attack'],['A Familiar Voice',`${h.name} hears someone calling from the dark.`,'Follow the voice','Gain a random item','Keep moving','Gain 40 gold']];const e=pick(events);showOverlay(e[0],`<p>${e[1]}</p><div class="choiceGrid"><button class="choice" onclick="resolveStory(0)"><strong>${e[2]}</strong><div class="muted">${e[3]}</div></button><button class="choice" onclick="resolveStory(1)"><strong>${e[4]}</strong><div class="muted">${e[5]}</div></button></div>`)}
function resolveStory(i){if(i===0){if(Math.random()<.5){state.run.perks.push({name:'Oathbound',type:'hp',value:.1});state.run.heroes.forEach(h=>{h.maxHp=Math.round(h.maxHp*1.1);h.hp=Math.min(h.maxHp,h.hp+h.maxHp*.2)})}else equipBest(makeItem(false))}else{if(Math.random()<.5)state.run.gold+=55;else state.run.perks.push({name:'Ambush Training',type:'attack',value:.12})}closeOverlay();advanceNode()}
function merchantEvent(){const items=[makeItem(),makeItem()],cost=45+state.run.region*25;showOverlay('The Road Trader',`<p class="muted">Run gold spent here cannot reach the guild—but it may keep this party alive.</p><div class="choiceGrid">${items.map((it,i)=>`<button class="choice" ${state.run.gold<cost?'disabled':''} onclick="buyRunItem(${JSON.stringify(it).replace(/"/g,'&quot;')},${cost})"><strong>${it.name}</strong><div class="muted">${it.rarity} · ${cost}g</div></button>`).join('')}<button class="choice" onclick="closeOverlay();advanceNode()"><strong>Leave</strong><div class="muted">Keep your gold.</div></button></div>`)}
function buyRunItem(item,cost){if(state.run.gold<cost)return;state.run.gold-=cost;equipBest(item);closeOverlay();advanceNode()}
function showOverlay(title,body){document.body.insertAdjacentHTML('beforeend',`<div class="overlay" id="overlay"><section class="panel modal"><h2>${title}</h2>${body}</section></div>`)}function closeOverlay(){$('#overlay')?.remove()}
function confirmAbandon(){showOverlay('Abandon this expedition?',`<p>The party will disband. The guild recovers a portion of its ${state.run.gold} run gold.</p><div class="actions"><button class="btn" onclick="closeOverlay()">Continue Run</button><button class="btn danger" onclick="closeOverlay();endRun(false)">Abandon Expedition</button></div>`)}
function endRun(won){clearInterval(battleTimer);battleTimer=null;const r=state.run,recovery=won?1:Math.min(.7,.2+(state.upgrades.recovery||0)*.1),secured=Math.round(r.gold*recovery),names=r.heroes.map(h=>h.name);state.treasury+=secured;state.history.push({won,party:names,region:REGIONS[Math.min(r.region,3)].name,battles:r.encounters,gold:secured,date:Date.now()});if(state.history.length>30)state.history.shift();state.run=null;save();$('#app').innerHTML=`<div class="shell">${header()}<section class="panel banner"><h2>${won?'Expedition Conquered':'The Expedition Is Lost'}</h2><p>${won?`${names.join(', ')} retire as legends.`:`${names.join(', ')} will not return to the road.`}</p><p class="muted">${secured} gold reached the guild treasury. A new expedition will require new adventurers.</p><button class="btn primary" onclick="render()">Return to Guild</button></section></div>`}
async function init(){try{const [items,races,subclasses]=await Promise.all([fetch(ITEM_DATA_URL),fetch('../guildmaster/data/races.json'),fetch('../guildmaster/data/subclasses.json')]);if(!items.ok||!races.ok||!subclasses.ok)throw new Error('Shared Guildmaster data unavailable');[ITEM_DATA,RACE_DATA,SUBCLASS_DATA]=await Promise.all([items.json(),races.json(),subclasses.json()])}catch(error){console.warn('Guildmaster shared data could not be loaded; fallback values will be used.',error)}render()}
init();
