const fs=require('node:fs'),assert=require('node:assert/strict');
const html=fs.readFileSync(__dirname+'/index.html','utf8');
const css=fs.readFileSync(__dirname+'/styles.css','utf8');
const js=fs.readFileSync(__dirname+'/game.js','utf8');
assert.match(html,/Guildmaster: Dungeons/);
assert.match(js,/function beginDraft\(/,'a new expedition begins with a recruit draft');
assert.match(js,/draftSelection\.length!==2/,'exactly two adventurers start a run');
assert.match(js,/function makeRegionMap\(\)/,'regions use a persistent branching node map');
assert.match(js,/Array\.from\(\{length:5\},makeNodes\)/,'each region has five encounters before its boss');
assert.match(js,/r\.heroes\.push\(h\);r\.region\+\+/,'one adventurer joins after a cleared boss');
assert.match(js,/state\.treasury\+=secured/,'gold is secured as persistent treasury currency');
assert.match(js,/state\.history\.push/,'finished parties enter persistent history');
assert.match(js,/localStorage\.setItem\(SAVE_KEY/,'campaign progression is persisted separately');
assert.match(css,/\.combatField/,'the game includes a visual combat field');
assert.match(js,/const ABILITIES=/,'combat defines class abilities, mana costs, and cooldowns');
assert.match(js,/function castHeroAbility\(/,'heroes use visible class abilities during combat');
assert.match(js,/classRoster\(1\+\(r\.region\+1\)\*5\)/,'post-boss recruitment offers one hero of each class');
assert.match(js,/function chooseEquipTarget\(/,'equipment rewards let the player choose who equips them');
assert.match(js,/function itemFolder\(/,'equipment art uses the correct asset folders');
console.log('Guildmaster: Dungeons smoke tests passed.');
