const fs=require('node:fs'),assert=require('node:assert/strict');
const html=fs.readFileSync(__dirname+'/index.html','utf8');
const css=fs.readFileSync(__dirname+'/styles.css','utf8');
const js=fs.readFileSync(__dirname+'/game.js','utf8');
assert.match(html,/Guildmaster: Dungeons/);
assert.match(js,/function beginDraft\(/,'a new expedition begins with a recruit draft');
assert.match(js,/draftSelection\.filter\(Boolean\)\.length!==2/,'exactly two adventurers start a run');
assert.match(js,/state\.draftSlots=\[classRoster\(1\),classRoster\(1\)\]/,'each party slot receives a separate candidate roster');
assert.match(js,/flatMap\(cls=>Array\.from\(\{length:copies\}/,'class rosters support duplicate-class candidates');
assert.match(js,/function openDraftSlot\(/,'clicking a party slot opens one candidate of each class');
assert.match(js,/function makeRegionMap\(\)/,'regions use a persistent branching node map');
assert.match(js,/Array\.from\(\{length:12\},\(_,index\)=>makeNodes\(index\)\)/,'each region has twelve encounters before its boss');
assert.match(js,/relicRow=step===5\|\|step===10/,'relic vaults have non-conflicting scheduled encounters');
assert.match(js,/if\(relicRow\)return\['relic'\]/,'relic milestone rows contain only the relic vault');
assert.match(js,/if\(shrineRow\)return\['shrine'\]/,'ability shrine milestone rows contain only the shrine');
assert.match(js,/preBossRow=step===12/,'the final encounter row is reserved for pre-boss preparation');
assert.match(js,/if\(preBossRow\)return\['camp',\.\.\.pool\.slice\(0,2\)\]/,'camp is always an option immediately before the boss');
assert.match(js,/function normalizeRegionMap\(/,'saved maps are migrated to the scheduled-camp rules');
assert.match(js,/r\.nodes\.length===12\?r\.nodes:makeRegionMap\(\)/,'old maps migrate to the extended route');
assert.match(js,/ascending=\[\.\.\.nodes\][\s\S]*\.reverse\(\)/,'the encounter route renders upward from the bottom');
assert.match(js,/function focusCurrentMapNode\(/,'the route scrolls to the current encounter');
assert.match(js,/getBoundingClientRect\(\)[\s\S]*scroller\.scrollTop\+=/,'map centering uses coordinates relative to its scroll container');
assert.match(css,/\.mapScroll\{[^}]*overflow-y:auto/,'the encounter tree has independent scrolling');
assert.match(css,/\.runMapGrid>aside\{position:sticky/,'the party remains visible while the route scrolls');
assert.match(js,/r\.heroes\.push\(h\);r\.region\+\+/,'one adventurer joins after a cleared boss');
assert.match(js,/if\(saved\.gems==null\)saved\.gems=saved\.treasury\|\|0/,'old treasury balances migrate safely to gems');
assert.match(js,/state\.gems\+=gems/,'expedition progress awards permanent gems');
assert.match(js,/gems=won\?40\+r\.encounters\*3:Math\.floor\(r\.encounters\/2\)/,'abandoning before an encounter awards no gems');
assert.doesNotMatch(js,/state\.treasury\+=secured/,'run gold can no longer become permanent currency');
assert.match(js,/state\.history\.push/,'finished parties enter persistent history');
assert.match(js,/localStorage\.setItem\(SAVE_KEY/,'campaign progression is persisted separately');
assert.match(css,/\.combatField/,'the game includes a visual combat field');
assert.match(js,/const ABILITIES=/,'combat defines class abilities, mana costs, and cooldowns');
assert.match(js,/function castHeroAbility\(/,'heroes use visible class abilities during combat');
assert.match(js,/r\.recruitChoices=classRoster\(currentPartyLevel\(\)\)/,'post-boss recruitment offers one hero of each class at party level');
assert.match(js,/function chooseInventoryTarget\(/,'inventory equipment lets the player choose who equips it');
assert.match(js,/function itemFolder\(/,'equipment art uses the correct asset folders');
assert.match(js,/requestAnimationFrame\(animateCombatMeters\)/,'combat meters animate every presentation frame');
assert.match(js,/ITEM_DATA_URL='\.\.\/guildmaster\/data\/items\.json'/,'the roguelike loads Guildmaster equipment definitions');
assert.match(js,/function gearStats\(/,'equipment affixes feed into combat stats');
assert.match(js,/function canEquip\(/,'class weapon and armor restrictions are enforced');
assert.match(js,/function inspectHero\(/,'characters open a complete inspector');
assert.match(js,/function inspectGear\(/,'equipped gear opens an item inspector');
assert.match(js,/fetch\('\.\.\/guildmaster\/data\/races\.json'\)/,'the roguelike shares Guildmaster races');
assert.match(js,/\*\(mult\.hp\|\|1\)/,'racial HP multipliers apply during character generation');
assert.match(js,/\*\(mult\.mana\|\|1\)/,'racial Mana multipliers apply during character generation');
assert.match(js,/raceAppliedVersion/,'existing characters receive a one-time race resource migration');
assert.match(js,/raceFlat\.attackSpeed/,'racial Attack Speed affects combat');
assert.match(js,/raceFlat\.regen/,'racial regeneration affects combat');
assert.match(js,/function rollCharacterRarity\(/,'character rarity uses weighted probabilities');
assert.match(js,/function buyRecruitmentFortune\(/,'a separate permanent upgrade improves recruit rarity');
assert.match(js,/function gearSlotVisual\(/,'character cards render equipment artwork');
assert.match(js,/fetch\('\.\.\/guildmaster\/data\/subclasses\.json'\)/,'the roguelike shares Guildmaster subclasses');
assert.match(js,/const TRAINING=/,'guild progression provides permanent combat-stat training');
assert.match(js,/function renderRunInventory\(/,'runs include a functional inventory');
assert.match(js,/state\.gearTierUnlocked=Math\.max/,'boss victories unlock the next equipment tier');
assert.match(js,/function applyRarityAffixes\(/,'drops use Guildmaster rarity affix rules');
assert.match(js,/fetch\('\.\.\/guildmaster\/data\/recipes\.json'\)/,'drops use Guildmaster exact named equipment recipes');
assert.match(js,/function makeRecipeItem\(/,'canonical recipe equipment is converted without dungeon-only names');
assert.match(js,/function partyCanEquip\(/,'generated equipment must be usable by the current party');
assert.match(js,/if\(partyCanEquip\(item\)\)return item/,'item generation filters incompatible equipment');
assert.match(js,/h\.speed\*=h\.slowAttackMigration\?\.35\/\.65:\.35/,'hero basic attacks use the slower versioned timing');
assert.match(js,/event\.target===this\)closeOverlay/,'clicking an overlay backdrop closes its window');
assert.match(js,/function heroXpNeeded\(level\)/,'character XP uses Guildmaster level requirements');
assert.match(js,/function levelBattleParty\(/,'each battle levels the entire party');
assert.match(js,/const target=currentPartyLevel\(\)\+1/,'battle leveling synchronizes every party member');
assert.match(js,/Array\.from\(\{length:6\},makeCanonicalItem\)/,'traders stock six canonical items');
assert.match(js,/class="traderPrice">\$\{cost\}g/,'trader cards show a prominent item cost');
assert.match(js,/boss\?335:elite\?150:105/,'elite and boss durability uses the reduced balance values');
assert.match(js,/boss\?22:elite\?16:12/,'elite and boss damage uses the reduced balance values');
assert.match(js,/const ABILITY_AUGMENTS=/,'runs provide class-specific ability augments');
assert.match(js,/function abilityShrine\(/,'ability shrine encounters build hero abilities');
assert.match(js,/const RELICS=/,'runs provide party-wide relics');
assert.match(js,/function relicVault\(/,'relic vault encounters offer party rule changes');
assert.match(js,/function inspectRelic\(/,'sidebar relics open a description');
assert.match(js,/function inspectBoon\(/,'sidebar boons open a description');
assert.match(js,/row\.length===1\?'singlePathRow'/,'single milestone nodes render without fake alternatives');
assert.match(js,/const CLASS_PASSIVES=/,'character inspection explains class passives');
assert.match(js,/const ABILITY_DESCRIPTIONS=/,'character inspection explains abilities');
assert.match(js,/function processOngoingEffects\(/,'status and renewal effects tick during slower combat');
assert.match(js,/resolveStory\('\$\{effect\}'\)/,'event buttons carry their explicit promised outcome');
assert.match(js,/effect==='randomGear'[\s\S]*r\.inventory\.push\(item\)/,'the random gear event always adds its item to inventory');
assert.match(js,/if\(relicRow\)return\['relic'\]/,'relic vaults are limited to every fifth encounter');
assert.match(js,/shrineRow=step===3\|\|step===8/,'ability shrines are limited to two scheduled encounters');
assert.match(js,/function makeRewards\(\)\{return\[\{kind:'item'[\s\S]*\{kind:'perk'/,'the first reward stage always has the three standard choices');
assert.match(js,/function makeEliteRelicRewards\(/,'elite victories prepare a separate set of relic choices');
assert.match(js,/r\.pendingEliteRelics=elite\?makeEliteRelicRewards\(\):null/,'only elite battles schedule the second reward stage');
assert.match(js,/r\.pendingReward=r\.pendingEliteRelics;delete r\.pendingEliteRelics/,'claiming the normal reward opens the relic selection afterward');
assert.match(js,/state\.run\?\.relics/,'character inspection works before a run exists during party selection');
assert.match(js,/function combatReportRows\(/,'combat renders a per-character live report');
assert.match(js,/damageTaken/,'combat tracks damage taken');
assert.match(js,/applyHealing/,'combat tracks effective healing');
assert.match(js,/Warrior:\{hp:145,atk:17,speed:1\.0,threat:1\.6/,'Warriors use Guildmaster base threat');
assert.match(js,/Paladin:\{hp:170,atk:13,speed:\.85,threat:2/,'Paladins use Guildmaster base threat');
assert.match(js,/function heroThreat\(/,'threat combines class, subclass, and equipment bonuses');
assert.match(js,/sub\?\.threatBonus\|\|0/,'Guardian and Templar subclass threat applies');
assert.match(js,/gear\.threatBonus\|\|0/,'canonical Guildmaster threat equipment applies');
assert.match(js,/function assignPartyFormation\(/,'high-threat durable heroes form the frontline');
assert.match(js,/function threatTarget\(/,'enemy targets are weighted by threat');
assert.match(js,/Math\.random\(\)<\.9\?front:back/,'ordinary enemies strongly prefer the frontline');
console.log('Guildmaster: Dungeons smoke tests passed.');
