const fs=require('node:fs'),assert=require('node:assert/strict');
const html=fs.readFileSync(__dirname+'/index.html','utf8');
const css=fs.readFileSync(__dirname+'/styles.css','utf8');
const js=fs.readFileSync(__dirname+'/game.js','utf8');
assert.match(html,/Guildmaster: Dungeons/);
assert.match(js,/function beginDraft\(/,'a new expedition begins with a recruit draft');
assert.match(js,/draftSelection\.length!==2/,'exactly two adventurers start a run');
assert.match(js,/function makeRegionMap\(\)/,'regions use a persistent branching node map');
assert.match(js,/Array\.from\(\{length:5\},makeNodes\)/,'each region has five encounters before its boss');
assert.match(js,/r\.heroes\.push\(h\);r\.region\+\+/,'one adventurer joins after a cleared boss');
assert.match(js,/state\.treasury\+=secured/,'gold is secured as persistent treasury currency');
assert.match(js,/state\.history\.push/,'finished parties enter persistent history');
assert.match(js,/localStorage\.setItem\(SAVE_KEY/,'campaign progression is persisted separately');
assert.match(css,/\.combatField/,'the game includes a visual combat field');
console.log('Guildmaster: Dungeons smoke tests passed.');
