const fs=require('node:fs');
const vm=require('node:vm');
const assert=require('node:assert/strict');

const app={innerHTML:''},toastTarget={append(){}};
const storage=new Map();
const subclassFixture=JSON.parse(fs.readFileSync(__dirname+'/../guildmaster/data/subclasses.json','utf8'));
const context={
  console,
  performance:{now:()=>0},
  localStorage:{getItem:key=>storage.get(key)||null,setItem:(key,value)=>storage.set(key,value)},
  document:{querySelector:selector=>selector==='#app'?app:selector==='#toast'?toastTarget:null,querySelectorAll:()=>[],createElement:()=>({remove(){}}),body:{insertAdjacentHTML(){}}},
  requestAnimationFrame:()=>0,cancelAnimationFrame(){},setInterval:()=>0,clearInterval(){},
  setTimeout:()=>0,fetch:async()=>({ok:false}),Image:function(){},confirm:()=>true,subclassFixture
};
vm.createContext(context);
let source=fs.readFileSync(__dirname+'/game.js','utf8').replace(/init\(\);\s*$/,'');
source+=`;globalThis.turnTest={
  setup(){RACE_DATA={Human:{mult:{},flat:{}}};SUBCLASS_DATA=JSON.parse(JSON.stringify(subclassFixture));Object.values(SUBCLASS_DATA).flat().forEach(sub=>{Object.assign(sub,SUBCLASS_TURN_OVERRIDES[sub.id]||{});sub.passive=subclassPassiveText(sub);sub.active=subclassActiveText(sub)});state=fresh();const warrior=makeHero(1,'Warrior'),rogue=makeHero(1,'Rogue');state.run={region:0,step:0,encounters:0,gold:0,heroes:[warrior,rogue],inventory:[],consumables:{},perks:[],relics:[],mode:'map'};beginCombat('combat');return state},
  state:()=>state,
  chooseTurnAction,chooseTurnTarget,buildTurnOrder,resortRemainingTurnOrder,heroInitiative,unitCard,turnActionPanel,inspectEnemy,turnDamage,applyHealing,enemyIntent,activateRelic,combatStatusBadges,weaponStatusProfile,weaponProcChance,
  abilities:TURN_ABILITIES,augments:ABILITY_AUGMENTS,subclasses:()=>SUBCLASS_DATA,subclassAbility,executeSubclassAbility,heroSheetStats,effectiveAtk,naturalMaxHp,makeHero,canEquip,applyLayeredDamage,ensureProtection,restoreProtection,protectionStatSheet,physicalDodgeFromDex,magicalDodgeFromInt,abilityPreviewDescription,enemyProtectionValues,heroWeaponDamageType,heroWeaponFamily,stunResistanceChance,classSkillNodes,availableSkillPoints,skillBonus,skillNodeUnlocked,plannedSkillNodeUnlocked,queueSkillNode,confirmSkillPoints,respecSkillTree,enemyUnit,enemyTurn,enemyDamage,applyEnemyControl,interruptEnemy,mergeInventoryItems,itemUpgradeButton,traderRerollCost,consumables:CONSUMABLES,pending:()=>PENDING_SKILL_NODES
}`;
vm.runInContext(source,context);

const api=context.turnTest,state=api.setup(),battle=state.run.battle;
assert.equal(battle.round,1,'combat starts in round one');
assert.equal(battle.activeUnitId,state.run.heroes[1].id,'the higher-Initiative Rogue acts first');
assert.ok(api.heroInitiative(state.run.heroes[1])>api.heroInitiative(state.run.heroes[0]),'class Initiative and Dexterity affect order');
const armoredProfile=api.enemyProtectionValues({name:'Ironback',role:'Bruiser',level:30,maxHp:1000}),casterProfile=api.enemyProtectionValues({name:'Grave Wisp',role:'Caster',level:30,maxHp:1000});assert.ok(armoredProfile.armor>1000&&armoredProfile.magic<300,'Ironbacks strongly favor Armor over Magic Armor');assert.ok(casterProfile.magic>1000&&casterProfile.armor<100,'Grave Wisps strongly favor Magic Armor over Armor');
assert.ok(api.heroSheetStats(state.run.heroes[1]).physicalDodge>0,'Dexterity grants physical dodge');
assert.ok(api.heroSheetStats(state.run.heroes[0]).magicalDodge>0,'Intellect grants magical dodge');
{const base={id:900001,name:'Test Signet',slot:'Accessory',sourceSlot:'Ring',rarity:'Common',tier:1,stat:'str',value:5,power:20,runes:[]},duplicate={...base,id:900002};state.run.inventory.push(base,duplicate);assert.match(api.itemUpgradeButton(base),/Upgrade to Uncommon/,'an identical same-rarity item enables upgrading');api.mergeInventoryItems(base.id,duplicate.id);assert.equal(base.rarity,'Uncommon','merging promotes the retained item by one rarity');assert.ok(base.value>5,'rarity promotion improves the item rather than changing only its label');assert.equal(state.run.inventory.some(item=>item.id===duplicate.id),false,'the duplicate is consumed by merging');state.run.inventory=state.run.inventory.filter(item=>item.id!==base.id)}
state.run.traderPaidRerolls=0;assert.equal(api.traderRerollCost(),25,'the first paid Trader reroll costs 25 gold in Region 1');state.run.region=1;assert.equal(api.traderRerollCost(),56,'Trader rerolls rise with the regional battle-gold curve');state.run.region=0;state.run.traderPaidRerolls=3;assert.equal(api.traderRerollCost(),200,'paid Trader rerolls double in cost each time');delete state.run.traderPaidRerolls;
const starterMage=api.makeHero(1,'Mage');assert.equal(api.heroWeaponDamageType(starterMage),'magical','the Mage starter weapon deals magical damage');
assert.equal(api.abilities.Warrior.length,2,'every class exposes two abilities');
assert.equal(Object.values(api.abilities).every(list=>list.length===2),true,'all class ability lists contain two choices');
assert.equal(api.abilities.Rogue[1].name,'Interrupting Strike','Rogue trades Poisoned Blade for a dedicated interrupt');assert.equal(api.abilities.Rogue[1].cost,12,'the Rogue interrupt costs less Mana than Poisoned Blade');assert.ok(api.consumables.silenceBomb,'traders can stock an interrupt consumable');
assert.equal(Object.values(api.abilities).flat().every(ability=>!('cooldown' in ability)),true,'turn abilities are limited by Mana rather than cooldowns');
for(const className of Object.keys(api.abilities)){const nodes=api.classSkillNodes(className);assert.ok(nodes.length>=220,`${className} has a huge universal, weapon, specialization, and class-specific skill network`);assert.ok(nodes.filter(node=>node.basic).length>=170,`${className} can travel through dense generic trunks, stat clusters, weapons, and direct ring links`);assert.equal(nodes.every(node=>node.maxRank===1),true,`${className} skill nodes each cost exactly one point`);assert.ok(nodes.filter(node=>node.major).length>=35,`${className} has weapon masteries, class talents, rings, and major keystones`);assert.ok(nodes.filter(node=>node.keystone).length>=20,`${className} exposes many transformative bargain keystones`);assert.equal(new Set(nodes.filter(node=>node.weaponCluster).map(node=>node.weaponCluster)).size,7,'all seven weapon families have dedicated clusters');assert.equal(nodes.some(node=>node.id.startsWith('bridge-')||node.id.startsWith('junction-')),false,'cross-attribute travel connects existing nodes instead of inserting artificial bridge nodes');const manaShield=nodes.find(node=>node.id==='keystone-mana-shield'),aether=nodes.find(node=>node.id==='keystone-aether-conversion');assert.equal(manaShield.requires,'mana-bastion','Mana Shield requires its complete dedicated route');assert.equal(aether.requires,'aether-unraveling','Aether Conversion requires its separate dedicated route');const classNodes=nodes.filter(node=>node.classSpecific),classAnchors=new Set(classNodes.map(node=>node.requires));assert.equal(classAnchors.size,12,`${className} class talents use twelve separate deep prerequisites`);assert.equal(classNodes.some(node=>node.requires.startsWith(className.toLowerCase()+'-')),false,`${className} talents never cheaply chain into one another`)}
{const nodes=api.classSkillNodes('Paladin'),byId=Object.fromEntries(nodes.map(node=>[node.id,node])),nodeLinks=node=>(node.requiresAny||[node.requires]).filter(Boolean),edges=nodes.flatMap(node=>nodeLinks(node).map(parent=>[byId[parent],node]).filter(([parent])=>parent));for(const path of ['str','dex','int'])assert.ok(nodeLinks(byId[`${path}-ring-3`]).includes(`${path}-ring-0`),`${path.toUpperCase()} ring retains its original connecting edge`);for(const [first,second] of []){const links=edges.filter(([a,b])=>new RegExp(`^${first}-ring-`).test(a.id)&&new RegExp(`^${second}-ring-`).test(b.id)||new RegExp(`^${second}-ring-`).test(a.id)&&new RegExp(`^${first}-ring-`).test(b.id));assert.equal(links.length,1,`${first.toUpperCase()} and ${second.toUpperCase()} rings have one direct nearby connection`);const chosen=Math.hypot(links[0][0].x-links[0][1].x,links[0][0].y-links[0][1].y),firstNodes=nodes.filter(node=>new RegExp(`^${first}-ring-[0-5]$`).test(node.id)),secondNodes=nodes.filter(node=>new RegExp(`^${second}-ring-[0-5]$`).test(node.id)),minimum=Math.min(...firstNodes.flatMap(a=>secondNodes.map(b=>Math.hypot(a.x-b.x,a.y-b.y))));assert.equal(chosen,minimum,`${first.toUpperCase()}-${second.toUpperCase()} connection uses the closest ring nodes`)}assert.equal(nodes.some(node=>/travel node/i.test(`${node.name} ${node.desc}`)||!Object.keys(node.effect||{}).length),false,'every visible node grants a real modifier and none are labelled as travel nodes');assert.equal(nodes.filter(node=>node.keystone&&!(node.requires||node.requiresAny?.length)&&!edges.some(([parent])=>parent.id===node.id)).length,0,'no keystone hangs disconnected in empty space')}
{const nodes=api.classSkillNodes('Mage'),byId=Object.fromEntries(nodes.map(node=>[node.id,node]));assert.equal(byId['keystone-spellblade'].requires,'lead-keystone-spellblade','Spellblade has a normal modifier before it');assert.equal(byId['lead-keystone-spellblade'].requires,'dex-ring-0','Spellblade belongs is anchored in the weapon-oriented DEX region instead of INT');assert.equal(byId['keystone-relentless-control'].requires,'lead-keystone-relentless-control','Relentless Control is separated from the preceding major node');assert.equal(byId['lead-keystone-relentless-control'].requires,'int-ring-6','Relentless Control uses a generic attribute route, never a weapon cluster');assert.equal(byId['keystone-glass-cannon'].requires,'lead-keystone-glass-cannon','Glass Cannon is separated from the preceding major node');assert.equal(byId['lead-keystone-glass-cannon'].requires,'cluster-ward-4','Glass Cannon belongs to the INT-side ward area')}
{const nodes=api.classSkillNodes('Mage');assert.equal(nodes.filter(node=>node.keystone).some(node=>String(node.requires||'').startsWith('weapon-')),false,'gameplay-changing nodes are not locked directly behind weapon clusters')}
{const nodes=api.classSkillNodes('Paladin'),byId=Object.fromEntries(nodes.map(node=>[node.id,node]));assert.equal(byId['paladin-0-0'].effect.defPct,.06,'Consecrated Plate grants 6% Armor');assert.equal(byId['paladin-0-0'].effect.mdefPct,.06,'Consecrated Plate grants 6% Magic Armor');for(const id of ['fire','ice','poison','lightning','thorns']){const final=byId[`cluster-${id}-4`];assert.ok(final&&final.requiresAny?.length===2,`${id} has a two-route cluster whose major node accepts either side`);if(id!=='thorns')assert.equal(byId[`cluster-${id}-0`].requires,'weapon-arcane-6',`${id} fans out directly from Archmage Focus`)}assert.equal(byId['initiative-advantage'].effect.initiativeAdvantage,.01,'DEX includes the Initiative-gap damage node')}
{const thorns=Object.fromEntries(api.classSkillNodes('Warrior').filter(node=>node.id.startsWith('cluster-thorns-')).map(node=>[node.id,node]));assert.equal(thorns['cluster-thorns-0'].effect.thornsMore,.05,'the STR Thorns route includes 5% multiplicative Thorns');assert.equal(thorns['cluster-thorns-1'].effect.blockMore,.05,'the STR Thorns route includes 5% multiplicative Block');assert.equal(thorns['cluster-thorns-4'].effect.guardThornsMore,.5,'the defensive major node empowers Thorns while Defending')}
for(const className of Object.keys(api.abilities)){const nodes=api.classSkillNodes(className),primary={Warrior:'str',Paladin:'str',Rogue:'dex',Ranger:'dex',Mage:'int',Priest:'int'}[className],key={str:'strPct',dex:'dexPct',int:'intPct'}[primary];assert.ok(nodes.filter(node=>node.remoteClassTalent).every(node=>(node.effect[key]||0)>=.08),`${className} remote class talents include a substantial primary-attribute premium`)}
const skilledMage=api.makeHero(10,'Mage');assert.equal(api.availableSkillPoints(skilledMage),9,'a level-ten character has earned nine skill points');skilledMage.skillRanks={'mage-0-0':3};assert.equal(api.availableSkillPoints(skilledMage),8,'legacy multi-rank purchases migrate to one point and refund excess ranks');assert.equal(api.skillBonus(skilledMage,'intPct'),.12,'a remote migrated class node includes its off-attribute premium');
if(process.env.PRINT_SKILL_CROSSINGS){const nodes=api.classSkillNodes('Paladin'),byId=Object.fromEntries(nodes.map(node=>[node.id,node])),edges=nodes.flatMap(node=>(node.requiresAny?.length?node.requiresAny:node.requires?[node.requires]:[]).map(id=>byId[id]&&[byId[id],node]).filter(Boolean)),orient=(a,b,c)=>(b.x-a.x)*(c.y-a.y)-(b.y-a.y)*(c.x-a.x),cross=(a,b,c,d)=>orient(a,b,c)*orient(a,b,d)<0&&orient(c,d,a)*orient(c,d,b)<0,hits=[];for(let i=0;i<edges.length;i++)for(let j=i+1;j<edges.length;j++){const [a,b]=edges[i],[c,d]=edges[j];if(new Set([a.id,b.id,c.id,d.id]).size<4)continue;if(cross(a,b,c,d))hits.push(`${a.id}->${b.id} x ${c.id}->${d.id}`)}console.log(hits.length,hits.slice(0,30))}
const skillHero=state.run.heroes[0],rootSkill=api.classSkillNodes(skillHero.class).find(node=>!node.requires&&!node.requiresAny);skillHero.level=3;api.queueSkillNode(skillHero.id,rootSkill.id);assert.equal(skillHero.skillRanks?.[rootSkill.id]||0,0,'selecting a skill node does not spend its point immediately');assert.equal(JSON.stringify(api.pending()[skillHero.id]),JSON.stringify([rootSkill.id]),'selected skill nodes remain pending until confirmation');api.confirmSkillPoints(skillHero.id);assert.equal(skillHero.skillRanks[rootSkill.id],1,'confirming applies all pending skill points');state.run.gold=100;api.respecSkillTree(skillHero.id);assert.equal(api.availableSkillPoints(skillHero),2,'respec refunds every allocated skill point');assert.equal(state.run.gold,0,'the first respec costs 100 run gold');assert.equal(skillHero.skillRespecs,1,'respec count persists so the next price doubles');
const clusterHero=api.makeHero(20,'Warrior'),clusterNodes=api.classSkillNodes('Warrior'),clusterFinal=clusterNodes.find(node=>node.id==='str-ring-6');clusterHero.skillRanks={'str-ring-2':1};state.run.heroes.push(clusterHero);api.queueSkillNode(clusterHero.id,clusterFinal.id);assert.equal(JSON.stringify(api.pending()[clusterHero.id]),JSON.stringify([clusterFinal.id]),'a large cluster node unlocks after completing either one of its two branches');state.run.heroes.pop();
const armorHero=api.makeHero(20,'Paladin'),armorNodes=api.classSkillNodes('Paladin'),adamantBastion=armorNodes.find(node=>node.id==='cluster-armor-4'),armorApproach=adamantBastion.requiresAny[0];armorHero.skillRanks={[armorApproach]:1};state.run.heroes.push(armorHero);assert.equal(api.skillNodeUnlocked(armorHero,adamantBastion,armorNodes),true,'Adamant Bastion unlocks from either completed side');api.queueSkillNode(armorHero.id,adamantBastion.id);assert.equal(JSON.stringify(api.pending()[armorHero.id]),JSON.stringify([adamantBastion.id]),'Adamant Bastion can be queued from one side only');state.run.heroes.pop();
const reverseHero=api.makeHero(20,'Mage'),reverseNodes=api.classSkillNodes('Mage'),reverseChild=reverseNodes.find(node=>node.requires&&reverseNodes.some(parent=>parent.id===node.requires&&parent.requires)),reverseParent=reverseNodes.find(node=>node.id===reverseChild.requires);reverseHero.skillRanks={[reverseChild.id]:1};state.run.heroes.push(reverseHero);api.queueSkillNode(reverseHero.id,reverseParent.id);assert.equal(JSON.stringify(api.pending()[reverseHero.id]),JSON.stringify([reverseParent.id]),'every visible skill-tree connection can be traversed in either direction');state.run.heroes.pop();
assert.doesNotMatch(api.abilityPreviewDescription(state.run.heroes[0],api.abilities.Warrior[0]),/% (?:of )?Attack/,'ability cards replace Attack percentages with current numerical damage');
state.run.heroes[0].gear.Weapon={slot:'Weapon',damageType:'fire'};assert.equal(api.heroWeaponDamageType(state.run.heroes[0]),'magical','a magical Warrior weapon makes weapon-driven abilities magical');const magicTarget=state.run.battle.enemies[0];magicTarget.hp=magicTarget.maxHp;magicTarget.armor=magicTarget.maxArmor=9999;magicTarget.magicArmor=magicTarget.maxMagicArmor=25;const magicHit=api.turnDamage(state.run.heroes[0],magicTarget,.1,api.heroWeaponDamageType(state.run.heroes[0]));assert.ok(magicHit.magicArmorDamage>0&&magicHit.armorDamage===0,'an elemental weapon hit damages Magic Armor instead of physical Armor');state.run.heroes[0].gear.Weapon=null;
assert.equal(Object.values(api.augments).every(list=>list.length===6),true,'each class has three shrine upgrades for each ability');
const subclassData=api.subclasses(),subclasses=Object.values(subclassData).flat();
assert.equal(subclasses.length,19,'all nineteen subclasses are loaded');
assert.equal(subclasses.every(sub=>!/(attack speed|\d+s\b|cooldown)/i.test(`${sub.passive} ${sub.active}`)),true,'every subclass uses turn-based wording');
for(const sub of subclasses){const hero=api.makeHero(10,Object.keys(subclassData).find(cls=>subclassData[cls].some(candidate=>candidate.id===sub.id)));hero.subclass=sub.id;state.run.heroes.push(hero);const ability=api.subclassAbility(hero);assert.ok(ability?.name&&ability.cost>0&&ability.desc&&['enemy','ally','deadAlly','allEnemies'].includes(ability.target),`${sub.name} has a complete turn-based ability`);battle.enemies.forEach(enemy=>{enemy.maxHp=1000000;enemy.hp=1000000;enemy.statuses={};enemy.skipTurns=0});assert.doesNotThrow(()=>api.executeSubclassAbility(hero,ability,ability.target==='ally'?hero:battle.enemies[0],[hero],battle.enemies),`${sub.name}'s ability executes`);state.run.heroes.pop()}
const warrior=state.run.heroes[0],baseInitiative=api.heroInitiative(warrior),baseAttack=api.effectiveAtk(warrior);warrior.subclass='berserker';assert.ok(api.heroInitiative(warrior)>baseInitiative&&api.effectiveAtk(warrior)>baseAttack,'Berserker Initiative and damage passives apply');
warrior.subclass='guardian';assert.ok(api.heroSheetStats(warrior).block>=2,'Guardian Block passive applies');warrior.subclass=null;
const ranger=api.makeHero(10,'Ranger'),baseHp=api.naturalMaxHp(ranger);state.run.heroes.push(ranger);ranger.subclass='beastmaster';assert.ok(api.naturalMaxHp(ranger)>baseHp,'Beastmaster maximum HP passive applies');state.run.heroes.pop();
const priest=api.makeHero(10,'Priest');priest.subclass='battlepriest';assert.equal(api.canEquip(priest,{slot:'Armor',armorClass:'Medium'}),true,'Battle Priest Medium armor proficiency applies');
assert.equal(api.canEquip(priest,{slot:'Armor',armorClass:'Heavy'}),true,'every class can equip every armor class');assert.equal(api.canEquip(priest,{slot:'Weapon',weaponTemplate:'Greatsword'}),true,'every class can equip every weapon family');assert.equal(api.canEquip(priest,{slot:'Accessory'}),true,'every class can equip every accessory');
assert.equal(api.weaponStatusProfile({slot:'Weapon',weaponTemplate:'Warhammer',damageType:'physical'}).name,'Armor Broken','maces and hammers can break Armor');
assert.equal(api.weaponStatusProfile({slot:'Weapon',weaponTemplate:'Crystal Wand',damageType:'ice'}).name,'Frostbite','elemental caster weapons apply their matching status');
assert.equal(api.weaponStatusProfile({slot:'Weapon',weaponTemplate:'Oak Staff',damageType:'arcane'}).name,'Arcane Fracture','a magical staff never inherits the physical Armor Break effect');
{const mage=api.makeHero(10,'Mage');mage.skillRanks={'mage-3-2':1};mage.mana=0;state.run.heroes.push(mage);const wardedTarget=state.run.battle.enemies[0];wardedTarget.hp=wardedTarget.maxHp;wardedTarget.magicArmor=wardedTarget.maxMagicArmor=1;api.turnDamage(mage,wardedTarget,1,'magical');assert.equal(mage.mana,Math.round(mage.maxMana*.1),'Arcane Reversal restores 10% maximum Mana when its owner breaks enemy Magic Armor');state.run.heroes.pop()}
assert.equal(api.heroWeaponFamily({gear:{Weapon:{name:'Broodmother Kris',weaponTemplate:'Kris'}}}),'Dagger','named special weapons inherit the family of their base weapon template');
const evasiveEnemy=api.enemyUnit('Dune Reaver','dune-reaver.png',5),piercingEnemy=api.enemyUnit('Ironback','ironback.png',5);assert.ok(evasiveEnemy.dodge>=.18,'Skirmisher enemies have meaningful dodge for Accuracy to counter');assert.ok(piercingEnemy.pierce>=.2,'Bruiser enemies pierce a portion of protection');
{const inspectedEnemy=battle.enemies[0];inspectedEnemy.dodge=.18;assert.match(api.protectionStatSheet(inspectedEnemy,true),/Dodge[\s\S]*18%/,'enemy inspection visibly reports Dodge chance');inspectedEnemy.dodge=0}
const casterIntent=api.enemyUnit('Cinder Imp','cinder-imp.png',5);casterIntent.actionsTaken=2;casterIntent.intent=null;assert.equal(api.enemyIntent(casterIntent).kind,'aoe','caster special attacks are telegraphed in their intent');casterIntent.intent=null;api.applyEnemyControl(casterIntent,1,'Stunned');casterIntent.skipTurns=0;casterIntent.intent=null;assert.equal(api.enemyIntent(casterIntent).label,'Recovering Attack','stunning an enemy cancels its queued special and resets it to a normal attack');
casterIntent.forceBasicActions=0;casterIntent.intent=null;assert.equal(api.enemyIntent(casterIntent).kind,'aoe');assert.equal(api.interruptEnemy(casterIntent),true,'interrupt cancels a telegraphed special');assert.equal(casterIntent.skipTurns||0,0,'interrupt does not stun or remove an enemy turn');assert.equal(api.enemyIntent(casterIntent).label,'Recovering Attack','an interrupted special becomes a normal attack');

api.chooseTurnAction('basic');
assert.equal(battle.pendingAction,'basic','targeted actions pause for target selection');
const target=battle.enemies[0],before=target.hp;target.dodge=1;assert.equal(api.turnDamage(state.run.heroes[0],target,.1).missed,true,'enemy Dodge produces a miss');assert.match(api.unitCard(target,true),/DODGED/,'a dodged hero attack displays DODGED instead of a damage number');target.dodge=0;
target.stunsTaken=0;
assert.equal(api.stunResistanceChance(target),0,'ordinary enemies have no resistance before their first successful stun');
target.stunsTaken=1;assert.equal(api.stunResistanceChance(target),.2,'each previous stun adds 20% resistance');target.stunsTaken=0;
assert.equal(api.stunResistanceChance({boss:true}),.25,'bosses begin with 25% stun resistance');
assert.equal(api.stunResistanceChance({boss:true,stunsTaken:4}),.9,'stacking stun resistance is capped below immunity');
api.ensureProtection(target);target.maxArmor=target.armor=20;const layeredHp=target.hp,layered=api.applyLayeredDamage(target,15,'physical');assert.equal(layered.hpDamage,0,'physical damage is absorbed by Armor before HP');assert.equal(target.armor,5,'Armor loses damage point for point');assert.equal(target.hp,layeredHp,'Armor prevents HP loss');target.lastDamageHit=null;api.turnDamage(state.run.heroes[0],target,.1);assert.equal(target.lastDamageHit.before,target.lastDamageHit.after,'protection-only damage does not create a false missing-HP segment');target.armor=20;const broken=api.applyLayeredDamage(target,15,'physical',0,2);assert.equal(broken.armorDamage,20,'Armor Broken doubles damage to the Armor layer');assert.equal(broken.hpDamage,5,'overflow retains normal damage against HP');target.armor=20;const pierced=api.applyLayeredDamage(target,10,'physical',.5);assert.equal(pierced.hpDamage,5,'Pierce bypasses Armor and damages HP');target.hp=before;target.armor=target.maxArmor;
assert.match(api.unitCard(target,true),/targetable[\s\S]*chooseTurnTarget/,'the enemy battlefield card becomes the target control');
assert.doesNotMatch(api.turnActionPanel(),/targetAction/,'the action panel does not duplicate enemy target buttons');
api.chooseTurnTarget(target.id);
assert.ok(target.hp<before,'the selected target takes damage');
assert.ok(target.lastDamageHit?.amount>0,'a hit records its visible damage amount and HP-bar loss');
assert.match(api.unitCard(target,true),/damageNumber[\s\S]*recentDamage/,'damaged combat cards render a floating number and trailing HP segment');
const wounded=state.run.heroes[0];wounded.hp-=20;api.applyHealing(state.run.heroes[1],wounded,12);
assert.match(api.unitCard(wounded),/healingNumber[\s\S]*recentHealing/,'healing renders a green number and restored-HP highlight');
assert.ok(target.role&&Number.isFinite(target.def)&&Number.isFinite(target.mdef),'enemies receive a tactical role and distinct defenses');
assert.match(api.unitCard(target,true),new RegExp(target.role),'enemy roles are visible on battlefield cards');
target.skipTurns=1;target.controlStatus='Frozen';
assert.match(api.combatStatusBadges(target,true),/Frozen[\s\S]*<span>1<\/span>/,'Frost Nova control is shown with an uncluttered round count');
warrior.subclassPowerRounds=4;battle.lifestealRounds=4;const partyStatuses=api.combatStatusBadges(warrior);assert.match(partyStatuses,/Battle Shout[\s\S]*<span>3<\/span>/,'Battle Shout appears as a party status');assert.match(partyStatuses,/Vampiric[\s\S]*<span>4<\/span>/,'temporary party lifesteal appears as a status');warrior.subclassPowerRounds=0;battle.lifestealRounds=0;
const rangerTurn=api.makeHero(1,'Ranger');state.run.heroes.push(rangerTurn);battle.turnOrder=[rangerTurn.id,target.id,warrior.id];battle.turnIndex=0;target.initiative=10;target.initiativePenalty=-5;api.resortRemainingTurnOrder();assert.equal(battle.turnOrder[1],warrior.id,'an Initiative penalty immediately reorders units that have not acted');state.run.heroes.pop();target.initiativePenalty=0;
const intent=api.enemyIntent(target);
assert.ok(intent.label&&intent.targetName&&intent.damageType,'enemy intent previews expose action, target, and damage type');

state.run.heroes.forEach(hero=>hero.mana=0);
battle.round=1;
api.buildTurnOrder();
assert.equal(battle.round,2,'finishing an order begins a new round');
assert.equal(state.run.heroes[0].mana,state.run.heroes[0].manaRegen,'Mana regenerates once at round start');
assert.equal(api.abilities.Warrior[0].cost,20,'ability Mana costs remain independently balanced');
const manaBefore=state.run.heroes[0].maxMana;api.activateRelic('sealedReservoir');
assert.equal(state.run.heroes[0].maxMana,Math.round(manaBefore*1.6),'Sealed Reservoir increases maximum Mana');
state.run.heroes[0].mana=0;api.buildTurnOrder();
assert.equal(state.run.heroes[0].mana,0,'Sealed Reservoir prevents round-based Mana regeneration');
state.run.heroes[0].skillRanks={'keystone-vital-leech':1};state.run.heroes[0].hp-=20;
assert.equal(api.applyHealing(state.run.heroes[1],state.run.heroes[0],10),0,'Vital Leech prevents non-Lifesteal healing');assert.equal(api.applyHealing(state.run.heroes[0],state.run.heroes[0],10,'lifesteal'),15,'Vital Leech makes Lifesteal fifty percent more effective');
api.activateRelic('adamantSoul');const protectedHero=state.run.heroes[1];delete protectedHero.maxArmor;api.ensureProtection(protectedHero);assert.ok(protectedHero.maxArmor>=api.heroSheetStats(protectedHero).def,'Adamant Soul scales earned protection without creating innate starting Armor');
{const nodes=api.classSkillNodes('Mage'),byId=Object.fromEntries(nodes.map(node=>[node.id,node])),edges=nodes.flatMap(node=>(node.requiresAny||[node.requires]).filter(Boolean).map(parent=>[byId[parent],node]).filter(([parent])=>parent));for(const [first,second] of [['str','dex'],['dex','int'],['int','str']])assert.equal(edges.some(([a,b])=>new RegExp(`^${first}-ring-`).test(a.id)&&new RegExp(`^${second}-ring-`).test(b.id)||new RegExp(`^${second}-ring-`).test(a.id)&&new RegExp(`^${first}-ring-`).test(b.id)),false,'inner attribute rings are not directly wired together');const radius=node=>node.keystone?82:node.major?68:48;for(let i=0;i<nodes.length;i++)for(let j=i+1;j<nodes.length;j++)assert.ok(Math.hypot(nodes[i].x-nodes[j].x,nodes[i].y-nodes[j].y)>=radius(nodes[i])+radius(nodes[j])+1,`${nodes[i].id} and ${nodes[j].id} do not overlap`)}
console.log('Guildmaster: Dungeons turn combat tests passed.');
