(() => {
'use strict';
const $=s=>document.querySelector(s),canvas=$('#game'),ctx=canvas.getContext('2d'),KEY='bramblebound-v3';
const classes=[
 {name:'Swordsman',hp:110,at:12,range:20,cool:.7,color:'#eeeeee',symbol:'╱',kind:'melee'},
 {name:'Boxer',hp:130,at:7,range:14,cool:.32,color:'#ed614e',symbol:'●',kind:'melee'},
 {name:'Archer',hp:80,at:11,range:125,cool:1,color:'#81c768',symbol:')',kind:'arrow'},
 {name:'Mage',hp:65,at:19,range:105,cool:1.5,color:'#cf8deb',symbol:'✦',kind:'magic'},
 {name:'Priest',hp:85,at:6,range:95,cool:1.3,color:'#7bbce8',symbol:'†',kind:'heal'},
 {name:'Spearman',hp:100,at:14,range:40,cool:1,color:'#e8bc60',symbol:'↗',kind:'melee'},
 {name:'Gunner',hp:75,at:6,range:155,cool:.4,color:'#aaaaaa',symbol:'⌐',kind:'bullet'},
 {name:'Whipper',hp:95,at:10,range:65,cool:1,color:'#75d0c3',symbol:'~',kind:'whip'}
];
const {items:ITEMS,effects:EFFECTS,descriptions:STAT_HELP}=BrambleGear;
const areas=['Grassland','Woodland','Cavern'];
let heroes=[],enemies=[],shots=[],numbers=[],loot=[],inventory=Array(15).fill(null),area=0,gold=0,selected=0,state='setup',paused=false,speed=1,drag=null,time=0,last=0,uid=0,uiTime=0,fields=[],flashes=[],gearDrag=null,pickedSlot=null,suppressGearClick=false;
const floor=x=>{const a=area%3;return a===0?(x<112?226:x<365?219:226):a===1?(x<180?226:x<310?207:226):(x<135?226:x<245?215:x<365?204:226)};
function needed(level){return 25+level*20}
function stats(h){
 const c=classes[h.classId],w=ITEMS[h.weapon],a=h.attributes;const str=4+a.str,dex=4+a.dex,int=a.int;
 h.str=str;h.dex=dex;h.int=int;h.maxHp=c.hp+(h.level-1)*6+a.str*[4,5,3,2,3,4,3,3][h.classId]+a.dex*[4,3,3,2,3,3,2,3][h.classId]+int*2;
 let min=w?w.min:1,max=w?w.max:2;h.range=w?w.range:12;let agi=w?w.agi:[25,35];let factor=1;h.crit=0;h.extra=0;h.abilityPower=1;h.healing=14+int;
 switch(h.classId){
 case 0:max+=str;min=Math.min(max,min+dex);break;
 case 1:min+=str;max+=str;factor=1/(1+dex*.02);break;
 case 2:h.range+=str*2;min+=dex*.5;max+=dex*.75;break;
 case 3:h.range+=str*2;factor=1/(1+dex*.02);min+=int*.5;max+=int*.75;h.abilityPower+=int*.05;break;
 case 4:h.range+=int*2;break;
 case 5:max+=str*1.5;min+=dex*.5;h.crit=Math.min(.4,dex*.01);break;
 case 6:min*=1+str*.02;max*=1+str*.02;factor=1/(1+dex*.02);h.abilityPower+=int*.03;break;
 case 7:min+=str*.5;max+=str*.5;h.extra=Math.floor(dex/5);break;
 }
 h.atMin=Math.floor(Math.min(min,max));h.atMax=Math.floor(max);h.at=h.atMax;h.agi=agi.map(n=>Math.max(5,Math.round(n*factor)));h.cool=(h.agi[0]+h.agi[1])/60;h.color=c.color;h.kind=w?c.kind:'melee';
}
function hero(classId,i){const h={id:++uid,classId,level:1,xp:0,weapon:classId+'-basic',attributes:{str:0,dex:0,int:0},sp:0,mp:0,gearRevision:0,x:35+i*20,y:226,vy:0,cooldown:i*.15,hold:0,anim:0,face:1};stats(h);h.hp=h.maxHp;return h}
function tell(text){$('#status').textContent=text}
function save(){if(!heroes.length)return;try{localStorage.setItem(KEY,JSON.stringify({version:3,area,gold,inventory,heroes:heroes.map(h=>({classId:h.classId,level:h.level,xp:h.xp,weapon:h.weapon,attributes:h.attributes,sp:h.sp,mp:h.mp}))}))}catch{}}
function load(){try{
 const s=JSON.parse(localStorage.getItem(KEY)||localStorage.getItem('bramblebound-v2'));if(!s||!Array.isArray(s.heroes)||s.heroes.length!==4)return false;
 if(!s.heroes.every(h=>Number.isInteger(h.classId)&&classes[h.classId]&&Number.isInteger(h.level)&&h.level>=1&&h.level<=99))return false;
 area=Math.max(0,Math.min(8,Math.floor(s.area)||0));gold=Math.max(0,Math.floor(s.gold)||0);
 inventory=Array.from({length:15},(_,i)=>{const id=s.inventory?.[i];return ITEMS[id]?id:s.version!==3&&Number.isInteger(id)&&id>0?s.heroes[i%4].classId+'-iron':null});
 heroes=s.heroes.map((v,i)=>{const h=hero(v.classId,i);h.level=v.level;h.xp=Math.max(0,Math.min(needed(h.level)-1,Number(v.xp)||0));
 const valid=ITEMS[v.weapon];h.weapon=s.version===3?(valid&&valid.classId===h.classId?v.weapon:null):h.classId+(v.weapon>0?'-iron':'-basic');
 const a=v.attributes||{};h.attributes={str:Math.max(0,Math.floor(a.str)||0),dex:Math.max(0,Math.floor(a.dex)||0),int:Math.max(0,Math.floor(a.int)||0)};
 let spent=Object.values(h.attributes).reduce((n,v)=>n+v,0);if(spent>h.level-1){h.attributes={str:0,dex:0,int:0};spent=0}h.sp=h.level-1-spent;
 const effect=EFFECTS[ITEMS[h.weapon]?.effect];h.mp=effect?Math.max(0,Math.min(effect.mp-1,Math.floor(v.mp)||0)):0;stats(h);h.hp=h.maxHp;return h});return true;
 }catch{return false}}
function allocate(stat){const h=heroes[selected];if(!h||h.sp<1||!['str','dex','int'].includes(stat))return false;const old=h.maxHp;h.attributes[stat]++;h.sp--;stats(h);if(h.hp>0)h.hp+=h.maxHp-old;save();refresh();return true}
function enemy(type,x){const boss=type==='boss',tier=Math.floor(area/3);return {id:++uid,type,x,y:floor(x),hp:boss?650:30+area*12,maxHp:boss?650:30+area*12,at:boss?19:4+area,range:type==='spitter'||type==='summoner'?105:16,cooldown:.5+(x%7)/10,summon:7,remaining:3,color:boss?'#de6262':type==='summoner'?'#c478ed':type==='spitter'?'#e6b94b':tier===1?'#7ca3ed':'#59df42',seed:x,flash:0}}
function enter(){state='fight';paused=false;drag=null;shots=[];numbers=[];loot=[];enemies=[];fields=[];flashes=[];$('#setup').hidden=true;$('#result').hidden=true;heroes.forEach((h,i)=>{h.x=32+i*20;h.y=floor(h.x);h.vy=0;h.hold=0;h.hp=Math.min(h.maxHp,h.hp>0?h.hp+h.maxHp*.25:h.maxHp*.5)});const count=4+area%3+Math.floor(area/3);for(let i=0;i<count;i++){const type=area===8&&i===count-1?'boss':area>=4&&i===count-1?'summoner':area>0&&i%3===2?'spitter':'slime';enemies.push(enemy(type,240+i*(245/(count-1))))}tell('Drag to position. Defeat the enemies, then walk right.');save();build();}
function start(){heroes=[...document.querySelectorAll('#choices select')].map((el,i)=>hero(+el.value,i));area=0;gold=0;inventory=Array(15).fill(null);selected=0;enter()}
function float(x,y,text,color='#fff'){numbers.push({x,y,text,color,life:1})}
function xp(amount){heroes.forEach(h=>{h.xp+=amount;while(h.xp>=needed(h.level)&&h.level<99){h.xp-=needed(h.level);h.level++;h.sp++;stats(h);h.hp=Math.min(h.maxHp,h.hp+26);float(h.x,h.y-34,'LEVEL UP','#ffff66')}});save()}
function damage(target,n){if(target.hp<=0)return;if(!target.type)n=Math.max(1,n-aura(target).defense);target.hp=Math.max(0,target.hp-n);target.flash=.1;float(target.x,target.y-22,Math.round(n));if(target.type&&target.hp===0){gold+=2+area;xp(target.type==='boss'?140:12+area*3);if(!target.minion&&(Math.random()<.55||!enemies.some(e=>e!==target&&e.hp>0)))loot.push({x:target.x,y:target.y,item:rollDrop()});save()}}
function shoot(h,target,kind,amount,attack=null){shots.push({x:h.x,y:h.y-13,target,kind,amount,attack,life:3})}
function rollDrop(){const classId=heroes[Math.floor(Math.random()*heroes.length)].classId;const pool=Object.values(ITEMS).filter(w=>w.classId===classId&&w.tier>0&&w.tier<=1+Math.floor(area/2));return pool[Math.floor(Math.random()*pool.length)].id}
function pickLoot(){loot=loot.filter(item=>{if(heroes.some(h=>h.hp>0&&Math.abs(h.x-item.x)<17)){const i=inventory.indexOf(null);if(i>=0){inventory[i]=item.item;tell('Found '+ITEMS[item.item].name+'. Drag it to a matching weapon slot.')}else{gold+=5*ITEMS[item.item].tier;tell('Item bag full. Drop converted to gold.')}save();build();return false}return true})}
function slotItem(slot){return slot.type==='bag'?inventory[slot.index]:heroes[slot.index]?.weapon}
function validSlot(slot){return slot&&Number.isInteger(slot.index)&&(slot.type==='bag'?slot.index>=0&&slot.index<15:slot.type==='gear'&&slot.index>=0&&slot.index<4)}
function accepts(slot,id){return !id||slot.type==='bag'||(ITEMS[id].classId===heroes[slot.index].classId&&ITEMS[id].level<=heroes[slot.index].level)}
function moveItem(from,to){if(!validSlot(from)||!validSlot(to)||from.type===to.type&&from.index===to.index)return false;const a=slotItem(from),b=slotItem(to);if(!a)return false;if(!accepts(to,a)||!accepts(from,b)){tell('Cannot equip: weapon class or required level does not match.');return false}
 for(const [slot,id] of [[from,b],[to,a]]){if(slot.type==='bag')inventory[slot.index]=id;else{const h=heroes[slot.index];h.weapon=id;h.mp=0;h.gearRevision++;stats(h)}}
 tell(ITEMS[a].name+' moved. Equipment swaps reset MP.');pickedSlot=null;save();build();return true}
function equip(i){return moveItem({type:'bag',index:i},{type:'gear',index:selected})}
function roll(min,max){return Math.floor(min+Math.random()*(max-min+1))}
function aura(h){let attack=1,defense=0;for(const p of heroes)if(p.hp>0&&p.classId===4&&Math.abs(p.x-h.x)<=p.range){attack+=p.str*.01;defense+=p.dex*.2}return {attack,defense}}
function basicAmount(h){return Math.max(1,Math.round(roll(h.atMin,h.atMax)*aura(h).attack*(Math.random()<h.crit?2:1)))}
function attackToken(h){return {owner:h,weapon:h.weapon,revision:h.gearRevision,charged:false}}
function basicHit(target,amount,attack){if(target.hp<=0)return;damage(target,amount);if(!attack||attack.charged)return;attack.charged=true;const h=attack.owner,w=ITEMS[attack.weapon],effect=EFFECTS[w?.effect];if(!effect||h.hp<=0||h.weapon!==attack.weapon||h.gearRevision!==attack.revision)return;h.mp+=h.int;if(h.mp>=effect.mp){h.mp=0;for(let i=0;i<=h.extra;i++)activate(h,target,w.effect)}save()}
function activate(h,target,kind){const e=EFFECTS[kind],power=h.abilityPower,amount=()=>Math.max(1,Math.round(roll(e.min,e.max)*power));float(h.x,h.y-38,e.name,e.color);flashes.push({x:h.x,y:h.y-18,tx:target.x,ty:target.y-10,color:e.color,life:.35,kind});
 const near=enemies.filter(v=>v.hp>0&&Math.abs(v.x-target.x)<45);
 if(kind==='fire'){fields.push({x:target.x,y:floor(target.x),life:1,elapsed:0,pulses:0,amount:amount(),color:e.color});}
 if(kind==='ice'){for(const v of near){damage(v,amount());v.frozen=.7;v.slow=2.7}}
 if(kind==='poison'){if(target.hp>0){target.poison={time:4,tick:1,amount:amount()};}}
 if(kind==='lightning'){enemies.filter(v=>v.hp>0&&Math.abs(v.x-target.x)<130).sort((a,b)=>Math.abs(a.x-target.x)-Math.abs(b.x-target.x)).slice(0,3).forEach(v=>{damage(v,amount());flashes.push({x:target.x,y:target.y-15,tx:v.x,ty:v.y-12,color:e.color,life:.35,kind})})}
 if(kind==='heal'){heroes.filter(v=>v.hp>0).forEach(v=>{const n=Math.min(v.maxHp-v.hp,amount());v.hp+=n;float(v.x,v.y-25,'+'+n,e.color)})}
 if(kind==='drain'&&target.hp>0){const n=Math.min(target.hp,amount());damage(target,n);h.hp=Math.min(h.maxHp,h.hp+n);float(h.x,h.y-25,'+'+n,e.color)}
 if(kind==='stun'){near.forEach(v=>{damage(v,amount());v.stun=e.time})}}
function tickEffects(dt){flashes.forEach(f=>f.life-=dt);flashes=flashes.filter(f=>f.life>0);for(const f of fields){f.life-=dt;f.elapsed+=dt;while(f.pulses<10&&f.pulses*.1<=f.elapsed){f.pulses++;enemies.filter(e=>e.hp>0&&Math.abs(e.x-f.x)<30&&Math.abs(e.y-f.y)<18).forEach(e=>damage(e,f.amount))}}fields=fields.filter(f=>f.life>0);for(const e of enemies){if(e.hp<=0)continue;e.frozen=Math.max(0,(e.frozen||0)-dt);e.slow=Math.max(0,(e.slow||0)-dt);e.stun=Math.max(0,(e.stun||0)-dt);if(e.poison){e.poison.time-=dt;e.poison.tick-=dt;if(e.poison.tick<=0){e.poison.tick+=1;damage(e,e.poison.amount)}if(e.poison.time<=0)e.poison=null}}}
function select(i){selected=i;build()}
function slotMarkup(type,i,id){const w=ITEMS[id],effect=EFFECTS[w?.effect];return '<button class="slot weapon" data-slot="'+type+'" data-index="'+i+'" aria-label="'+(type==='gear'?'Character '+(i+1)+' weapon: ':'Inventory '+(i+1)+': ')+(w?w.name:'Empty')+'" title="'+(w?w.name+' | AT '+w.min+'–'+w.max+(effect?' | '+effect.name+' MP '+effect.mp:' | Physical'):'Empty slot')+'" style="color:'+(w?w.color:'#444')+'">'+(w?classes[w.classId].symbol:'·')+'<small>'+(w?'L'+w.level:'')+'</small></button>'}
function build(){
 $('#party').innerHTML=heroes.map((h,i)=>'<button class="slot '+(selected===i?'selected':'')+'" data-hero="'+i+'" aria-label="Select character '+(i+1)+', '+classes[h.classId].name+'"><span class="life"><i style="width:'+h.hp/h.maxHp*100+'%"></i></span><canvas width="32" height="36" id="portrait-'+i+'"></canvas><span class="num">'+(i+1)+'</span></button>').join('');
 $('#weapons').innerHTML=heroes.map((h,i)=>slotMarkup('gear',i,h.weapon)).join('');$('#items').innerHTML=inventory.map((id,i)=>slotMarkup('bag',i,id)).join('');
 heroes.forEach((h,i)=>stick($('#portrait-'+i).getContext('2d'),{...h,x:16,y:31,anim:0},false));refresh();inspect(heroes[selected]?.weapon);
}
function inspect(id){const w=ITEMS[id],e=EFFECTS[w?.effect];$('#item-name').textContent=w?w.name:'Unarmed';$('#item-details').textContent=w?classes[w.classId].name+' · LV '+w.level+' · AT '+w.min+'–'+w.max+' · AGI '+w.agi.join('–')+' · RANGE '+w.range+' · '+(e?'MP '+e.mp+' · '+e.name:'Physical / no ability'):'No weapon equipped. Basic unarmed attack only.';$('#item-effect').textContent=e?e.description+' Bonus AT '+e.min+'–'+e.max+'. MP gained only by successful basic hits.':w?'Higher physical AT can be a better choice than a weaker elemental weapon.':'';}
function refresh(){const h=heroes[selected];if(!h)return;$('#class-name').textContent=classes[h.classId].name;$('#lp').textContent=Math.ceil(h.hp)+'/'+h.maxHp;$('#attack').textContent=h.atMin+'–'+h.atMax;$('#agi').textContent=h.agi.join('–');$('#range').textContent=h.range;$('#level').textContent=h.level;$('#sp').textContent=h.sp;for(const [i,name] of ['str','dex','int'].entries()){$('#'+name).textContent=h[name];const btn=$('[data-stat="'+name+'"]');btn.disabled=h.sp<1;btn.title=STAT_HELP[h.classId][i];btn.setAttribute('aria-label','Add '+name.toUpperCase()+': '+STAT_HELP[h.classId][i]);}
 $('#stat-help').textContent='STR: '+STAT_HELP[h.classId][0]+' | DEX: '+STAT_HELP[h.classId][1]+' | INT: '+STAT_HELP[h.classId][2];
 const w=ITEMS[h.weapon],e=EFFECTS[w?.effect];$('#mp').textContent=e?h.mp+'/'+e.mp:'—';$('#mp-fill').style.width=e?h.mp/e.mp*100+'%':'0%';$('#mp-hint').textContent=e?(h.int?Math.ceil((e.mp-h.mp)/h.int)+' hits to '+e.name:'Spend a point in INT to charge '+e.name):w?'Physical weapon':'Unarmed';
 $('#xp').textContent=h.xp+'/'+needed(h.level);$('#xp-fill').style.width=h.xp/needed(h.level)*100+'%';$('#gold').textContent=gold;$('#area').textContent=areas[Math.floor(area/3)]+': '+(area%3+1);$('#pause').textContent=paused?'Resume':'Pause';heroes.forEach((h,i)=>{const bar=$('[data-hero="'+i+'"] .life i');if(bar)bar.style.width=Math.max(0,h.hp/h.maxHp)*100+'%'});}
function update(dt){time+=dt;numbers.forEach(n=>{n.y-=13*dt;n.life-=dt});numbers=numbers.filter(n=>n.life>0);if(state!=='fight'&&state!=='walk')return;tickEffects(dt);
 for(const h of heroes){h.flash=Math.max(0,(h.flash||0)-dt);h.anim=Math.max(0,h.anim-dt);if(h.hp<=0||h===drag)continue;h.cooldown-=dt;h.hold=Math.max(0,h.hold-dt);h.vy+=390*dt;h.y+=h.vy*dt;if(h.y>=floor(h.x)){h.y=floor(h.x);h.vy=0}h.walk=false;if(state==='walk'){h.x+=39*dt;h.walk=true;continue}if(h.kind==='heal'&&h.cooldown<=0){const ally=heroes.filter(a=>a.hp>0&&a.hp<a.maxHp*.85).sort((a,b)=>a.hp/a.maxHp-b.hp/b.maxHp)[0];if(ally){if(Math.abs(ally.x-h.x)<145){shoot(h,ally,'heal',h.healing);h.cooldown=h.cool;h.anim=.2;continue}else if(h.hold<=0){h.x+=Math.sign(ally.x-h.x)*32*dt;h.walk=true;continue}}}
 const target=enemies.filter(e=>e.hp>0).sort((a,b)=>Math.abs(a.x-h.x)-Math.abs(b.x-h.x))[0];if(!target)continue;const d=Math.abs(target.x-h.x);h.face=target.x>=h.x?1:-1;if(d>h.range&&h.hold<=0){h.x+=h.face*33*dt;h.walk=true}if(d<=h.range+3&&Math.abs(h.y-target.y)<45&&h.cooldown<=0){h.cooldown=roll(...h.agi)/30;h.anim=.2;const token=attackToken(h),amount=basicAmount(h);if(h.kind==='melee')basicHit(target,amount,token);else if(h.kind==='whip')enemies.filter(e=>e.hp>0&&Math.abs(e.x-h.x)<h.range).forEach(e=>basicHit(e,amount,token));else shoot(h,target,h.kind==='heal'?'magic':h.kind,amount,token)}}
 const additions=[];for(const e of enemies){if(e.hp<=0||e.frozen>0||e.stun>0)continue;e.flash=Math.max(0,e.flash-dt);e.y=floor(e.x);e.cooldown-=dt;if(e.type==='summoner'){e.summon-=dt;if(e.summon<=0&&e.remaining>0){const m=enemy('slime',Math.max(130,e.x-20));m.minion=true;m.hp=m.maxHp*=.55;additions.push(m);e.remaining--;e.summon=8;float(e.x,e.y-30,'SUMMON','#d795ee')}}const target=heroes.filter(h=>h.hp>0).sort((a,b)=>Math.abs(a.x-e.x)-Math.abs(b.x-e.x))[0];if(!target)continue;const d=Math.abs(target.x-e.x);if(d>e.range)e.x+=Math.sign(target.x-e.x)*(e.type==='boss'?13:17)*(e.slow>0?.6:1)*dt;else if(e.cooldown<=0&&Math.abs(target.y-e.y)<50){e.cooldown=e.type==='boss'?1.2:1.4;if(e.range>20)shoot(e,target,'enemy',e.at);else damage(target,e.at)}}enemies.push(...additions);
 for(const s of shots){s.life-=dt;if(s.target.hp<=0){s.life=0;continue}const dx=s.target.x-s.x,dy=s.target.y-12-s.y,d=Math.hypot(dx,dy),v=s.kind==='bullet'?330:180;if(d<v*dt+3){if(s.kind==='heal'){const n=Math.min(s.target.maxHp-s.target.hp,s.amount);s.target.hp+=n;float(s.target.x,s.target.y-22,`+${n}`,'#66ff66')}else{if(s.attack)basicHit(s.target,s.amount,s.attack);else damage(s.target,s.amount)}s.life=0}else{s.x+=dx/d*v*dt;s.y+=dy/d*v*dt}}shots=shots.filter(s=>s.life>0);enemies=enemies.filter(e=>e.hp>0);pickLoot();
 if(heroes.every(h=>h.hp<=0)){state='lost';$('#result-title').textContent='PARTY DEFEATED';$('#result-text').textContent='EXP, levels and equipment are kept.';$('#retry').hidden=false;$('#result').hidden=false;save();tell('Retry this area with your earned levels.');return}
 if(!enemies.length&&state==='fight'){state='walk';tell('AREA CLEAR — moving to the right exit.');save()}
 if(state==='walk'&&heroes.filter(h=>h.hp>0).every(h=>h.x>525)){if(area<8){area++;enter()}else{state='won';$('#result-title').textContent='ALL AREAS CLEARED';$('#result-text').textContent='Your party defeated the cave guardian.';$('#retry').hidden=true;$('#result').hidden=false;tell('Adventure complete. New party starts another run.');save()}}
 uiTime+=dt;if(uiTime>.1){refresh();uiTime=0}}
function line(c,points,color){c.strokeStyle=color;c.lineWidth=1;c.beginPath();points.forEach(([x,y],i)=>i?c.lineTo(Math.round(x)+.5,Math.round(y)+.5):c.moveTo(Math.round(x)+.5,Math.round(y)+.5));c.stroke()}
function stick(c,h,mark){c.save();c.translate(Math.round(h.x),Math.round(h.y));if(h.hp<=0){c.rotate(-Math.PI/2);c.globalAlpha=.4}const stride=h.walk?Math.sin(time*12)*3:0,col=h.flash?'#fff':h.color,face=h.face||1;line(c,[[-4-stride,0],[-2,-5],[0,-10],[2,-5],[4+stride,0]],col);line(c,[[0,-10],[0,-18]],col);line(c,[[-5,-10],[0,-16],[face*6,-11-(h.anim?3:0)]],col);c.strokeStyle=col;c.strokeRect(-3,-24,6,6);const cl=classes[h.classId];if(!h.weapon){}else if(cl.kind==='melee'){line(c,[[face*5,-11],[face*(h.anim?18:9),h.anim?-15:-25]],'#bbb')}else if(cl.kind==='arrow'){line(c,[[7,-24],[11,-17],[7,-9],[7,-24]],'#bd925c')}else if(cl.kind==='whip'){line(c,[[5,-12],[14,-17],[h.anim?32:19,-11]],'#99ddbb')}else{line(c,[[7,-4],[7,-25]],'#b7a470');c.fillStyle=col;c.fillRect(6,-27,3,3)}if(mark&&h.hp>0){c.fillStyle='#fff';c.fillRect(-1,-32,3,2);c.fillRect(0,-33,1,1)}c.restore()}
function terrain(){ctx.fillStyle='#000';ctx.fillRect(0,0,512,256);const cave=area>=6;for(let x=0;x<512;x++){const y=floor(x);ctx.fillStyle=cave?'#837568':'#c99449';ctx.fillRect(x,y,1,256-y);ctx.fillStyle=cave?'#aaa6a0':'#42ed28';ctx.fillRect(x,y,1,1);ctx.fillStyle=cave?'#b1a092':'#f1c270';for(let py=y+3+(x%3);py<256;py+=4)if(x%3===0)ctx.fillRect(x,py,1,1)}if(cave){ctx.fillStyle='#6c635b';for(let x=0;x<512;x+=8)ctx.fillRect(x,0,8,7+(x*7)%17)}if(state==='walk'){ctx.fillStyle='#be8d46';ctx.fillRect(479,205,31,10);ctx.fillRect(484,215,2,11);ctx.fillStyle='#000';ctx.font='8px monospace';ctx.fillText('NEXT>',480,213)}}
function draw(){ctx.imageSmoothingEnabled=false;terrain();for(const e of enemies){const r=e.type==='boss'?17:e.type==='summoner'?9:7,x=Math.round(e.x),y=Math.round(e.y);ctx.strokeStyle=e.flash?'#fff':e.frozen>0?'#79cfff':e.poison?'#a3ff57':e.color;ctx.beginPath();if(e.type==='summoner'){ctx.moveTo(x-r,y-3);ctx.lineTo(x,y-25);ctx.lineTo(x+r,y-3);ctx.closePath()}else ctx.ellipse(x,y-r,r,r-1,0,Math.PI,Math.PI*3);ctx.stroke();ctx.fillStyle=e.color;ctx.fillRect(x-3,y-r,1,2);ctx.fillRect(x+3,y-r,1,2);if(e.hp<e.maxHp){ctx.fillStyle='#c32929';ctx.fillRect(x-r,y-r*2-5,Math.max(1,Math.round(2*r*e.hp/e.maxHp)),2)}}fields.forEach(f=>{ctx.fillStyle=f.color;for(let i=0;i<10;i++)ctx.fillRect(f.x-25+i*5,f.y-2-(i%3)*2,2,2)});flashes.forEach(f=>line(ctx,[[f.x,f.y],[(f.x+f.tx)/2,f.ty-12],[f.tx,f.ty]],f.color));loot.forEach(l=>{ctx.fillStyle=ITEMS[l.item].color;ctx.fillRect(Math.round(l.x),l.y-5,3,5)});heroes.forEach((h,i)=>stick(ctx,h,i===selected));shots.forEach(s=>{ctx.fillStyle=s.kind==='heal'?'#60ff70':s.kind==='magic'?'#df81ff':s.kind==='enemy'?'#ed9552':'#eee';ctx.fillRect(Math.round(s.x),Math.round(s.y),s.kind==='arrow'?6:2,2)});ctx.font='7px monospace';ctx.textAlign='center';numbers.forEach(n=>{ctx.fillStyle=n.color;ctx.fillText(n.text,Math.round(n.x),Math.round(n.y))});ctx.textAlign='left';if(paused){ctx.fillStyle='#ffffff';ctx.font='12px monospace';ctx.fillText('PAUSED',233,90)}}
function toggle(){if(state==='setup'||state==='lost'||state==='won')return;paused=!paused;refresh()}
function point(e){const r=canvas.getBoundingClientRect();return{x:(e.clientX-r.left)*512/r.width,y:(e.clientY-r.top)*256/r.height}}
canvas.addEventListener('pointerdown',e=>{if(paused||!['fight','walk'].includes(state))return;const p=point(e),h=heroes.filter(h=>h.hp>0).sort((a,b)=>Math.hypot(a.x-p.x,a.y-13-p.y)-Math.hypot(b.x-p.x,b.y-13-p.y))[0];if(h&&Math.hypot(h.x-p.x,h.y-13-p.y)<22){drag=h;select(heroes.indexOf(h));canvas.setPointerCapture(e.pointerId)}});
canvas.addEventListener('pointermove',e=>{if(!drag||paused)return;const p=point(e);drag.x=Math.max(8,Math.min(503,p.x));drag.y=Math.max(45,Math.min(floor(drag.x),p.y+13));drag.vy=0});function release(){if(drag){drag.hold=.8;drag=null}}canvas.addEventListener('pointerup',release);canvas.addEventListener('pointercancel',release);
$('#pause').onclick=toggle;$('#speed').onclick=()=>{speed=speed===1?2:1;$('#speed').textContent=speed+'x'};$('#start').onclick=start;$('#retry').onclick=()=>{heroes.forEach(h=>h.hp=h.maxHp);enter()};$('#new').onclick=()=>{if(heroes.length&&!confirm('Start a new party? This replaces your current run.'))return;state='setup';paused=false;$('#setup').hidden=false;$('#result').hidden=true;tell('Choose any combination of four classes.');refresh()};$('#fullscreen').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await $('#app').requestFullscreen()}catch{tell('Full screen is unavailable in this browser.')}};
$('#party').onclick=e=>{const b=e.target.closest('[data-hero]');if(b)select(+b.dataset.hero)};
$('.stats').onclick=e=>{const b=e.target.closest('[data-stat]');if(b)allocate(b.dataset.stat)};
function slotFrom(el){const b=el?.closest('[data-slot]');return b?{type:b.dataset.slot,index:+b.dataset.index}:null}
const app=$('#app');
app.addEventListener('pointerdown',e=>{const from=slotFrom(e.target);if(!from||!slotItem(from)||e.button!==0)return;gearDrag={from,startX:e.clientX,startY:e.clientY,moved:false,pointerId:e.pointerId};app.setPointerCapture(e.pointerId)});
app.addEventListener('pointermove',e=>{if(!gearDrag)return;const d=gearDrag;if(Math.hypot(e.clientX-d.startX,e.clientY-d.startY)>5)d.moved=true;if(!d.moved)return;e.preventDefault();const w=ITEMS[slotItem(d.from)],ghost=$('#drag-item');ghost.hidden=false;ghost.textContent=classes[w.classId].symbol;ghost.style.color=w.color;ghost.style.left=e.clientX+'px';ghost.style.top=e.clientY+'px';const target=slotFrom(document.elementFromPoint(e.clientX,e.clientY));document.querySelectorAll('[data-slot]').forEach(el=>el.classList.remove('drop-ok','drop-no'));if(target){const el=$('[data-slot="'+target.type+'"][data-index="'+target.index+'"]');el.classList.add(accepts(target,w.id)&&accepts(d.from,slotItem(target))?'drop-ok':'drop-no')}});
function endGear(e,cancel=false){if(!gearDrag)return;const d=gearDrag;gearDrag=null;$('#drag-item').hidden=true;document.querySelectorAll('[data-slot]').forEach(el=>el.classList.remove('drop-ok','drop-no'));if(app.hasPointerCapture?.(d.pointerId))app.releasePointerCapture(d.pointerId);if(d.moved){suppressGearClick=true;if(!cancel){const to=slotFrom(document.elementFromPoint(e.clientX,e.clientY));if(to)moveItem(d.from,to)}setTimeout(()=>suppressGearClick=false,0)}}
app.addEventListener('pointerup',e=>endGear(e));app.addEventListener('pointercancel',e=>endGear(e,true));
app.addEventListener('click',e=>{if(suppressGearClick)return;const slot=slotFrom(e.target);if(!slot)return;if(pickedSlot){const from=pickedSlot;pickedSlot=null;moveItem(from,slot);build()}else if(slotItem(slot)){pickedSlot=slot;inspect(slotItem(slot));tell('Item selected. Click a destination slot, or drag it there.');e.target.closest('[data-slot]').classList.add('item-picked')}});
app.addEventListener('mouseover',e=>{const slot=slotFrom(e.target);if(slot)inspect(slotItem(slot))});app.addEventListener('focusin',e=>{const slot=slotFrom(e.target);if(slot)inspect(slotItem(slot))});
window.addEventListener('keydown',e=>{if(e.key==='Escape'){pickedSlot=null;if(gearDrag)endGear(e,true);build();return}if(e.target.matches('select,button'))return;if(e.code==='Space'){e.preventDefault();toggle()}if(/^[1-4]$/.test(e.key)&&heroes.length)select(+e.key-1)});window.addEventListener('blur',()=>{if(state==='fight'||state==='walk'){paused=true;release();if(gearDrag)endGear({},true);refresh()}});
$('#choices').innerHTML=[0,2,3,4].map((n,i)=>`<label class="choice">${i+1}<canvas width="32" height="40" id="choice-${i}"></canvas><select aria-label="Character ${i+1} class">${classes.map((c,j)=>`<option value="${j}" ${j===n?'selected':''}>${c.name}</option>`).join('')}</select></label>`).join('');
function previews(){document.querySelectorAll('#choices select').forEach((el,i)=>{const c=$(`#choice-${i}`).getContext('2d');c.clearRect(0,0,32,40);stick(c,{...hero(+el.value,i),x:16,y:35},false)})}$('#choices').onchange=previews;previews();if(load())enter();else{heroes=[0,2,3,4].map(hero);build()}
function frame(t){const dt=Math.min(.035,(t-last)/1000);last=t;if(!paused&&!gearDrag)update(dt*speed);draw();requestAnimationFrame(frame)}requestAnimationFrame(frame);
})();



