(() => {
'use strict';
const $=s=>document.querySelector(s),canvas=$('#game'),ctx=canvas.getContext('2d'),KEY='bramblebound-v2';
const classes=[
 {name:'Swordsman',hp:110,at:12,range:20,cool:.7,color:'#eeeeee',symbol:'╱',kind:'melee'},
 {name:'Boxer',hp:130,at:7,range:14,cool:.32,color:'#ed614e',symbol:'●',kind:'melee'},
 {name:'Archer',hp:80,at:11,range:125,cool:1,color:'#81c768',symbol:')',kind:'arrow'},
 {name:'Mage',hp:65,at:19,range:105,cool:1.5,color:'#cf8deb',symbol:'✦',kind:'magic'},
 {name:'Priest',hp:85,at:6,range:95,cool:1.3,color:'#7bbce8',symbol:'†',kind:'heal'},
 {name:'Spearman',hp:100,at:14,range:40,cool:1,color:'#e8bc60',symbol:'↗',kind:'melee'},
 {name:'Gunner',hp:75,at:6,range:155,cool:.4,color:'#aaaaaa',symbol:'⌐',kind:'bullet'},
 {name:'Whipper',hp:95,at:10,range:65,cool:1,color:'#75d0c3',symbol:'~',kind:'whip'}
];
const areas=['Grassland','Woodland','Cavern'];
let heroes=[],enemies=[],shots=[],numbers=[],loot=[],inventory=[],area=0,gold=0,selected=0,state='setup',paused=false,speed=1,drag=null,time=0,last=0,uid=0,uiTime=0;
const floor=x=>{const a=area%3;return a===0?(x<112?226:x<365?219:226):a===1?(x<180?226:x<310?207:226):(x<135?226:x<245?215:x<365?204:226)};
function needed(level){return 25+level*20}
function stats(h){const c=classes[h.classId];h.maxHp=c.hp+(h.level-1)*13;h.at=c.at+(h.level-1)*2+h.weapon*3;h.range=c.range;h.cool=c.cool;h.color=c.color;h.kind=c.kind}
function hero(classId,i){const h={id:++uid,classId,level:1,xp:0,weapon:0,x:35+i*20,y:226,vy:0,cooldown:i*.15,hold:0,anim:0,face:1};stats(h);h.hp=h.maxHp;return h}
function tell(text){$('#status').textContent=text}
function save(){if(!heroes.length)return;try{localStorage.setItem(KEY,JSON.stringify({area,gold,inventory,heroes:heroes.map(h=>({classId:h.classId,level:h.level,xp:h.xp,weapon:h.weapon}))}))}catch{}}
function load(){try{const s=JSON.parse(localStorage.getItem(KEY));if(!s||!Array.isArray(s.heroes)||s.heroes.length!==4)return false;if(!s.heroes.every(h=>Number.isInteger(h.classId)&&classes[h.classId]&&Number.isInteger(h.level)&&h.level>=1&&h.level<=99))return false;area=Math.max(0,Math.min(8,Math.floor(s.area)||0));gold=Math.max(0,Math.floor(s.gold)||0);inventory=Array.isArray(s.inventory)?s.inventory.filter(n=>Number.isInteger(n)&&n>0&&n<30).slice(0,15):[];heroes=s.heroes.map((v,i)=>{const h=hero(v.classId,i);h.level=v.level;h.xp=Math.max(0,Math.min(needed(h.level)-1,Number(v.xp)||0));h.weapon=Math.max(0,Math.min(29,Math.floor(v.weapon)||0));stats(h);h.hp=h.maxHp;return h});return true}catch{return false}}
function enemy(type,x){const boss=type==='boss',tier=Math.floor(area/3);return {id:++uid,type,x,y:floor(x),hp:boss?650:30+area*12,maxHp:boss?650:30+area*12,at:boss?19:4+area,range:type==='spitter'||type==='summoner'?105:16,cooldown:.5+(x%7)/10,summon:7,remaining:3,color:boss?'#de6262':type==='summoner'?'#c478ed':type==='spitter'?'#e6b94b':tier===1?'#7ca3ed':'#59df42',seed:x,flash:0}}
function enter(){state='fight';paused=false;drag=null;shots=[];numbers=[];loot=[];enemies=[];$('#setup').hidden=true;$('#result').hidden=true;heroes.forEach((h,i)=>{h.x=32+i*20;h.y=floor(h.x);h.vy=0;h.hold=0;h.hp=Math.min(h.maxHp,h.hp>0?h.hp+h.maxHp*.25:h.maxHp*.5)});const count=4+area%3+Math.floor(area/3);for(let i=0;i<count;i++){const type=area===8&&i===count-1?'boss':area>=4&&i===count-1?'summoner':area>0&&i%3===2?'spitter':'slime';enemies.push(enemy(type,240+i*(245/(count-1))))}tell('Drag to position. Defeat the enemies, then walk right.');save();build();}
function start(){heroes=[...document.querySelectorAll('#choices select')].map((el,i)=>hero(+el.value,i));area=0;gold=0;inventory=[];selected=0;enter()}
function float(x,y,text,color='#fff'){numbers.push({x,y,text,color,life:1})}
function xp(amount){heroes.forEach(h=>{h.xp+=amount;while(h.xp>=needed(h.level)&&h.level<99){h.xp-=needed(h.level);h.level++;stats(h);h.hp=Math.min(h.maxHp,h.hp+26);float(h.x,h.y-34,'LEVEL UP','#ffff66')}});save()}
function damage(target,n){if(target.hp<=0)return;target.hp=Math.max(0,target.hp-n);target.flash=.1;float(target.x,target.y-22,Math.round(n));if(target.type&&target.hp===0){gold+=2+area;xp(target.type==='boss'?140:12+area*3);if(!target.minion&&Math.random()<.32)loot.push({x:target.x,y:target.y,tier:1+Math.floor(area/3)});save()}}
function shoot(h,target,kind,amount){shots.push({x:h.x,y:h.y-13,target,kind,amount,life:3})}
function pickLoot(){loot=loot.filter(item=>{if(heroes.some(h=>h.hp>0&&Math.abs(h.x-item.x)<17)){if(inventory.length<15){inventory.push(item.tier);tell(`Found weapon +${item.tier}. Select a hero, then click ITEM to equip.`)}else{gold+=item.tier*5;tell('Item bag full. Drop converted to gold.')}save();build();return false}return true})}
function equip(i){const h=heroes[selected];if(!h||inventory[i]==null)return;const old=h.weapon;h.weapon=inventory[i];if(old)inventory[i]=old;else inventory.splice(i,1);stats(h);tell(`${classes[h.classId].name}: weapon +${h.weapon} equipped.`);save();build()}
function select(i){selected=i;build()}
function build(){ $('#party').innerHTML=heroes.map((h,i)=>`<button class="slot ${selected===i?'selected':''}" data-hero="${i}" aria-label="Select character ${i+1}, ${classes[h.classId].name}"><span class="life"><i style="width:${h.hp/h.maxHp*100}%"></i></span><canvas width="32" height="36" id="portrait-${i}"></canvas><span class="num">${i+1}</span></button>`).join('');$('#weapons').innerHTML=heroes.map((h,i)=>`<button class="slot weapon" data-hero="${i}" title="${classes[h.classId].name} weapon +${h.weapon}">${classes[h.classId].symbol}<small>+${h.weapon}</small></button>`).join('');$('#items').innerHTML=Array.from({length:15},(_,i)=>`<button class="slot weapon" data-item="${i}" ${inventory[i]==null?'disabled':''} aria-label="${inventory[i]==null?'Empty slot':`Equip weapon +${inventory[i]}`}" title="${inventory[i]==null?'Empty':`Equip +${inventory[i]} on selected character`}">${inventory[i]!=null?'╱<small>+'+inventory[i]+'</small>':''}</button>`).join('');heroes.forEach((h,i)=>stick($(`#portrait-${i}`).getContext('2d'),{...h,x:16,y:31,anim:0},false));refresh()}
function refresh(){const h=heroes[selected];if(!h)return;$('#class-name').textContent=classes[h.classId].name;$('#lp').textContent=`${Math.ceil(h.hp)}/${h.maxHp}`;$('#attack').textContent=h.at;$('#range').textContent=h.range;$('#level').textContent=h.level;$('#xp').textContent=`${h.xp}/${needed(h.level)}`;$('#xp-fill').style.width=`${h.xp/needed(h.level)*100}%`;$('#gold').textContent=gold;$('#area').textContent=`${areas[Math.floor(area/3)]}: ${area%3+1}`;$('#pause').textContent=paused?'Resume':'Pause';heroes.forEach((h,i)=>{const bar=$(`[data-hero="${i}"] .life i`);if(bar)bar.style.width=`${Math.max(0,h.hp/h.maxHp)*100}%`})}
function update(dt){time+=dt;numbers.forEach(n=>{n.y-=13*dt;n.life-=dt});numbers=numbers.filter(n=>n.life>0);if(state!=='fight'&&state!=='walk')return;
 for(const h of heroes){h.flash=Math.max(0,(h.flash||0)-dt);h.anim=Math.max(0,h.anim-dt);if(h.hp<=0||h===drag)continue;h.cooldown-=dt;h.hold=Math.max(0,h.hold-dt);h.vy+=390*dt;h.y+=h.vy*dt;if(h.y>=floor(h.x)){h.y=floor(h.x);h.vy=0}h.walk=false;if(state==='walk'){h.x+=39*dt;h.walk=true;continue}if(h.kind==='heal'&&h.cooldown<=0){const ally=heroes.filter(a=>a.hp>0&&a.hp<a.maxHp*.85).sort((a,b)=>a.hp/a.maxHp-b.hp/b.maxHp)[0];if(ally){if(Math.abs(ally.x-h.x)<145){shoot(h,ally,'heal',14+h.level*3);h.cooldown=h.cool;h.anim=.2;continue}else if(h.hold<=0){h.x+=Math.sign(ally.x-h.x)*32*dt;h.walk=true;continue}}}
 const target=enemies.filter(e=>e.hp>0).sort((a,b)=>Math.abs(a.x-h.x)-Math.abs(b.x-h.x))[0];if(!target)continue;const d=Math.abs(target.x-h.x);h.face=target.x>=h.x?1:-1;if(d>h.range&&h.hold<=0){h.x+=h.face*33*dt;h.walk=true}if(d<=h.range+3&&Math.abs(h.y-target.y)<45&&h.cooldown<=0){h.cooldown=h.cool;h.anim=.2;if(h.kind==='melee')damage(target,h.at);else if(h.kind==='whip')enemies.filter(e=>e.hp>0&&Math.abs(e.x-h.x)<h.range).forEach(e=>damage(e,h.at));else shoot(h,target,h.kind==='heal'?'magic':h.kind,h.at)}}
 const additions=[];for(const e of enemies){if(e.hp<=0)continue;e.flash=Math.max(0,e.flash-dt);e.y=floor(e.x);e.cooldown-=dt;if(e.type==='summoner'){e.summon-=dt;if(e.summon<=0&&e.remaining>0){const m=enemy('slime',Math.max(130,e.x-20));m.minion=true;m.hp=m.maxHp*=.55;additions.push(m);e.remaining--;e.summon=8;float(e.x,e.y-30,'SUMMON','#d795ee')}}const target=heroes.filter(h=>h.hp>0).sort((a,b)=>Math.abs(a.x-e.x)-Math.abs(b.x-e.x))[0];if(!target)continue;const d=Math.abs(target.x-e.x);if(d>e.range)e.x+=Math.sign(target.x-e.x)*(e.type==='boss'?13:17)*dt;else if(e.cooldown<=0&&Math.abs(target.y-e.y)<50){e.cooldown=e.type==='boss'?1.2:1.4;if(e.range>20)shoot(e,target,'enemy',e.at);else damage(target,e.at)}}enemies.push(...additions);
 for(const s of shots){s.life-=dt;if(s.target.hp<=0){s.life=0;continue}const dx=s.target.x-s.x,dy=s.target.y-12-s.y,d=Math.hypot(dx,dy),v=s.kind==='bullet'?330:180;if(d<v*dt+3){if(s.kind==='heal'){const n=Math.min(s.target.maxHp-s.target.hp,s.amount);s.target.hp+=n;float(s.target.x,s.target.y-22,`+${n}`,'#66ff66')}else{damage(s.target,s.amount);if(s.kind==='magic')enemies.filter(e=>e!==s.target&&e.hp>0&&Math.abs(e.x-s.target.x)<25).forEach(e=>damage(e,Math.ceil(s.amount*.4)))}s.life=0}else{s.x+=dx/d*v*dt;s.y+=dy/d*v*dt}}shots=shots.filter(s=>s.life>0);enemies=enemies.filter(e=>e.hp>0);pickLoot();
 if(heroes.every(h=>h.hp<=0)){state='lost';$('#result-title').textContent='PARTY DEFEATED';$('#result-text').textContent='EXP, levels and equipment are kept.';$('#retry').hidden=false;$('#result').hidden=false;save();tell('Retry this area with your earned levels.');return}
 if(!enemies.length&&state==='fight'){state='walk';tell('AREA CLEAR — moving to the right exit.');save()}
 if(state==='walk'&&heroes.filter(h=>h.hp>0).every(h=>h.x>525)){if(area<8){area++;enter()}else{state='won';$('#result-title').textContent='ALL AREAS CLEARED';$('#result-text').textContent='Your party defeated the cave guardian.';$('#retry').hidden=true;$('#result').hidden=false;tell('Adventure complete. New party starts another run.');save()}}
 uiTime+=dt;if(uiTime>.1){refresh();uiTime=0}}
function line(c,points,color){c.strokeStyle=color;c.lineWidth=1;c.beginPath();points.forEach(([x,y],i)=>i?c.lineTo(Math.round(x)+.5,Math.round(y)+.5):c.moveTo(Math.round(x)+.5,Math.round(y)+.5));c.stroke()}
function stick(c,h,mark){c.save();c.translate(Math.round(h.x),Math.round(h.y));if(h.hp<=0){c.rotate(-Math.PI/2);c.globalAlpha=.4}const stride=h.walk?Math.sin(time*12)*3:0,col=h.flash?'#fff':h.color,face=h.face||1;line(c,[[-4-stride,0],[-2,-5],[0,-10],[2,-5],[4+stride,0]],col);line(c,[[0,-10],[0,-18]],col);line(c,[[-5,-10],[0,-16],[face*6,-11-(h.anim?3:0)]],col);c.strokeStyle=col;c.strokeRect(-3,-24,6,6);const cl=classes[h.classId];if(cl.kind==='melee'){line(c,[[face*5,-11],[face*(h.anim?18:9),h.anim?-15:-25]],'#bbb')}else if(cl.kind==='arrow'){line(c,[[7,-24],[11,-17],[7,-9],[7,-24]],'#bd925c')}else if(cl.kind==='whip'){line(c,[[5,-12],[14,-17],[h.anim?32:19,-11]],'#99ddbb')}else{line(c,[[7,-4],[7,-25]],'#b7a470');c.fillStyle=col;c.fillRect(6,-27,3,3)}if(mark&&h.hp>0){c.fillStyle='#fff';c.fillRect(-1,-32,3,2);c.fillRect(0,-33,1,1)}c.restore()}
function terrain(){ctx.fillStyle='#000';ctx.fillRect(0,0,512,256);const cave=area>=6;for(let x=0;x<512;x++){const y=floor(x);ctx.fillStyle=cave?'#837568':'#c99449';ctx.fillRect(x,y,1,256-y);ctx.fillStyle=cave?'#aaa6a0':'#42ed28';ctx.fillRect(x,y,1,1);ctx.fillStyle=cave?'#b1a092':'#f1c270';for(let py=y+3+(x%3);py<256;py+=4)if(x%3===0)ctx.fillRect(x,py,1,1)}if(cave){ctx.fillStyle='#6c635b';for(let x=0;x<512;x+=8)ctx.fillRect(x,0,8,7+(x*7)%17)}if(state==='walk'){ctx.fillStyle='#be8d46';ctx.fillRect(479,205,31,10);ctx.fillRect(484,215,2,11);ctx.fillStyle='#000';ctx.font='8px monospace';ctx.fillText('NEXT>',480,213)}}
function draw(){ctx.imageSmoothingEnabled=false;terrain();for(const e of enemies){const r=e.type==='boss'?17:e.type==='summoner'?9:7,x=Math.round(e.x),y=Math.round(e.y);ctx.strokeStyle=e.flash?'#fff':e.color;ctx.beginPath();if(e.type==='summoner'){ctx.moveTo(x-r,y-3);ctx.lineTo(x,y-25);ctx.lineTo(x+r,y-3);ctx.closePath()}else ctx.ellipse(x,y-r,r,r-1,0,Math.PI,Math.PI*3);ctx.stroke();ctx.fillStyle=e.color;ctx.fillRect(x-3,y-r,1,2);ctx.fillRect(x+3,y-r,1,2);if(e.hp<e.maxHp){ctx.fillStyle='#c32929';ctx.fillRect(x-r,y-r*2-5,Math.max(1,Math.round(2*r*e.hp/e.maxHp)),2)}}loot.forEach(l=>{ctx.fillStyle='#ffff75';ctx.fillRect(Math.round(l.x),l.y-5,3,5)});heroes.forEach((h,i)=>stick(ctx,h,i===selected));shots.forEach(s=>{ctx.fillStyle=s.kind==='heal'?'#60ff70':s.kind==='magic'?'#df81ff':s.kind==='enemy'?'#ed9552':'#eee';ctx.fillRect(Math.round(s.x),Math.round(s.y),s.kind==='arrow'?6:2,2)});ctx.font='7px monospace';ctx.textAlign='center';numbers.forEach(n=>{ctx.fillStyle=n.color;ctx.fillText(n.text,Math.round(n.x),Math.round(n.y))});ctx.textAlign='left';if(paused){ctx.fillStyle='#ffffff';ctx.font='12px monospace';ctx.fillText('PAUSED',233,90)}}
function toggle(){if(state==='setup'||state==='lost'||state==='won')return;paused=!paused;refresh()}
function point(e){const r=canvas.getBoundingClientRect();return{x:(e.clientX-r.left)*512/r.width,y:(e.clientY-r.top)*256/r.height}}
canvas.addEventListener('pointerdown',e=>{if(paused||!['fight','walk'].includes(state))return;const p=point(e),h=heroes.filter(h=>h.hp>0).sort((a,b)=>Math.hypot(a.x-p.x,a.y-13-p.y)-Math.hypot(b.x-p.x,b.y-13-p.y))[0];if(h&&Math.hypot(h.x-p.x,h.y-13-p.y)<22){drag=h;select(heroes.indexOf(h));canvas.setPointerCapture(e.pointerId)}});
canvas.addEventListener('pointermove',e=>{if(!drag||paused)return;const p=point(e);drag.x=Math.max(8,Math.min(503,p.x));drag.y=Math.max(45,Math.min(floor(drag.x),p.y+13));drag.vy=0});function release(){if(drag){drag.hold=.8;drag=null}}canvas.addEventListener('pointerup',release);canvas.addEventListener('pointercancel',release);
$('#pause').onclick=toggle;$('#speed').onclick=()=>{speed=speed===1?2:1;$('#speed').textContent=speed+'x'};$('#start').onclick=start;$('#retry').onclick=()=>{heroes.forEach(h=>h.hp=h.maxHp);enter()};$('#new').onclick=()=>{if(heroes.length&&!confirm('Start a new party? This replaces your current run.'))return;state='setup';paused=false;$('#setup').hidden=false;$('#result').hidden=true;tell('Choose any combination of four classes.');refresh()};$('#fullscreen').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await $('#app').requestFullscreen()}catch{tell('Full screen is unavailable in this browser.')}};
$('#party').onclick=e=>{const b=e.target.closest('[data-hero]');if(b)select(+b.dataset.hero)};$('#weapons').onclick=$('#party').onclick;$('#items').onclick=e=>{const b=e.target.closest('[data-item]');if(b)equip(+b.dataset.item)};
window.addEventListener('keydown',e=>{if(e.target.matches('select,button'))return;if(e.code==='Space'){e.preventDefault();toggle()}if(/^[1-4]$/.test(e.key)&&heroes.length)select(+e.key-1)});window.addEventListener('blur',()=>{if(state==='fight'||state==='walk'){paused=true;release();refresh()}});
$('#choices').innerHTML=[0,2,3,4].map((n,i)=>`<label class="choice">${i+1}<canvas width="32" height="40" id="choice-${i}"></canvas><select aria-label="Character ${i+1} class">${classes.map((c,j)=>`<option value="${j}" ${j===n?'selected':''}>${c.name}</option>`).join('')}</select></label>`).join('');
function previews(){document.querySelectorAll('#choices select').forEach((el,i)=>{const c=$(`#choice-${i}`).getContext('2d');c.clearRect(0,0,32,40);stick(c,{...hero(+el.value,i),x:16,y:35},false)})}$('#choices').onchange=previews;previews();if(load())enter();else{heroes=[0,2,3,4].map(hero);build()}
function frame(t){const dt=Math.min(.035,(t-last)/1000);last=t;if(!paused)update(dt*speed);draw();requestAnimationFrame(frame)}requestAnimationFrame(frame);
})();

