const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const noop=()=>{},context=new Proxy({},{get:()=>noop,set:()=>true});
function harness(saved={}){
 const events={};const elements=new Map(),choices=[0,2,3,4].map(value=>({value:String(value)}));
 const element=()=>({style:{setProperty:noop},classList:{add:noop,remove:noop},hidden:false,textContent:'',innerHTML:'',addEventListener:noop,setAttribute:noop,getContext:()=>context});
 const document={querySelector(s){if(!elements.has(s))elements.set(s,element());return elements.get(s)},querySelectorAll(s){return s==='#choices select'?choices:[]}};
 let seed=13;const math=Object.create(Math);math.random=()=>((seed=(seed*1664525+1013904223)>>>0)/4294967296);
 const storage={...saved};const sandbox={document,Math:math,window:{addEventListener:(name,fn)=>events[name]=fn},localStorage:{getItem:k=>storage[k]||null,setItem:(k,v)=>storage[k]=v},Path2D:class {constructor(path){this.path=path}},requestAnimationFrame:noop,setTimeout:noop,console};
 vm.runInNewContext(fs.readFileSync(__dirname+'/gear.js','utf8'),sandbox);
 const src=fs.readFileSync(__dirname+'/game.js','utf8').replace(/\}\)\(\);\s*$/,`globalThis.test={start:()=>{start();enter()},startTown:start,summonInterval,drawItemIcon,openMainMenu,chooseSaveSlot,readSlot,tickBossExit,manaPercent,itemSymbol,canAutoMove,setAutoMove,openSettings,closeSettings,float,tickNumbers,changeScene,tickSceneFade,rawUpdate:update,pickLoot,setLoot:l=>loot.push(l),stageExitOpen,defeatBossAndAdvance:()=>{enemies.filter(e=>e.type==='boss').forEach(e=>e.hp=0);tickBossExit(2);completeArea()},REGIONAL_POOLS,REGION_BOSSES,tickRogueArms,rogueHands,applySong,songTotal,enemyDamage,effectiveAgi,setTime:n=>time=n,tickMinions,shootNote,swingSegments,combatAllies,classes,draw,shopPages,renderServices,fitFullscreen,setShopPage:n=>shopIndex=n,WORLD,controlDuration,slowFactor,panMap,setPan:n=>mapPan=n,xpGain,stepEnemyPhysics,tickCatapult,drawEnemy,ENEMY_TYPES,enemyTrait,encounterType,revivalCost,revive,tickSlash,attackMotion,needed,areaHealth,weaponPrice,buyPrice,aura,terrainHit,tickShots,moveEnemy,innCost,stepHeld,grounded,launchHazard,tickHazards,tickSpecial,moveHeld,release,setHeld:h=>drag=h,stageCount,shopStock,setStage:n=>stage=n,clearRegion:()=>{for(let i=stage;i<stageCount();){enemies.filter(e=>e.type==='boss').forEach(e=>e.hp=0);tickBossExit(2);completeArea();tickSceneFade(1);if(state==='map')break}},openMap,travel,completeArea,healTown,sellItem,buyRune,pickPotions,unlockedNodes,inspect,inspectHero,restoreInfo,update,damage,xp,equip,enter,load,save,stats,allocate,select,moveItem,attackToken,basicHit,activate,tickEffects,enemy,shoot,rollDrops,weaponDropTable,WEAPON_DROPS,dropMultiplier,stepBody,resolveStrike,frame,toggle,get:()=>({menuOpen,activeSlot,sceneFade,heroes,minions,enemies,numbers,hazards,blasts,area,stage,state,inventory,inventoryRunes,fields,shots,loot,paused,time,completed,potions,currentNode,selected,hoverHero,inspectingItem,gold}),setPotion:p=>potions.push(p),setGold:n=>gold=n,setPicked:s=>pickedSlot=s,setGearDrag:v=>gearDrag=v,setArea:n=>area=n,setItem:(i,id)=>inventory[i]=id,setParty:ids=>heroes=ids.map(hero),items:ITEMS,effects:EFFECTS};})();`);
 vm.runInNewContext(src,sandbox);const api=sandbox.test;api.chooseSaveSlot(1);for(const name of ['update','travel','completeArea','defeatBossAndAdvance']){const original=api[name];api['raw_'+name]=original;api[name]=(...args)=>{const result=original(...args);api.tickSceneFade(1);return result}}return {t:api,storage,choices,math,events,elements};
}
const {t,storage,choices}=harness();
choices.forEach(c=>c.value='1');t.start();assert.ok(t.get().heroes.every(h=>h.classId===1));
assert.equal(t.get().enemies.length,6);for(let i=0;i<100;i++)t.update(.02);assert.equal(t.get().enemies.length,6,'No timed spawning');
t.xp(225);assert.ok(t.get().heroes.every(h=>h.level===2&&h.sp===2));t.select(0);assert.ok(t.allocate('int'));assert.equal(t.get().heroes[0].int,1);assert.ok(t.allocate('dex'));assert.equal(t.allocate('int'),false,'Cannot spend without SP');
t.xp(t.needed(2));assert.ok(t.allocate('int'));let h=t.get().heroes[0];assert.equal(h.int,2);
t.setItem(0,'1-fire');assert.ok(t.equip(0));assert.equal(h.weapon,'1-fire');assert.equal(t.get().inventory[0],'1-basic','Equipping swaps original into inventory');
let victim=t.get().enemies[0];victim.hp=victim.maxHp=10000;
for(let i=1;i<=4;i++){t.basicHit(victim,1,t.attackToken(h));assert.equal(h.mp,i*2);assert.equal(t.get().fields.length,0)}
t.basicHit(victim,1,t.attackToken(h));assert.equal(h.mp,0);assert.equal(t.get().fields.length,1,'2 INT / 10 MP fires on fifth landed hit');
t.tickEffects(.05);assert.equal(h.mp,0,'Ability damage does not generate MP');
const token=t.attackToken(h);t.basicHit(victim,1,token);t.basicHit(victim,1,token);assert.equal(h.mp,2,'Multiple targets charge only once per basic attack');
const inFlight=t.attackToken(h);assert.ok(t.moveItem({type:'gear',index:0},{type:'bag',index:3}));assert.equal(h.weapon,null);assert.equal(h.mp,0);t.basicHit(victim,1,inFlight);assert.equal(h.mp,0,'Old projectile cannot charge new equipment');assert.equal(t.get().inventory[3],'1-fire');
assert.ok(t.moveItem({type:'bag',index:3},{type:'gear',index:0}));assert.equal(h.weapon,'1-fire');assert.equal(t.get().inventory[3],null);
t.setItem(4,'2-poison');assert.equal(t.moveItem({type:'bag',index:4},{type:'gear',index:0}),false,'Wrong class rejected atomically');assert.equal(t.get().inventory[4],'2-poison');assert.equal(h.weapon,'1-fire');
t.setItem(5,'1-steel');assert.ok(t.equip(5));assert.equal(h.weapon,'1-steel');t.setItem(6,'1-ice');assert.ok(t.moveItem({type:'bag',index:6},{type:'bag',index:5}));assert.equal(t.get().inventory[5],'1-ice');
// Class-specific stat effects.
for(let c=0;c<8;c++){t.setParty([c,c,c,c]);const p=t.get().heroes[0];const before={max:p.atMax,min:p.atMin,range:p.range,agi:p.agi[0]};p.attributes.str++;t.stats(p);if(c===0)assert.equal(p.atMax,before.max+1);if(c===2||c===3)assert.equal(p.range,before.range+2);p.attributes.int=2;t.stats(p);assert.equal(p.int,2)}
assert.ok(t.items['0-heavy'].max>t.items['0-lightning'].max,'Physical sword can outdamage elemental sword');
// Freeze/slow, poison, lightning, heal, drain, stun all execute actual gameplay effects.
t.setParty([0,2,3,4]);t.setArea(0);t.enter();h=t.get().heroes[0];victim=t.get().enemies[0];victim.hp=victim.maxHp=10000;t.activate(h,victim,'ice');assert.ok(victim.frozen>0);t.tickEffects(.8);assert.equal(victim.frozen,0);assert.ok(!(victim.slow>0));
t.activate(h,victim,'poison');const beforePoison=victim.hp;t.tickEffects(1);assert.ok(victim.hp<beforePoison);const hp=victim.hp;t.activate(h,victim,'lightning');assert.ok(victim.hp<hp);h.hp=10;t.activate(h,victim,'heal');assert.ok(h.hp>10);const beforeDrain=h.hp;t.activate(h,victim,'drain');assert.ok(h.hp>beforeDrain);t.activate(h,victim,'stun');assert.ok(victim.stun>0);
// Killing hit still charges. No charge for attacks on already dead targets.
h.weapon='0-fire';h.attributes.int=2;t.stats(h);h.mp=0;victim.hp=1;t.basicHit(victim,10,t.attackToken(h));assert.equal(h.mp,2);t.basicHit(victim,10,t.attackToken(h));assert.equal(h.mp,2);
t.get().enemies.slice().forEach(e=>t.damage(e,99999));t.update(.01);assert.equal(t.get().state,'walk');assert.equal(t.get().area,0);const stopped=t.get().heroes.map(h=>h.x);for(let i=0;i<100;i++)t.update(.02);assert.equal(t.get().stage,0);t.get().heroes.forEach((h,i)=>assert.ok(Math.abs(h.x-stopped[i])<2,'Cleared party stays in place'));const exitHero=t.get().heroes[0];exitHero.x=554;exitHero.y=100;t.update(.01);assert.equal(t.get().stage,0,'Flying above sign does not advance');exitHero.y=226;exitHero.vy=0;t.update(.01);assert.equal(t.get().stage,1,'Only one hero must touch sign');assert.ok(!t.get().completed.includes('a0'));
t.setArea(4);t.enter();const summoner=t.get().enemies.find(e=>e.type==='summoner');const count=t.get().enemies.length;summoner.summon=0;t.update(.01);assert.equal(t.get().enemies.length,count+1);
t.get().heroes.forEach(h=>h.hp=0);t.update(.01);assert.equal(t.get().state,'service');assert.equal(t.get().currentNode,'town');assert.ok(t.get().heroes.every(h=>h.hp===Math.ceil(h.maxHp*.05)));
// Opening party still wins and earns unspent points without automatic spending.
t.setArea(0);t.setParty([0,2,3,4]);t.enter();for(let i=0;i<20000&&t.get().state!=='map'&&t.get().state!=='lost';i++)t.update(.02);assert.ok(t.get().stage>0);assert.ok(t.get().heroes.every(h=>h.int===0));
t.xp(t.needed(t.get().heroes[0].level));t.select(0);t.allocate('int');t.setItem(0,'0-fire');t.equip(0);t.get().heroes[0].mp=3;t.save();const reloaded=harness(storage).t.get();assert.equal(reloaded.heroes[0].weapon,'0-fire');assert.equal(reloaded.heroes[0].int,1);assert.equal(reloaded.heroes[0].mp,3);assert.equal(reloaded.inventory.length,15);
const old={area:3,gold:99,inventory:[1,2],heroes:[0,2,3,4].map(classId=>({classId,level:5,xp:2,weapon:2}))};const migrated=harness({'bramblebound-v2':JSON.stringify(old)}).t.get();assert.equal(migrated.heroes[0].sp,8);assert.equal(migrated.heroes[0].weapon,'0-iron');assert.equal(migrated.area,3);

// No charging with zero INT; minimum level restrictions leave both slots intact.
const isolated=harness().t;isolated.start();let fighter=isolated.get().heroes[0];isolated.setItem(0,'0-steel');assert.equal(isolated.equip(0),false);assert.equal(fighter.weapon,'0-basic');assert.equal(isolated.get().inventory[0],'0-steel');
isolated.setItem(1,'0-fire');isolated.equip(1);let dummy=isolated.get().enemies[0];dummy.hp=dummy.maxHp=10000;isolated.basicHit(dummy,1,isolated.attackToken(fighter));assert.equal(fighter.mp,0);
// Ten fire pulses regardless of coarse simulation steps, without proc recursion.
isolated.activate(fighter,dummy,'fire');let field=isolated.get().fields[0];const fireStart=dummy.hp,fireAmount=field.amount;for(let i=0;i<11;i++)isolated.tickEffects(.1);assert.equal(dummy.hp,fireStart-fireAmount*10);assert.equal(fighter.mp,0);assert.equal(isolated.get().fields.length,0);
// A launched projectile earns nothing until it actually lands.
fighter.attributes.int=2;isolated.stats(fighter);dummy.x=fighter.x+100;dummy.y=fighter.y;isolated.get().heroes.forEach(h=>h.cooldown=10);isolated.get().enemies.forEach(e=>e.cooldown=10);isolated.shoot(fighter,dummy,'arrow',1,isolated.attackToken(fighter));isolated.update(.01);assert.equal(fighter.mp,0);for(let i=0;i<80;i++)isolated.tickShots(.01);assert.equal(fighter.mp,2);
// Cancelling an attack because the victim was already dead yields no MP.
const discarded=isolated.attackToken(fighter);dummy.hp=0;isolated.shoot(fighter,dummy,'arrow',1,discarded);isolated.update(.01);assert.equal(fighter.mp,2);
// Continuous simulation while dragging equipment or changing focus; manual pause still works.
const motion=harness();motion.t.start();motion.t.setGearDrag({from:{type:'bag',index:0},moved:false});motion.t.frame(16);assert.ok(motion.t.get().time>0,'Equipment dragging must not pause');motion.events.blur();assert.equal(motion.t.get().paused,false);const elapsed=motion.t.get().time;motion.t.frame(32);assert.ok(motion.t.get().time>elapsed);motion.t.toggle();motion.events.blur();motion.t.frame(48);assert.equal(motion.t.get().paused,true);assert.equal(motion.t.get().time,elapsed+.016);motion.t.toggle();
const body=motion.t.get().heroes[0];body.drive=33;body.vx=0;const beforeX=body.x;motion.t.stepBody(body,1/60);assert.ok(body.vx>0&&body.vx<33);assert.ok(body.x>beforeX);const momentum=body.vx;motion.t.stepBody(body,1/60);assert.ok(body.vx>0&&body.vx<momentum,'Coasting decelerates instead of snapping');body.y=70;body.vy=0;for(let i=0;i<240;i++)motion.t.stepBody(body,1/120);assert.ok(body.y>=200&&body.y<=226);assert.ok(Number.isFinite(body.lean));
body.classId=1;const meleeTarget=motion.t.get().enemies[0];meleeTarget.x=body.x+10;meleeTarget.y=body.y;const health=meleeTarget.hp;body.strike={left:.09,target:meleeTarget,amount:3,token:motion.t.attackToken(body),range:30};motion.t.resolveStrike(body,.04);assert.equal(meleeTarget.hp,health,'Swing windup deals no immediate damage');motion.t.resolveStrike(body,.06);assert.equal(meleeTarget.hp,health-3);assert.ok(meleeTarget.kick>0);body.strike={left:.09,target:meleeTarget,amount:3,token:motion.t.attackToken(body),range:30};meleeTarget.x+=100;motion.t.resolveStrike(body,.1);assert.equal(meleeTarget.hp,health-3,'Out-of-range melee attack misses');
// Exact drop boundary, no guaranteed final kill, and both item categories.

const drops=harness();drops.t.start();drops.math.random=()=>.9;
drops.t.get().enemies.forEach(e=>drops.t.damage(e,9999));assert.equal(drops.t.get().loot.length,0,'Last enemy has no guaranteed drop');
for(const [type,low,high] of [['slime',4700,5300],['swarmling',2300,2700],['boss',9600,10400]]){
 const sample=harness(),foe=sample.t.enemy(type,300);let weapons=0,sockets=0,souls=0;
 for(let i=0;i<100000;i++)for(const id of sample.t.rollDrops(foe)){const item=sample.t.items[id];if(item.type==='weapon')weapons++;else if(item.type==='soul')souls++;else sockets++;}
 assert.ok(weapons>low&&weapons<high,type+' weapon rate '+weapons);assert.ok(sockets>850&&sockets<1150);assert.ok(type==='boss'?souls>9500&&souls<10500:souls===0);
}

const run=harness(),rt=run.t;rt.start();const rh=rt.get().heroes[0];rt.setItem(0,'rune-leech');assert.ok(rt.moveItem({type:'bag',index:0},{type:'rune0',index:0}));rt.setItem(1,'rune-ward');assert.ok(rt.moveItem({type:'bag',index:1},{type:'rune1',index:0}));assert.equal(rh.runes.length,2);
assert.equal(rt.moveItem({type:'rune0',index:0},{type:'gear',index:0}),false);assert.equal(rt.moveItem({type:'gear',index:0},{type:'rune1',index:0}),false);
rh.hp=20;const target=rt.get().enemies[0];target.hp=5;rt.basicHit(target,100,rt.attackToken(rh));assert.equal(rh.hp,20.1,'Lifesteal uses actual damage, not overkill');
rt.setParty([0,0,0,0]);const q=rt.get().heroes[0];q.runes=['rune-ward','rune-ward'];rt.stats(q);q.hp=100;rt.damage(q,20,'poison');assert.equal(q.hp,90);rt.damage(q,20);assert.equal(q.hp,70,'Ward does not reduce physical damage');
q.runes=['rune-wisdom',null];rt.stats(q);rt.xp(10);assert.equal(q.xp,11);assert.equal(rt.get().heroes[1].xp,10);
q.attributes.str=10;q.runes=[null,null];rt.stats(q);const baseAgi=q.agi[0],baseAt=q.atMax,baseRange=q.range,baseHp=q.maxHp;
q.runes=['rune-haste','rune-might'];rt.stats(q);assert.ok(q.agi[0]<baseAgi);assert.ok(q.atMax>baseAt);
q.runes=['rune-reach','rune-vitality'];rt.stats(q);assert.equal(q.range,baseRange+15);assert.equal(q.maxHp,Math.floor(baseHp*1.2));
q.runes=['rune-renewal',null];rt.stats(q);q.hp=20;rt.update(.5);assert.equal(q.hp,20.5);
assert.equal(rt.moveItem({type:'rune0',index:0},{type:'bag',index:4}),false);assert.equal(q.runes[0],'rune-renewal');assert.equal(rt.get().inventory[4],null);
rt.setItem(5,'rune-reach');rt.moveItem({type:'bag',index:5},{type:'rune1',index:0});rt.save();const restored=harness(run.storage).t.get();assert.equal(restored.heroes[0].runes[1],'rune-reach');assert.equal(restored.inventory[4],null);
const legacy={version:3,area:0,gold:0,inventory:[],heroes:[0,2,3,4].map(classId=>({classId,level:5,xp:0,weapon:classId+'-fire',attributes:{str:1,dex:1,int:2}}))};
const upgraded=harness({'bramblebound-v3':JSON.stringify(legacy)});assert.equal(upgraded.t.get().heroes[0].sp,4);upgraded.t.save();assert.equal(harness(upgraded.storage).t.get().heroes[0].sp,4,'SP top-up does not repeat on reload');
// Town starts the journey; paths unlock on completion, including the trader detour.
const world=harness(),wt=world.t;wt.startTown();assert.equal(wt.get().state,'service');assert.equal(wt.get().currentNode,'town');assert.equal(wt.travel('a3'),false);assert.equal(wt.travel('trader'),false);
const wh=wt.get().heroes[0];wh.hp=17;wt.xp(225);assert.equal(wh.hp,17,'Leveling never heals');wt.allocate('str');assert.equal(wh.hp,17,'Spending HP-increasing stats never heals');assert.ok(wt.travel('a0'));assert.equal(wh.hp,17);wt.clearRegion();assert.ok(wt.unlockedNodes().has('a1'));assert.ok(!wt.unlockedNodes().has('a2'));assert.ok(wt.travel('a1'));assert.equal(wh.hp,17);wt.clearRegion();wt.travel('a2');wt.clearRegion();assert.ok(wt.unlockedNodes().has('a3'));assert.ok(wt.unlockedNodes().has('trader'));assert.equal(wh.hp,17);
wt.travel('trader');assert.equal(wt.healTown(),false);wt.setGold(1100);assert.ok(wt.buyRune('rune-ward'));assert.equal(wt.get().gold,100);assert.equal(wt.buyRune('rune-leech'),false);wt.setPicked({type:'bag',index:0});assert.ok(wt.sellItem());assert.equal(wt.get().inventory[0],null);assert.equal(wt.get().gold,125);assert.equal(wt.sellItem(),false);
wt.travel('town');assert.equal(wh.hp,17,'Visiting town alone does not heal');wt.get().heroes[1].hp=0;wt.healTown();assert.equal(wh.hp,wh.maxHp);assert.equal(wt.get().heroes[1].hp,wt.get().heroes[1].maxHp);
wh.hp=19;wt.get().heroes[1].hp=0;wt.save();const healthReload=harness(world.storage).t;assert.equal(healthReload.get().heroes[0].hp,19);assert.equal(healthReload.get().heroes[1].hp,0);assert.ok(healthReload.unlockedNodes().has('trader'));
// Five-percent potions are independent from item drops and heal only the grounded collector.
const pot=harness(),pt=pot.t;pt.start();pot.math.random=()=>.30;pt.damage(pt.get().enemies[0],9999);assert.equal(pt.get().potions.length,0);pot.math.random=()=>.29999;pt.damage(pt.get().enemies[1],9999);assert.equal(pt.get().potions.length,1);assert.equal(pt.get().loot.length,0);const potion=pt.get().potions[0];pt.get().heroes.forEach((h,i)=>{h.hp=10;h.x=20+i*10;h.y=226});const collector=pt.get().heroes[2];collector.x=potion.x;collector.y=potion.y-30;pt.pickPotions();assert.equal(pt.get().potions.length,1,'Airborne heroes cannot consume ground potions');collector.y=potion.y;pt.pickPotions();assert.equal(pt.get().potions.length,0);assert.equal(collector.hp,10+Math.ceil(collector.maxHp*.2));assert.equal(pt.get().heroes[0].hp,10);assert.equal(pt.get().heroes[1].hp,10);assert.equal(pt.get().heroes[3].hp,10);
pt.setPotion({x:collector.x,y:collector.y});collector.hp=collector.maxHp-1;pt.pickPotions();assert.equal(collector.hp,collector.maxHp);pt.setPotion({x:collector.x,y:collector.y});collector.hp=0;pt.pickPotions();assert.equal(pt.get().potions.length,1,'Potion cannot revive a corpse');
// Hovering uses the left panel and does not change selection.
wt.inspect('0-fire');assert.equal(world.elements.get('#hover-info').hidden,false);assert.equal(world.elements.get('#character-info').hidden,true);wt.inspectHero(2);assert.equal(wt.get().selected,0);assert.equal(world.elements.get('#class-name').textContent,'Mage');wt.restoreInfo();assert.equal(world.elements.get('#hover-info').hidden,true);

// Bound sockets follow individual weapon copies through swaps and saves.
const bind=harness(),bt=bind.t;bt.start();bt.setItem(0,'rune-might');assert.ok(bt.moveItem({type:'bag',index:0},{type:'rune0',index:0}));bt.setItem(1,'rune-reach');assert.equal(bt.moveItem({type:'bag',index:1},{type:'rune0',index:0}),false);
bt.setItem(2,'0-basic');assert.ok(bt.moveItem({type:'bag',index:2},{type:'gear',index:0}));assert.equal(bt.get().heroes[0].runes[0],null);assert.equal(bt.get().inventoryRunes[2][0],'rune-might');bt.save();const br=harness(bind.storage).t;assert.equal(br.get().inventoryRunes[2][0],'rune-might');assert.ok(br.moveItem({type:'bag',index:2},{type:'gear',index:0}));assert.equal(br.get().heroes[0].runes[0],'rune-might');
const stages=harness(),st=stages.t;st.start();for(let a=0;a<9;a++){st.setArea(a);assert.ok(st.stageCount()>=5&&st.stageCount()<=8);st.setStage(0);st.enter();assert.ok(!st.get().enemies.some(e=>e.type==='boss'));st.setStage(st.stageCount()-1);st.enter();assert.equal(st.get().enemies.filter(e=>e.type==='boss').length,1)}
const sh=harness(),shp=sh.t;shp.startTown();assert.ok(shp.shopStock().every(w=>w.tier===0));shp.openMap();assert.ok(!sh.elements.get('#map-nodes').innerHTML.includes('Woodland'));shp.travel('a0');shp.clearRegion();shp.travel('town');assert.ok(shp.shopStock().every(w=>w.tier===0));shp.setGold(1000);assert.equal(shp.buyRune('0-steel'),false);

// Enemy attacks have physical trajectories; a missed target is not damaged.
const combat=harness(),ct=combat.t;ct.start();const ch=ct.get().heroes[0];ct.get().heroes.forEach((h,i)=>{h.x=90+i*25;h.y=226;h.hp=h.maxHp});
const shooter=ct.enemy('spitter',300);let projectile=ct.launchHazard(shooter,ch,'bullet',0,30);const originalAngle=Math.atan2(projectile.vy,projectile.vx);ch.y=100;const dodgeHp=ch.hp;for(let i=0;i<100;i++)ct.tickHazards(.01);assert.equal(ch.hp,dodgeHp,'Moving out of straight bullet path dodges it');assert.equal(Math.atan2(projectile.vy,projectile.vx),originalAngle);
ch.x=200;ch.y=226;projectile=ct.launchHazard(shooter,ch,'bullet',0,30);const hitHp=ch.hp;for(let i=0;i<80;i++)ct.tickHazards(.01);assert.ok(ch.hp<hitHp,'Bullet collides with body');
projectile=ct.launchHazard(shooter,ch,'arrow');const vy=projectile.vy;ct.tickHazards(.1);assert.ok(projectile.vy>vy,'Arrows fall under gravity');
projectile=ct.launchHazard(shooter,ch,'missile');const heading=Math.atan2(projectile.vy,projectile.vx);ch.y=40;ct.tickHazards(.1);const change=Math.abs(Math.atan2(Math.sin(Math.atan2(projectile.vy,projectile.vx)-heading),Math.cos(Math.atan2(projectile.vy,projectile.vx)-heading)));assert.ok(change>0&&change<=.150001,'Homing turn is limited so missiles can be outmaneuvered');
const bombs=harness(),btwo=bombs.t;btwo.start();const bh=btwo.get().heroes[0];btwo.get().heroes.forEach((h,i)=>{h.x=20+i*15;h.y=226});const bomb=btwo.launchHazard(btwo.enemy('boss',300),bh,'bomb',0,40);bomb.x=bh.x;bomb.y=bh.y-3;bomb.vx=bomb.vy=0;bomb.fuse=.2;const beforeBomb=bh.hp;btwo.tickHazards(.1);assert.equal(bh.hp,beforeBomb);btwo.tickHazards(.11);assert.equal(bh.hp,beforeBomb-40,'Bomb only damages when its fuse expires');assert.ok(btwo.get().blasts.length);
const pattern=btwo.enemy('boss',350);pattern.specialCooldown=0;btwo.tickSpecial(pattern,bh,.01);assert.ok(pattern.warning);const countBefore=btwo.get().hazards.length;btwo.tickSpecial(pattern,bh,.5);assert.equal(btwo.get().hazards.length,countBefore);btwo.tickSpecial(pattern,bh,.5);assert.equal(btwo.get().hazards.length,countBefore+7,'Telegraph precedes seven-shot fan');
const thrower=harness(),tt=thrower.t;tt.start();const th=tt.get().heroes[0];th.x=100;th.y=160;th.vx=th.vy=0;tt.setHeld(th);tt.moveHeld(160,100,200);assert.equal(th.x,100,'Pointer movement sets target without teleporting body');for(let i=0;i<10;i++)tt.stepHeld(th,.01);assert.ok(th.x>100&&th.x<160&&th.y<160&&th.y>100,'Body lags behind dragged target');const releaseX=th.x,releaseY=th.y,throwVX=th.vx,throwVY=th.vy;tt.release({timeStamp:200});assert.equal(th.vx,throwVX);assert.equal(th.vy,throwVY);tt.stepBody(th,.05);assert.ok(th.x>releaseX&&th.y<releaseY,'Release carries spring momentum');for(let i=0;i<200;i++)tt.stepBody(th,.01);th.y=100;th.vy=300;for(let i=0;i<80&&th.vy!==0;i++)tt.stepBody(th,.01);assert.ok(th.crouch>0,'Landing compresses the body');
const air=harness(),at=air.t;at.start();const ah=at.get().heroes[0],ae=at.get().enemies[0];ah.x=ae.x-10;ah.y=100;ah.vy=0;ah.cooldown=0;const enemyHealth=ae.hp;at.update(.01);assert.equal(ah.strike,null);assert.ok(!at.get().shots.some(s=>s.attack?.owner===ah));ah.strike={left:0,target:ae,amount:50,token:at.attackToken(ah),range:100};at.resolveStrike(ah,.01);assert.equal(ae.hp,enemyHealth,'Airborne pending melee hit is cancelled');
const inn=harness(),it=inn.t;it.startTown();const ih=it.get().heroes[0];ih.hp-=21;assert.equal(it.innCost(),3);it.setGold(2);assert.equal(it.healTown(),false);assert.equal(ih.hp,ih.maxHp-21);assert.equal(it.get().gold,2);it.setGold(10);assert.ok(it.healTown());assert.equal(it.get().gold,7);assert.equal(ih.hp,ih.maxHp);assert.equal(it.innCost(),0);it.healTown();assert.equal(it.get().gold,7);
tt.select(3);const priest=tt.get().heroes[3];priest.attributes.str=6;priest.attributes.dex=11;tt.stats(priest);tt.inspectHero(3);assert.match(thrower.elements.get('#priest-aura').textContent,/AT \+6% · DEF \+2.2/);tt.inspectHero(0);assert.equal(thrower.elements.get('#priest-aura').hidden,true);

const slowDrag=harness().t,fastDrag=harness().t;for(const d of [slowDrag,fastDrag]){d.start();const h=d.get().heroes[0];h.x=100;h.y=150;h.vx=h.vy=0;h.dragSample={x:100,y:150,t:0};d.setHeld(h)}slowDrag.moveHeld(160,100,1000);fastDrag.moveHeld(160,100,50);for(let i=0;i<8;i++){slowDrag.stepHeld(slowDrag.get().heroes[0],.01);fastDrag.stepHeld(fastDrag.get().heroes[0],.01)}assert.ok(fastDrag.get().heroes[0].x>slowDrag.get().heroes[0].x+8,'Fast cursor movement produces faster follow at equal distance');

const mechanics=harness(),mt=mechanics.t;mt.start();assert.deepEqual(Array.from({length:16},(_,i)=>mt.areaHealth(i)),[20,40,60,80,100,130,160,190,220,250,290,330,370,410,450,500]);for(let i=0;i<9;i++){mt.setArea(i);assert.equal(mt.enemy('boss',300).maxHp,mt.areaHealth(i)*10)}assert.deepEqual(Array.from({length:13},(_,i)=>mt.weaponPrice(i)),[100,250,500,750,1000,1500,2000,2500,3000,3500,4000,4500,5000]);assert.equal(mt.weaponPrice(22),10000);assert.equal(mt.weaponPrice(23),11000);assert.equal(mt.buyPrice(mt.items['0-ice']),750);assert.equal(mt.needed(1),225);
mt.setArea(1);mt.setStage(0);mt.enter();assert.ok(mt.terrainHit(160,215,200,215),'A terrain wall blocks a low shot');const wallTarget=mt.get().enemies[0];wallTarget.x=210;wallTarget.y=226;wallTarget.hp=100;const wallShooter=mt.get().heroes[0];wallShooter.x=160;wallShooter.y=226;mt.shoot(wallShooter,wallTarget,'bullet',40,mt.attackToken(wallShooter));mt.tickShots(.3);assert.equal(wallTarget.hp,100);assert.equal(mt.get().shots.length,0);
const climber=mt.get().heroes[0];climber.x=179.9;climber.y=226;climber.vy=0;climber.vx=33;climber.drive=33;mt.stepBody(climber,.01);assert.ok(climber.y>220,'Hero does not snap 19 pixels up hill');for(let i=0;i<150;i++){climber.drive=33;mt.stepBody(climber,.01)}assert.ok(climber.x>180&&Math.abs(climber.y-207)<1,'Hero finishes stepping onto ledge');
const ec=mt.enemy('slime',179.9);mt.moveEnemy(ec,.3,.01);assert.ok(ec.y>220);for(let i=0;i<150;i++)mt.moveEnemy(ec,.17,.01);assert.ok(ec.x>180&&Math.abs(ec.y-207)<1,'Enemy steps onto ledge');
mt.setArea(0);mt.setParty([4,0,0,0]);mt.enter();const priestPulse=mt.get().heroes[0];priestPulse.x=260;priestPulse.y=219;priestPulse.weapon='4-fire';priestPulse.attributes.int=2;priestPulse.attributes.str=4;mt.stats(priestPulse);priestPulse.cooldown=0;mt.get().heroes.slice(1).forEach(h=>{h.x=20;h.cooldown=99});mt.get().enemies.forEach((e,i)=>{e.x=i<2?280+i*20:480;e.y=219;e.hp=e.maxHp=100;e.cooldown=99;e.specialCooldown=99});mt.update(.001);assert.ok(mt.get().enemies[0].hp<100&&mt.get().enemies[1].hp<100);assert.equal(mt.get().enemies[2].hp,100);assert.equal(priestPulse.mp,2,'Aura pulse charges MP once for multiple enemies');const ally=mt.get().heroes[1];ally.x=priestPulse.x;ally.y=priestPulse.y-200;assert.equal(mt.aura(ally).attack,1,'Above the aura gets no buff');ally.y=priestPulse.y;assert.ok(mt.aura(ally).attack>1);


const resurrection=harness(),rv=resurrection.t;rv.start();const corpse=rv.get().heroes[0];corpse.level=3;rv.stats(corpse);corpse.hp=0;rv.setGold(29);rv.select(0);assert.equal(rv.revivalCost(corpse),30);assert.equal(rv.revive(),false);assert.equal(corpse.hp,0);assert.equal(resurrection.elements.get('#revive').hidden,false);rv.setGold(1000);assert.equal(rv.revivalCost(corpse),100);assert.ok(rv.revive());assert.equal(rv.get().gold,900);assert.equal(corpse.hp,Math.ceil(corpse.maxHp*.1));assert.equal(rv.revive(),false);rv.get().heroes.forEach(h=>h.hp=0);rv.update(.01);assert.equal(rv.get().state,'service');assert.equal(rv.get().currentNode,'town');assert.ok(rv.get().heroes.every(h=>h.hp===Math.ceil(h.maxHp*.05)));assert.equal(rv.get().gold,900);assert.equal(rv.revive(),false);assert.equal(resurrection.elements.get('#result').hidden,true);
const closeCombat=harness().t;closeCombat.start();assert.ok(closeCombat.get().enemies.some(e=>e.type==='slasher'));const slashEnemy=closeCombat.enemy('slasher',250),dodgeHero=closeCombat.get().heroes[0];closeCombat.get().heroes.forEach(h=>{h.x=20;h.y=226});dodgeHero.x=225;dodgeHero.y=slashEnemy.y;slashEnemy.slash={left:.18,life:.32,face:-1,hit:false};const initialHP=dodgeHero.hp;closeCombat.tickSlash(slashEnemy,.1);assert.equal(dodgeHero.hp,initialHP);dodgeHero.y-=60;closeCombat.tickSlash(slashEnemy,.09);assert.equal(dodgeHero.hp,initialHP,'Lifting hero dodges slash');closeCombat.tickSlash(slashEnemy,.2);assert.equal(slashEnemy.slash,null);
dodgeHero.y=slashEnemy.y;slashEnemy.slash={left:.18,life:.32,face:-1,hit:false};closeCombat.tickSlash(slashEnemy,.19);assert.ok(dodgeHero.hp<initialHP);const afterSlash=dodgeHero.hp;closeCombat.tickSlash(slashEnemy,.01);assert.equal(dodgeHero.hp,afterSlash,'Slash damages only once');
const bombBoss=closeCombat.enemy('boss',350);bombBoss.warning={left:0,pattern:'BOMBS',x:100,y:226};closeCombat.tickSpecial(bombBoss,dodgeHero,.01);assert.equal(closeCombat.get().hazards.filter(p=>p.kind==='bomb').length,1);const shortMissile=closeCombat.launchHazard(bombBoss,dodgeHero,'missile');assert.equal(shortMissile.life,1.6);for(let i=0;i<170;i++)closeCombat.tickHazards(.01);assert.ok(!closeCombat.get().hazards.includes(shortMissile));closeCombat.attackMotion(dodgeHero);assert.equal(dodgeHero.swingV,48);assert.equal(dodgeHero.swing,-.8);


const auraUI=harness(),au=auraUI.t;au.start();au.setParty([0,4,4,0]);au.enter();const ahh=au.get().heroes;ahh[0].x=200;ahh[0].y=219;ahh[1].x=210;ahh[1].y=219;ahh[2].x=215;ahh[2].y=219;ahh[1].attributes.str=50;ahh[2].attributes.str=50;au.stats(ahh[1]);au.stats(ahh[2]);au.inspectHero(0);assert.equal(auraUI.elements.get('#attack').textContent,Math.round(ahh[0].atMin*2)+'–'+Math.round(ahh[0].atMax*2));ahh[2].x=500;au.inspectHero(0);assert.equal(auraUI.elements.get('#attack').textContent,Math.round(ahh[0].atMin*1.5)+'–'+Math.round(ahh[0].atMax*1.5));ahh[1].hp=0;au.inspectHero(0);assert.equal(auraUI.elements.get('#attack').textContent,ahh[0].atMin+'–'+ahh[0].atMax);
const slowBomb=au.launchHazard(au.enemy('spitter',400),ahh[0],'bomb');assert.ok(Math.abs(slowBomb.vx)<110);assert.equal(slowBomb.fuse,2.6);assert.equal(au.enemy('slasher',300).range,22);assert.equal(au.enemy('slime',300).range,12);

const variety=harness().t;variety.start();const foundTypes=new Set();for(let a=0;a<18;a++){variety.setArea(a);for(let stg=0;stg<variety.stageCount();stg++){variety.setStage(stg);variety.enter();variety.get().enemies.forEach(e=>{foundTypes.add(e.type);foundTypes.add(e.species);variety.drawEnemy(e);assert.ok(Number.isFinite(e.hp)&&e.hp>0)});assert.equal(variety.get().enemies.filter(e=>e.type==='boss').length,stg===variety.stageCount()-1?1:0)}}for(const id of Object.keys(variety.ENEMY_TYPES))assert.ok(foundTypes.has(id),'Encounter coverage '+id);
variety.setArea(0);const swarm=variety.enemy('swarmling',300),beetle=variety.enemy('beetle',300);assert.equal(swarm.maxHp,10);assert.equal(swarm.range,10);assert.equal(beetle.maxHp,36);assert.ok(swarm.speed>beetle.speed);const hop=variety.enemy('hopper',300);hop.hopCooldown=0;variety.stepEnemyPhysics(hop,{x:100,y:226},.01);assert.ok(hop.vy<0&&hop.vx<0);
variety.setArea(3);variety.setStage(0);variety.enter();const shaman=variety.enemy('shaman',300);variety.get().enemies.push(shaman);const patient=variety.get().enemies[0];patient.x=310;patient.hp=1;for(let i=0;i<3;i++){shaman.healCooldown=0;variety.enemyTrait(shaman,{x:20},.01)}assert.equal(shaman.heals,0);const healed=patient.hp;assert.ok(healed>1);shaman.healCooldown=0;variety.enemyTrait(shaman,{x:20},.01);assert.equal(patient.hp,healed,'Shaman cannot heal indefinitely');


const physicsEnemies=harness().t;physicsEnemies.start();const prey={x:100,y:226,hp:100};const spider=physicsEnemies.enemy('spider',300);for(let i=0;i<100;i++)physicsEnemies.stepEnemyPhysics(spider,prey,.01);assert.equal(spider.feet.length,6);assert.ok(spider.x<300);assert.ok(spider.feet.some(f=>f.step),'Spider feet step independently');const rolling=physicsEnemies.enemy('roller',300);for(let i=0;i<100;i++)physicsEnemies.stepEnemyPhysics(rolling,prey,.01);assert.ok(rolling.vx<-50);assert.ok(Math.abs(rolling.rotation)>1);physicsEnemies.stepEnemyPhysics(rolling,{x:500,y:226},.01);assert.ok(rolling.vx<0,'Roller keeps momentum when target changes sides');
const bat=physicsEnemies.enemy('flyer',300);for(let i=0;i<120;i++)physicsEnemies.stepEnemyPhysics(bat,prey,.01);assert.ok(bat.x<300);assert.ok(bat.y<226);assert.ok(Number.isFinite(bat.vy));
const lobber=physicsEnemies.enemy('catapult',300);lobber.cooldown=0;physicsEnemies.tickCatapult(lobber,prey,.01);assert.ok(lobber.lob);const countRocks=physicsEnemies.get().hazards.length;physicsEnemies.tickCatapult(lobber,prey,.5);assert.equal(physicsEnemies.get().hazards.length,countRocks);physicsEnemies.tickCatapult(lobber,prey,.5);const rock=physicsEnemies.get().hazards.find(p=>p.kind==='rock');assert.ok(rock&&rock.vy<0&&Math.abs(rock.vx)<100);assert.equal(rock.fuse,undefined);assert.equal(rock.amount,lobber.at*4);physicsEnemies.get().heroes.forEach(h=>{h.x=20;h.y=226});const rockVictim=physicsEnemies.get().heroes[0];rock.x=rockVictim.x;rock.y=rockVictim.y-13;rock.vx=rock.vy=0;const rockHP=rockVictim.hp;physicsEnemies.tickHazards(.001);assert.ok(rockVictim.hp<rockHP);assert.equal(physicsEnemies.get().blasts.length,0,'Rocks never explode');[spider,rolling,bat,lobber].forEach(physicsEnemies.drawEnemy);


const gems=harness(),gt=gems.t;gt.start();const gh=gt.get().heroes[0],baseStrength=gh.str,baseHealth=gh.maxHp;gh.hp=20;gt.setItem(0,'gem-ruby-1');assert.ok(gt.moveItem({type:'bag',index:0},{type:'rune0',index:0}));assert.equal(gh.str,baseStrength+5);assert.equal(gh.hp,20);gt.setItem(1,'gem-topaz-1');assert.ok(gt.moveItem({type:'bag',index:1},{type:'rune1',index:0}));assert.equal(gh.maxHp,baseHealth+20+50);assert.equal(gt.moveItem({type:'rune0',index:0},{type:'bag',index:2}),false);gt.moveItem({type:'gear',index:0},{type:'bag',index:2});assert.equal(gh.str,baseStrength);assert.equal(gh.maxHp,baseHealth);gt.save();const gemReload=harness(gems.storage).t;assert.equal(gemReload.get().inventoryRunes[2][0],'gem-ruby-1');gemReload.moveItem({type:'bag',index:2},{type:'gear',index:0});assert.equal(gemReload.get().heroes[0].str,baseStrength+5);
for(const family of ['ruby','emerald','sapphire','amethyst','diamond','topaz'])for(let tier=1;tier<=10;tier++){const item=gt.items['gem-'+family+'-'+tier];assert.equal(item.type,'gem');for(const [key,value] of Object.entries(gt.items['gem-'+family+'-1'].gemStats))assert.equal(item.gemStats[key],value*tier)}
gt.setParty([0,0,0,0]);const defender=gt.get().heroes[0];defender.runes=['gem-diamond-1','gem-amethyst-1'];gt.stats(defender);assert.equal(defender.defense,1);assert.equal(defender.str,2);assert.equal(defender.dex,2);assert.equal(defender.int,2);defender.hp=50;gt.damage(defender,10);assert.equal(defender.hp,41);
defender.runeBonus.xpBonus=0;for(const [diff,factor] of [[5,1],[6,.9],[10,.5],[14,.1],[15,0],[30,0]]){defender.level=1+diff;assert.ok(Math.abs(gt.xpGain(defender,100,1)-Math.max(1,100*factor))<1e-8)}defender.runeBonus.xpBonus=.2;defender.level=7;assert.equal(gt.xpGain(defender,100,1),108);defender.level=16;assert.equal(gt.xpGain(defender,100,1),1);
gt.setParty([0,0,0,0]);gt.get().heroes[0].level=7;gt.get().heroes[1].level=16;gt.xp(100,1);assert.equal(gt.get().heroes[0].xp,90);assert.equal(gt.get().heroes[1].xp,1);assert.equal(gt.get().heroes[2].xp,100);gt.setArea(4);assert.equal(gt.enemy('slime',300).level,9);


const control=harness(),cc=control.t;cc.start();cc.setParty([5,3,2,0]);cc.enter();const spear=cc.get().heroes[0];spear.weapon='5-ice';cc.stats(spear);const normal=cc.get().enemies[0];normal.hp=10000;cc.activate(spear,normal,'ice');assert.ok(normal.frozen<.4);const bossControl=cc.enemy('boss',normal.x+2);cc.get().enemies.push(bossControl);cc.activate(spear,bossControl,'ice');assert.ok(Math.abs(bossControl.frozen-cc.controlDuration(spear,.7)*.2)<1e-9);assert.ok(!(bossControl.slow>0));cc.activate(spear,bossControl,'slow');assert.equal(bossControl.slowAmount,.06);assert.equal(cc.slowFactor(bossControl),.94);cc.activate(spear,bossControl,'stun');assert.ok(Math.abs(bossControl.stun-cc.controlDuration(spear,.6)*.2)<1e-9);const mage=cc.get().heroes[1];mage.weapon='3-ice';mage.attributes.dex=0;cc.stats(mage);assert.ok(cc.controlDuration(mage,.7)>.6);
const bow=cc.get().heroes[2];bow.weapon='2-poison2';bow.attributes.int=2;cc.stats(bow);const volley=cc.attackToken(bow);cc.shoot(bow,normal,'arrow',1,volley);const arrows=cc.get().shots.filter(s=>s.attack===volley);assert.equal(arrows.length,2);arrows.forEach(s=>cc.basicHit(normal,1,s.attack));assert.equal(bow.mp,2,'Volley only charges once');assert.equal(cc.items['2-steel4'].arrows,4);
assert.equal(cc.WORLD.filter(n=>!n.kind).length,18);for(let i=0;i<18;i++){cc.setArea(i);cc.setStage(cc.stageCount()-1);cc.defeatBossAndAdvance();if(i<17)assert.ok(cc.unlockedNodes().has('a'+(i+1)))}cc.setArea(17);cc.save();assert.equal(harness(control.storage).t.get().area,17);const chart=control.elements.get('.map-chart');chart.scrollWidth=1800;chart.clientWidth=600;chart.scrollLeft=0;cc.setPan(1);cc.panMap(1);assert.equal(chart.scrollLeft,240);cc.panMap(20);assert.equal(chart.scrollLeft,1200);cc.setPan(-1);cc.panMap(20);assert.equal(chart.scrollLeft,0);


const freezeBefore=cc.controlDuration(mage,.7);mage.attributes.dex=100;mage.runes=['rune-haste','rune-haste'];cc.stats(mage);assert.ok(mage.cool<1);assert.equal(cc.controlDuration(mage,.7),freezeBefore,'Freeze uses base AGI, ignoring DEX and haste');
const shopLayout=harness(),sl=shopLayout.t;sl.start();for(let i=0;i<=6;i++){sl.setArea(i);sl.setStage(sl.stageCount()-1);sl.defeatBossAndAdvance()}sl.travel('town');const pages=sl.shopPages();assert.ok(pages.length>=2);for(const page of pages)assert.ok(page.items.every(w=>w.level===page.tier));const tierOne=pages.findIndex(p=>p.tier===1);sl.setShopPage(tierOne);sl.renderServices();for(const w of pages[tierOne].items)assert.ok(shopLayout.elements.get('#trader-stock').innerHTML.includes(w.name));sl.fitFullscreen();

const quiet=harness().t;quiet.start();const qh=quiet.get().heroes[0],qe=quiet.get().enemies[0];qe.hp=qe.maxHp=10000;quiet.activate(qh,qe,'fire');quiet.activate(qh,qe,'poison');const countNumbers=quiet.get().numbers.length,lpBefore=qe.hp;for(let i=0;i<100;i++)quiet.tickEffects(.01);assert.ok(qe.hp<lpBefore);assert.equal(quiet.get().numbers.length,countNumbers,'DoT damage creates no numbers');quiet.damage(qe,1);assert.equal(quiet.get().numbers.length,countNumbers+1);
quiet.setArea(0);quiet.setStage(1);quiet.enter();assert.ok(quiet.get().enemies.filter(e=>e.type==='swarmling').length>=6);assert.ok(pages[0].items.some(w=>w.id==='0-basic'));assert.ok(pages[0].items.some(w=>w.id==='0-iron'));assert.equal(pages[0].tier,1);
console.log('PASS: quiet DoTs, larger encounters, six-member swarms, displayed-tier shop grouping, base-AGI freeze invariant, tier pricing and grouped shop, speed-scaled CC, boss resistances, multiarrow proc guard, expanded map/save/panning, gem tiers/stats/permanent sockets/save migration, per-character low-level XP penalty, spider feet, roller inertia, flight physics, catapult rocks, six enemy archetypes, region rosters, hopper leap, limited shaman healing, automatic town recovery, live stacked-aura AT, shorter starter reach, slower bombs, revival costs/defeat recovery, brief dodgeable slashes, single bombs, short missiles, HP/price curves, slower XP, terrain collision, stepping, priest area damage, manual single-character stage exit, stopped cleared party, speed-sensitive dragging, enemy projectiles/dodging, telegraphs, bombs, homing turn limits, throw momentum, priest aura totals, permanent weapon sockets, 5–8 stages and bosses, hidden map nodes, gated shop stock,  map locks/branches, town healing, trader buy/sell, persistent HP, no level-up healing, 5% tactical potions, left-panel hover, and all combat/rune regressions.');

{const fresh=harness(),ft=fresh.t;ft.startTown();for(let c=0;c<8;c++){ft.setParty([c,c,c,c]);const h=ft.get().heroes[0];assert.equal(h.str,0);assert.equal(h.dex,0);assert.equal(h.int,0)}ft.setParty([4,0,0,0]);ft.select(0);assert.deepEqual(Array.from(ft.get().heroes[0].agi),[80,90]);assert.ok(Object.values(ft.items).filter(w=>w.classId===4).every(w=>w.agi[0]===80&&w.agi[1]===90));assert.equal(fresh.elements.get('[data-stat="lp"]').hidden,true);ft.get().heroes[0].sp=1;ft.select(0);assert.equal(fresh.elements.get('[data-stat="lp"]').hidden,false);fresh.elements.get('#world-button').onclick();assert.equal(ft.get().state,'service');const traveler=ft.get().heroes[0];traveler.x=552;traveler.y=100;ft.update(.01);assert.equal(ft.get().state,'service');traveler.y=226;ft.update(.01);assert.equal(ft.get().state,'map');console.log('Zero starting stats, slow Priest staves, HP button visibility, and town sign contact pass.');}
{
const run=harness(),r=run.t;r.start();assert.deepEqual(Array.from(r.classes,c=>c.name),['Warrior','Rogue','Ranger','Mage','Priest','Reaper','Bard','Summoner']);
r.setParty([5,0,1,6]);r.enter();const reaper=r.get().heroes[0];reaper.x=260;reaper.y=219;reaper.hp=20;reaper.attributes.dex=10;r.stats(reaper);
const foes=r.get().enemies;foes.forEach((e,i)=>{e.x=i<2?285:450;e.y=219;e.hp=100});reaper.strike={elapsed:0,left:.09,target:foes[0],amount:2,token:r.attackToken(reaper),range:reaper.range,face:1};for(let i=0;i<30;i++)r.resolveStrike(reaper,.01);
assert.equal(foes[0].hp,98);assert.equal(foes[1].hp,98);assert.equal(foes[2].hp,100);assert.equal(reaper.hp,30,'Reaper heals once per enemy per swing');
const rogue=r.get().heroes[2];rogue.x=275;rogue.y=219;rogue.strike={left:0,target:foes[0],amount:2,token:r.attackToken(rogue),range:14};r.resolveStrike(rogue,.01);assert.equal(foes[0].hp,96);assert.equal(foes[1].hp,98);
const bard=r.get().heroes[3];bard.x=250;bard.y=219;bard.attributes.str=10;bard.attributes.dex=10;r.stats(bard);reaper.x=275;foes[0].x=300;foes[1].x=325;r.shootNote(bard,foes[0],2,r.attackToken(bard));for(let i=0;i<50;i++)r.tickShots(.01);assert.equal(r.songTotal(reaper,'attack'),.1);assert.equal(r.aura(reaper).attack,1.1);assert.equal(foes[0].hp,94);assert.equal(foes[1].hp,96);reaper.songs={};assert.equal(r.aura(reaper).flat,0);
r.setParty([7,0,0,0]);r.enter();const summoner=r.get().heroes[0];summoner.weapon='7-poison';summoner.attributes.int=20;summoner.attributes.dex=10;r.stats(summoner);assert.ok(Math.abs(r.summonInterval(summoner)-2/1.4)<1e-8);for(let i=0;i<310;i++)r.tickMinions(.01);assert.equal(r.get().minions.length,2);assert.equal(r.get().minions[0].maxHp,36);const pet=r.get().minions[0],progress=summoner.summonProgress;r.damage(pet,100);r.tickMinions(.01);assert.ok(!r.get().minions.includes(pet));assert.ok(summoner.summonProgress>progress);const survivor=r.get().minions[0];survivor.life=.005;r.tickMinions(.01);assert.ok(!r.get().minions.includes(survivor));summoner.weapon='7-heavy';summoner.gearRevision++;r.stats(summoner);r.tickMinions(.4);assert.equal(r.get().minions.length,0);for(let i=0;i<400;i++)r.tickMinions(.01);assert.ok(r.get().minions.length>0);assert.ok(r.get().minions.every(m=>m.kind==='golem'));summoner.hp=0;r.tickMinions(.01);assert.equal(r.get().minions.length,0);r.draw();
console.log('New roster, swept Reaper collisions/healing, single-target Rogue, Bard piercing/buffs, and Summoner groups/health/respawn/equipment cleanup pass.');
}
{
const check=harness(),c=check.t;c.start();c.setParty([5,3,0,0]);c.enter();const h=c.get().heroes[0],target=c.get().enemies[0];target.hp=10000;h.weapon='5-ice';c.stats(h);c.inspect(h.weapon);assert.match(check.elements.get('#item-effect').textContent,/Freeze 0.37s/);c.activate(h,target,'ice');assert.ok(target.frozen>0);assert.ok(!(target.slow>0));c.tickEffects(1);assert.equal(c.slowFactor(target),1);h.weapon='5-slow';c.stats(h);c.inspect(h.weapon);assert.match(check.elements.get('#item-effect').textContent,/Slow 20% for 2s/);c.activate(h,target,'slow');assert.equal(target.frozen,0);assert.equal(target.slow,2);assert.equal(c.slowFactor(target),.8);c.inspect('3-ice');assert.match(check.elements.get('#item-effect').textContent,/Freeze 0.7s/);assert.equal(Object.values(c.items).filter(w=>w.effect==='slow').length,7);console.log('Separate freeze/slow weapons and exact weapon duration readouts pass.');
}
{
const h=harness(),b=h.t;b.start();b.setParty([6,6,6,0]);b.enter();const [one,two,three,warrior]=b.get().heroes,foe=b.get().enemies[0];
for(const bard of [one,two,three]){bard.attributes.str=10;bard.attributes.dex=20;b.stats(bard);b.applySong(warrior,bard);b.applySong(foe,bard);}
assert.equal(b.aura(warrior).attack,1.3);assert.ok(Math.abs(b.songTotal(warrior,'haste')-.6)<1e-9);assert.deepEqual(Array.from(b.effectiveAgi(warrior)),[13,19]);assert.equal(b.enemyDamage(foe),1);foe.at=50;assert.equal(b.enemyDamage(foe),35);
b.applySong(warrior,one);assert.equal(b.aura(warrior).attack,1.3);foe.hp=100;b.basicHit(foe,5,b.attackToken(warrior));assert.equal(foe.hp,80);b.damage(foe,5,'fire',false);assert.equal(foe.hp,75);
b.setTime(1.01);assert.equal(b.aura(warrior).flat,0);assert.equal(b.enemyDamage(foe),50);assert.deepEqual(Array.from(b.effectiveAgi(warrior)),[20,30]);
for(const [id,pattern,count] of [['6-basic','line',1],['6-iron','long',1],['6-ice','cone',3],['6-heavy','pulse',1]]){b.get().shots.length=0;one.weapon=id;b.stats(one);b.shootNote(one,foe,5,b.attackToken(one));assert.equal(b.items[id].note,pattern);assert.equal(b.get().shots.length,count);assert.ok(b.get().shots[0].life*(pattern==='pulse'?110:160)>Math.min(one.range,Math.hypot(foe.x-one.x,foe.y-one.y)));assert.deepEqual(Array.from(one.agi),[55,65]);}
one.weapon='6-fire';one.attributes.int=12;b.stats(one);one.mp=0;b.get().shots.length=0;b.basicHit(foe,1,b.attackToken(one));assert.equal(one.mp,0);assert.equal(b.get().shots.length,1);assert.ok(b.get().shots[0].attack.charged);
b.activate(one,foe,'sustain');b.shootNote(one,foe,1,b.attackToken(one));assert.equal(b.get().shots.at(-1).mod.duration,2);assert.equal(one.nextNote,null);
b.activate(one,foe,'crescendo');b.shootNote(one,foe,1,b.attackToken(one));assert.equal(b.get().shots.at(-1).mod.power,1.5);
b.get().shots.length=0;one.x=260;one.y=219;warrior.x=280;warrior.y=219;warrior.hp=20;foe.x=310;foe.y=219;one.weapon='6-heal';b.stats(one);b.activate(one,foe,'restore');b.shootNote(one,foe,1,b.attackToken(one));for(let i=0;i<40;i++)b.tickShots(.01);assert.equal(warrior.hp,32,'Harp heals ally once across all three notes');assert.equal(b.songTotal(warrior,'attack'),.1);
b.draw();console.log('Bard stacks, expiry, haste, flat enemy modifiers, four instrument patterns, range extension, musical abilities and no recursive Encore pass.');
}
{
const r=harness().t;r.start();for(let region=0;region<6;region++)for(let other=region+1;other<6;other++)assert.ok(r.REGIONAL_POOLS[region].every(id=>!r.REGIONAL_POOLS[other].includes(id)),'Regions have exclusive species');
assert.equal(new Set(r.REGION_BOSSES.map(b=>b[0])).size,18);
for(let area=0;area<18;area++){r.setArea(area);r.setStage(1);r.enter();for(let i=0;i<120;i++)r.update(.01);for(const e of r.get().enemies){assert.ok(Number.isFinite(e.x)&&Number.isFinite(e.y)&&Number.isFinite(e.hp));r.drawEnemy(e)}}
r.setParty([1,1,0,4]);r.setArea(0);r.enter();const rogue=r.get().heroes[0];r.attackMotion(rogue);assert.equal(rogue.attackHand,0);assert.equal(rogue.daggerArms[0].velocity,38);assert.equal(rogue.daggerArms[1].velocity,0);r.tickRogueArms(rogue,.02);const poses=r.rogueHands(rogue,[0,-18],1,0);assert.notDeepEqual(poses[0].hand,poses[1].hand);r.attackMotion(rogue);assert.equal(rogue.attackHand,1);assert.equal(rogue.daggerArms[1].velocity,38);r.draw();console.log('Exclusive regional species, 18 named guardians, regional movement/rendering, and independently animated alternating Rogue hands pass.');
}
{
const r=harness().t;r.start();const h=r.get().heroes[0];const originalXP=h.xp,gold=r.get().gold;assert.ok(r.get().enemies.some(e=>e.hp>0));h.x=554;h.y=226;r.update(.001);assert.equal(r.get().stage,1);assert.equal(h.xp,originalXP);assert.equal(r.get().gold,gold);assert.equal(r.get().loot.length,0);assert.equal(h.x,32);
r.setStage(r.stageCount()-1);r.enter();assert.equal(r.stageExitOpen(),false);r.completeArea();assert.equal(r.get().state,'fight');h.x=554;h.y=226;r.update(.001);assert.equal(r.get().state,'fight');assert.ok(!r.get().completed.includes('a0'));r.get().enemies.find(e=>e.type==='boss').hp=0;assert.ok(r.get().enemies.some(e=>e.hp>0));assert.equal(r.stageExitOpen(),false);r.tickBossExit(1.99);assert.equal(r.stageExitOpen(),false);r.tickBossExit(.01);assert.equal(r.stageExitOpen(),true);h.x=554;h.y=226;r.update(.001);assert.equal(r.get().state,'map');assert.ok(r.get().completed.includes('a0'));console.log('Regular stages can be skipped without rewards; live bosses block progression; surviving regular mobs do not block a defeated boss exit.');
}
{
const check=harness(),c=check.t;c.start();const foe=c.enemy('slime',300),table=Array.from(c.weaponDropTable(foe));assert.ok(table.length>=1&&table.length<=2);c.setParty([7,7,7,7]);assert.deepEqual(Array.from(c.weaponDropTable(foe)),table);const covered=new Set();for(const items of Object.values(c.WEAPON_DROPS)){assert.ok(items.length>=1&&items.length<=2);items.forEach(id=>{assert.equal(c.items[id].type,'weapon');covered.add(id)})}assert.ok(Object.values(c.items).filter(w=>w.type==='weapon'&&w.tier>0).every(w=>covered.has(w.id)));
assert.equal(c.items['rune-leech'].type,'soul');assert.equal(c.items['rune-leech'].bonuses.lifesteal,.02);assert.equal(c.items['rune-wisdom'].bonuses.xpBonus,.1);assert.equal(c.items['soul-fortune-1'].bonuses.dropBonus,.05);
c.setItem(0,'soul-fortune-1');assert.ok(c.moveItem({type:'bag',index:0},{type:'rune0',index:0}));assert.equal(c.dropMultiplier(),1.05);c.save();assert.ok(c.load());assert.equal(c.get().heroes[0].runes[0],'soul-fortune-1');assert.equal(c.dropMultiplier(),1.05);c.inspect('soul-fortune-1');assert.match(check.elements.get('#item-details').textContent,/Soul/);assert.equal(c.moveItem({type:'rune0',index:0},{type:'bag',index:1}),false);
c.get().heroes[0].hp=0;assert.equal(c.dropMultiplier(),1);check.math.random=()=>0;const boss=c.enemy('boss',300);const both=c.rollDrops(boss);assert.deepEqual(Array.from(both,id=>c.items[id].type),['weapon','rune','soul']);c.setArea(17);const late=c.rollDrops(c.enemy('boss',300));assert.equal(c.items[late.find(id=>c.items[id].type==='soul')].tier,5);
console.log('Fixed monster tables, all weapon coverage, independent boss rolls, Souls, save/socket support, and equipment drop bonuses pass.');
}
{
const run=harness(),r=run.t;r.start();run.math.random=()=>.15;r.damage(r.enemy('swarmling',300),99999);assert.equal(r.get().potions.length,0);run.math.random=()=>.14999;r.damage(r.enemy('glowleech',300),99999);assert.equal(r.get().potions.length,1);run.math.random=()=>.29;r.damage(r.enemy('slime',300),99999);assert.equal(r.get().potions.length,2);
r.get().potions.length=0;r.get().heroes.forEach(h=>{h.x=300;h.y=219;h.hp=h.maxHp});r.setPotion({x:300,y:219});r.pickPotions();assert.equal(r.get().potions.length,1,'Full-health party leaves potion untouched');const wounded=r.get().heroes[2];wounded.hp=1;r.pickPotions();assert.equal(r.get().potions.length,0);assert.equal(wounded.hp,1+Math.ceil(wounded.maxHp*.2),'Wounded hero can collect beside full-health allies');console.log('Swarm potion rate and full-health pickup exclusion pass.');
}
{
const test=harness(),t=test.t;t.start();const h=t.get().heroes[0];t.get().loot.length=0;t.setLoot({x:300,y:219,item:'0-iron'});h.x=300;h.y=170;t.pickLoot();assert.equal(t.get().loot.length,1);h.y=219;t.setHeld(h);t.pickLoot();assert.equal(t.get().loot.length,0);assert.equal(t.get().inventory[0],'0-iron');h.hp=1;t.setPotion({x:300,y:219});t.pickPotions();assert.equal(t.get().potions.length,0);assert.equal(h.hp,1+Math.ceil(h.maxHp*.2));for(let i=0;i<15;i++)t.setItem(i,'0-basic');t.setLoot({x:300,y:219,item:'0-fire'});const gold=t.get().gold;t.pickLoot();assert.equal(t.get().loot.length,1);assert.equal(t.get().gold,gold);t.setHeld(null);
const stage=t.get().stage;t.raw_completeArea();assert.equal(t.get().stage,stage);t.tickSceneFade(.49);assert.equal(t.get().stage,stage);t.tickSceneFade(.01);assert.equal(t.get().stage,stage+1);assert.equal(test.elements.get('#scene-fade').style.opacity,'1');assert.ok(t.get().sceneFade);const before=t.get().time;t.rawUpdate(.1);assert.ok(t.get().time>before);t.tickSceneFade(.5);assert.equal(t.get().sceneFade,null);assert.equal(test.elements.get('#scene-fade').hidden,true);
t.raw_travel('town');t.tickSceneFade(.49);assert.notEqual(t.get().currentNode,'town');t.tickSceneFade(.01);assert.equal(t.get().currentNode,'town');t.tickSceneFade(.5);assert.equal(t.get().sceneFade,null);
console.log('Physical ground pickups while held, full-bag preservation, and one-second midpoint scene transitions pass.');
}
{
const test=harness(),r=test.t;r.start();const h=r.get().heroes[0];r.setAutoMove(0,false);assert.equal(r.canAutoMove(h),false);for(let i=0;i<50;i++)r.rawUpdate(.01);assert.equal(h.x,32);assert.ok(r.get().heroes[1].x>52);r.setAutoMove(null,false);assert.ok(r.get().heroes.every(h=>!r.canAutoMove(h)));r.setAutoMove(null,true);assert.equal(r.canAutoMove(h),false);assert.equal(r.canAutoMove(r.get().heroes[1]),true);r.save();assert.ok(r.load());assert.equal(r.canAutoMove(r.get().heroes[0]),false);r.openSettings();const t=r.get().time;r.rawUpdate(.1);assert.equal(r.get().time,t);r.closeSettings();r.rawUpdate(.01);assert.ok(r.get().time>t);
r.get().numbers.length=0;r.float(100,100,12);const n=r.get().numbers[0];assert.ok(Math.abs(n.vx)>=9&&Math.abs(n.vx)<=16);r.tickNumbers(.01);assert.ok(n.y<100&&n.x!==100);assert.ok(n.x!==Math.round(n.x));for(let i=0;i<90;i++)r.tickNumbers(.01);assert.ok(n.vy>0);r.tickNumbers(.2);assert.equal(r.get().numbers.length,0);r.draw();console.log('Saved per-character/master auto movement, settings pause, and smooth ballistic damage numbers pass.');
}
const saves=harness(),sv=saves.t;sv.startTown();sv.setGold(777);sv.save();sv.openMainMenu();assert.equal(sv.get().menuOpen,true);const frozenTime=sv.get().time;sv.rawUpdate(1);assert.equal(sv.get().time,frozenTime);sv.chooseSaveSlot(2);sv.startTown();sv.setGold(222);sv.save();assert.equal(sv.readSlot(1).gold,777);assert.equal(sv.readSlot(2).gold,222);sv.openMainMenu();sv.chooseSaveSlot(1);assert.equal(sv.get().gold,777);sv.openMainMenu();sv.chooseSaveSlot(3);sv.openMainMenu();assert.equal(sv.readSlot(3),null);assert.equal(sv.readSlot(1).gold,777);
assert.equal(sv.buyPrice(sv.items['gem-ruby-1']),500);assert.equal(sv.buyPrice(sv.items['gem-ruby-3']),1500);assert.equal(sv.buyPrice(sv.items['rune-ward']),1000);
assert.equal(new Set(Object.values(sv.items).filter(i=>i.type==='rune').map(sv.itemSymbol)).size,6);
const mh=sv.get().heroes[0];mh.weapon='0-fire';mh.mp=5;assert.equal(sv.manaPercent(mh),50);
console.log('Independent save slots, menu pause, socket prices, distinct rune icons and mana bars pass.');
const tuning=harness(),tu=tuning.t;tu.start();assert.equal(tu.needed(10),3600);assert.equal(tu.needed(20),12100);
const hurt=tu.get().heroes[0];tu.damage(hurt,5);assert.equal(tu.get().numbers.at(-1).color,'#ff4545');tu.damage(tu.get().enemies[0],1);assert.equal(tu.get().numbers.at(-1).color,'#fff');
for(let a=0;a<18;a++){tu.setArea(a);for(let i=0;i<1000;i++)for(const id of tu.rollDrops(tu.enemy('boss',300))){const w=tu.items[id];if(w.type!=='weapon')assert.ok(w.tier<=Math.max(1,Math.floor(a/3)),'Socket drop exceeds region tier in area '+a)}}
tu.setArea(0);const heldBase={...hurt,x:100,y:100,vx:0,vy:0,dragTarget:{x:400,y:100},swing:0,lean:0};const medium={...heldBase,cursorSpeed:800},fast={...heldBase,cursorSpeed:2400};tu.stepHeld(medium,1/120);tu.stepHeld(fast,1/120);assert.ok(fast.vx>medium.vx*2);
console.log('Steeper XP curve, fast drag response, red incoming damage and regional socket-drop caps pass.');
const icons=harness().t;for(const w of Object.values(icons.items))icons.drawItemIcon(context,w);
console.log('Timed individual summons, INT casting speed, death-independent cycle, expiry, weapon cleanup and shared item drawing pass.');
