const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const noop=()=>{},context=new Proxy({},{get:()=>noop,set:()=>true});
function harness(saved={}){
 const events={};const elements=new Map(),choices=[0,2,3,4].map(value=>({value:String(value)}));
 const element=()=>({style:{},classList:{add:noop,remove:noop},hidden:false,textContent:'',innerHTML:'',addEventListener:noop,setAttribute:noop,getContext:()=>context});
 const document={querySelector(s){if(!elements.has(s))elements.set(s,element());return elements.get(s)},querySelectorAll(s){return s==='#choices select'?choices:[]}};
 let seed=13;const math=Object.create(Math);math.random=()=>((seed=(seed*1664525+1013904223)>>>0)/4294967296);
 const storage={...saved};const sandbox={document,Math:math,window:{addEventListener:(name,fn)=>events[name]=fn},localStorage:{getItem:k=>storage[k]||null,setItem:(k,v)=>storage[k]=v},requestAnimationFrame:noop,setTimeout:noop,console};
 vm.runInNewContext(fs.readFileSync(__dirname+'/gear.js','utf8'),sandbox);
 const src=fs.readFileSync(__dirname+'/game.js','utf8').replace(/\}\)\(\);\s*$/,`globalThis.test={start:()=>{start();enter()},startTown:start,revivalCost,revive,tickSlash,attackMotion,needed,areaHealth,weaponPrice,buyPrice,aura,terrainHit,tickShots,moveEnemy,innCost,stepHeld,grounded,launchHazard,tickHazards,tickSpecial,moveHeld,release,setHeld:h=>drag=h,stageCount,shopStock,setStage:n=>stage=n,clearRegion:()=>{for(let i=stage;i<stageCount();){completeArea();if(state==='map')break}},openMap,travel,completeArea,healTown,sellItem,buyRune,pickPotions,unlockedNodes,inspect,inspectHero,restoreInfo,update,damage,xp,equip,enter,load,save,stats,allocate,select,moveItem,attackToken,basicHit,activate,tickEffects,enemy,shoot,rollDrop,stepBody,resolveStrike,frame,toggle,get:()=>({heroes,enemies,hazards,blasts,area,stage,state,inventory,inventoryRunes,fields,shots,loot,paused,time,completed,potions,currentNode,selected,hoverHero,inspectingItem,gold}),setPotion:p=>potions.push(p),setGold:n=>gold=n,setPicked:s=>pickedSlot=s,setGearDrag:v=>gearDrag=v,setArea:n=>area=n,setItem:(i,id)=>inventory[i]=id,setParty:ids=>heroes=ids.map(hero),items:ITEMS,effects:EFFECTS};})();`);
 vm.runInNewContext(src,sandbox);return {t:sandbox.test,storage,choices,math,events,elements};
}
const {t,storage,choices}=harness();
choices.forEach(c=>c.value='1');t.start();assert.ok(t.get().heroes.every(h=>h.classId===1));
assert.equal(t.get().enemies.length,4);for(let i=0;i<100;i++)t.update(.02);assert.equal(t.get().enemies.length,4,'No timed spawning');
t.xp(190);assert.ok(t.get().heroes.every(h=>h.level===2&&h.sp===2));t.select(0);assert.ok(t.allocate('int'));assert.equal(t.get().heroes[0].int,1);assert.ok(t.allocate('dex'));assert.equal(t.allocate('int'),false,'Cannot spend without SP');
t.xp(300);assert.ok(t.allocate('int'));let h=t.get().heroes[0];assert.equal(h.int,2);
t.setItem(0,'1-fire');assert.ok(t.equip(0));assert.equal(h.weapon,'1-fire');assert.equal(t.get().inventory[0],'1-basic','Equipping swaps original into inventory');
let victim=t.get().enemies[0];victim.hp=victim.maxHp=10000;
for(let i=1;i<=4;i++){t.basicHit(victim,1,t.attackToken(h));assert.equal(h.mp,i*2);assert.equal(t.get().fields.length,0)}
t.basicHit(victim,1,t.attackToken(h));assert.equal(h.mp,0);assert.equal(t.get().fields.length,1,'2 INT / 10 MP fires on fifth landed hit');
t.tickEffects(.05);assert.equal(h.mp,0,'Ability damage does not generate MP');
const token=t.attackToken(h);t.basicHit(victim,1,token);t.basicHit(victim,1,token);assert.equal(h.mp,2,'Multiple targets charge only once per basic attack');
const inFlight=t.attackToken(h);assert.ok(t.moveItem({type:'gear',index:0},{type:'bag',index:3}));assert.equal(h.weapon,null);assert.equal(h.mp,0);t.basicHit(victim,1,inFlight);assert.equal(h.mp,0,'Old projectile cannot charge new equipment');assert.equal(t.get().inventory[3],'1-fire');
assert.ok(t.moveItem({type:'bag',index:3},{type:'gear',index:0}));assert.equal(h.weapon,'1-fire');assert.equal(t.get().inventory[3],null);
t.setItem(4,'2-poison');assert.equal(t.moveItem({type:'bag',index:4},{type:'gear',index:0}),false,'Wrong class rejected atomically');assert.equal(t.get().inventory[4],'2-poison');assert.equal(h.weapon,'1-fire');
t.setItem(5,'1-steel');assert.ok(t.equip(5));assert.equal(h.weapon,'1-steel');t.setItem(6,'1-ice');assert.ok(t.moveItem({type:'bag',index:6},{type:'bag',index:5}));assert.equal(t.get().inventory[5],'1-ice');
// Class-specific stat effects.
for(let c=0;c<8;c++){t.setParty([c,c,c,c]);const p=t.get().heroes[0];const before={max:p.atMax,min:p.atMin,range:p.range,agi:p.agi[0]};p.attributes.str++;t.stats(p);if(c===0)assert.equal(p.atMax,before.max+1);if(c===2||c===3)assert.equal(p.range,before.range+2);p.attributes.int=2;t.stats(p);assert.equal(p.int,2)}
assert.ok(t.items['0-heavy'].max>t.items['0-lightning'].max,'Physical sword can outdamage elemental sword');
// Freeze/slow, poison, lightning, heal, drain, stun all execute actual gameplay effects.
t.setParty([0,2,3,4]);t.setArea(0);t.enter();h=t.get().heroes[0];victim=t.get().enemies[0];victim.hp=victim.maxHp=10000;t.activate(h,victim,'ice');assert.ok(victim.frozen>0);t.tickEffects(.8);assert.equal(victim.frozen,0);assert.ok(victim.slow>0);
t.activate(h,victim,'poison');const beforePoison=victim.hp;t.tickEffects(1);assert.ok(victim.hp<beforePoison);const hp=victim.hp;t.activate(h,victim,'lightning');assert.ok(victim.hp<hp);h.hp=10;t.activate(h,victim,'heal');assert.ok(h.hp>10);const beforeDrain=h.hp;t.activate(h,victim,'drain');assert.ok(h.hp>beforeDrain);t.activate(h,victim,'stun');assert.ok(victim.stun>0);
// Killing hit still charges. No charge for attacks on already dead targets.
h.weapon='0-fire';h.attributes.int=2;t.stats(h);h.mp=0;victim.hp=1;t.basicHit(victim,10,t.attackToken(h));assert.equal(h.mp,2);t.basicHit(victim,10,t.attackToken(h));assert.equal(h.mp,2);
t.get().enemies.slice().forEach(e=>t.damage(e,99999));t.update(.01);assert.equal(t.get().state,'walk');assert.equal(t.get().area,0);const stopped=t.get().heroes.map(h=>h.x);for(let i=0;i<100;i++)t.update(.02);assert.equal(t.get().stage,0);t.get().heroes.forEach((h,i)=>assert.ok(Math.abs(h.x-stopped[i])<2,'Cleared party stays in place'));const exitHero=t.get().heroes[0];exitHero.x=490;exitHero.y=100;t.update(.01);assert.equal(t.get().stage,0,'Flying above sign does not advance');exitHero.y=226;exitHero.vy=0;t.update(.01);assert.equal(t.get().stage,1,'Only one hero must touch sign');assert.ok(!t.get().completed.includes('a0'));
t.setArea(4);t.enter();const summoner=t.get().enemies.find(e=>e.type==='summoner');const count=t.get().enemies.length;summoner.summon=0;t.update(.01);assert.equal(t.get().enemies.length,count+1);
t.get().heroes.forEach(h=>h.hp=0);t.update(.01);assert.equal(t.get().state,'service');assert.equal(t.get().currentNode,'town');assert.ok(t.get().heroes.every(h=>h.hp===Math.ceil(h.maxHp*.05)));
// Opening party still wins and earns unspent points without automatic spending.
t.setArea(0);t.setParty([0,2,3,4]);t.enter();for(let i=0;i<20000&&t.get().state!=='map'&&t.get().state!=='lost';i++)t.update(.02);assert.ok(t.get().stage>0);assert.ok(t.get().heroes.every(h=>h.int===0));
t.xp(t.needed(t.get().heroes[0].level));t.select(0);t.allocate('int');t.setItem(0,'0-fire');t.equip(0);t.get().heroes[0].mp=3;t.save();const reloaded=harness(storage).t.get();assert.equal(reloaded.heroes[0].weapon,'0-fire');assert.equal(reloaded.heroes[0].int,1);assert.equal(reloaded.heroes[0].mp,3);assert.equal(reloaded.inventory.length,15);
const old={area:3,gold:99,inventory:[1,2],heroes:[0,2,3,4].map(classId=>({classId,level:5,xp:2,weapon:2}))};const migrated=harness({'bramblebound-v2':JSON.stringify(old)}).t.get();assert.equal(migrated.heroes[0].sp,8);assert.equal(migrated.heroes[0].weapon,'0-iron');assert.equal(migrated.area,3);

// No charging with zero INT; minimum level restrictions leave both slots intact.
const isolated=harness().t;isolated.start();let fighter=isolated.get().heroes[0];isolated.setItem(0,'0-steel');assert.equal(isolated.equip(0),false);assert.equal(fighter.weapon,'0-basic');assert.equal(isolated.get().inventory[0],'0-steel');
isolated.setItem(1,'0-fire');isolated.equip(1);let dummy=isolated.get().enemies[0];dummy.hp=dummy.maxHp=10000;isolated.basicHit(dummy,1,isolated.attackToken(fighter));assert.equal(fighter.mp,0);
// Ten fire pulses regardless of coarse simulation steps, without proc recursion.
isolated.activate(fighter,dummy,'fire');let field=isolated.get().fields[0];const fireStart=dummy.hp,fireAmount=field.amount;for(let i=0;i<11;i++)isolated.tickEffects(.1);assert.equal(dummy.hp,fireStart-fireAmount*10);assert.equal(fighter.mp,0);assert.equal(isolated.get().fields.length,0);
// A launched projectile earns nothing until it actually lands.
fighter.attributes.int=2;isolated.stats(fighter);dummy.x=fighter.x+100;dummy.y=fighter.y;isolated.get().heroes.forEach(h=>h.cooldown=10);isolated.get().enemies.forEach(e=>e.cooldown=10);isolated.shoot(fighter,dummy,'arrow',1,isolated.attackToken(fighter));isolated.update(.01);assert.equal(fighter.mp,0);for(let i=0;i<80;i++)isolated.tickShots(.01);assert.equal(fighter.mp,2);
// Cancelling an attack because the victim was already dead yields no MP.
const discarded=isolated.attackToken(fighter);dummy.hp=0;isolated.shoot(fighter,dummy,'arrow',1,discarded);isolated.update(.01);assert.equal(fighter.mp,2);
// Continuous simulation while dragging equipment or changing focus; manual pause still works.
const motion=harness();motion.t.start();motion.t.setGearDrag({from:{type:'bag',index:0},moved:false});motion.t.frame(16);assert.ok(motion.t.get().time>0,'Equipment dragging must not pause');motion.events.blur();assert.equal(motion.t.get().paused,false);const elapsed=motion.t.get().time;motion.t.frame(32);assert.ok(motion.t.get().time>elapsed);motion.t.toggle();motion.events.blur();motion.t.frame(48);assert.equal(motion.t.get().paused,true);assert.equal(motion.t.get().time,elapsed+.016);motion.t.toggle();
const body=motion.t.get().heroes[0];body.drive=33;body.vx=0;const beforeX=body.x;motion.t.stepBody(body,1/60);assert.ok(body.vx>0&&body.vx<33);assert.ok(body.x>beforeX);const momentum=body.vx;motion.t.stepBody(body,1/60);assert.ok(body.vx>0&&body.vx<momentum,'Coasting decelerates instead of snapping');body.y=70;body.vy=0;for(let i=0;i<240;i++)motion.t.stepBody(body,1/120);assert.ok(body.y>=200&&body.y<=226);assert.ok(Number.isFinite(body.lean));
const meleeTarget=motion.t.get().enemies[0];meleeTarget.x=body.x+10;meleeTarget.y=body.y;const health=meleeTarget.hp;body.strike={left:.09,target:meleeTarget,amount:3,token:motion.t.attackToken(body),range:30};motion.t.resolveStrike(body,.04);assert.equal(meleeTarget.hp,health,'Swing windup deals no immediate damage');motion.t.resolveStrike(body,.06);assert.equal(meleeTarget.hp,health-3);assert.ok(meleeTarget.kick>0);body.strike={left:.09,target:meleeTarget,amount:3,token:motion.t.attackToken(body),range:30};meleeTarget.x+=100;motion.t.resolveStrike(body,.1);assert.equal(meleeTarget.hp,health-3,'Out-of-range melee attack misses');
// Exact drop boundary, no guaranteed final kill, and both item categories.
const drops=harness();drops.t.start();drops.math.random=()=>.02;assert.equal(drops.t.rollDrop(),null);
drops.t.get().enemies.forEach(e=>drops.t.damage(e,9999));assert.equal(drops.t.get().loot.length,0,'Last enemy has no guaranteed drop');
let randoms=[.01999,.1,.1,.1];drops.math.random=()=>randoms.shift()??.9;assert.equal(drops.t.items[drops.t.rollDrop()].type,'rune');
randoms=[.01999,.9,.1,.1];assert.equal(drops.t.items[drops.t.rollDrop()].type,'weapon');
const sample=harness();let countDrops=0,runeDrops=0;for(let i=0;i<100000;i++){const id=sample.t.rollDrop();if(id){countDrops++;if(sample.t.items[id].type==='rune')runeDrops++}}assert.ok(countDrops>1800&&countDrops<2200);assert.ok(runeDrops/countDrops>.45&&runeDrops/countDrops<.55);
// Two independent rune slots, swaps, and item-type rejection.
const run=harness(),rt=run.t;rt.start();const rh=rt.get().heroes[0];rt.setItem(0,'rune-leech');assert.ok(rt.moveItem({type:'bag',index:0},{type:'rune0',index:0}));rt.setItem(1,'rune-ward');assert.ok(rt.moveItem({type:'bag',index:1},{type:'rune1',index:0}));assert.equal(rh.runes.length,2);
assert.equal(rt.moveItem({type:'rune0',index:0},{type:'gear',index:0}),false);assert.equal(rt.moveItem({type:'gear',index:0},{type:'rune1',index:0}),false);
rh.hp=20;const target=rt.get().enemies[0];target.hp=5;rt.basicHit(target,100,rt.attackToken(rh));assert.equal(rh.hp,20.4,'Lifesteal uses actual damage, not overkill');
rt.setParty([0,0,0,0]);const q=rt.get().heroes[0];q.runes=['rune-ward','rune-ward'];rt.stats(q);q.hp=100;rt.damage(q,20,'poison');assert.equal(q.hp,90);rt.damage(q,20);assert.equal(q.hp,70,'Ward does not reduce physical damage');
q.runes=['rune-wisdom',null];rt.stats(q);rt.xp(10);assert.equal(q.xp,12);assert.equal(rt.get().heroes[1].xp,10);
q.runes=[null,null];rt.stats(q);const baseAgi=q.agi[0],baseAt=q.atMax,baseRange=q.range,baseHp=q.maxHp;
q.runes=['rune-haste','rune-might'];rt.stats(q);assert.ok(q.agi[0]<baseAgi);assert.ok(q.atMax>baseAt);
q.runes=['rune-reach','rune-vitality'];rt.stats(q);assert.equal(q.range,baseRange+15);assert.equal(q.maxHp,Math.floor(baseHp*1.2));
q.runes=['rune-renewal',null];rt.stats(q);q.hp=20;rt.update(.5);assert.equal(q.hp,20.5);
assert.equal(rt.moveItem({type:'rune0',index:0},{type:'bag',index:4}),false);assert.equal(q.runes[0],'rune-renewal');assert.equal(rt.get().inventory[4],null);
rt.setItem(5,'rune-reach');rt.moveItem({type:'bag',index:5},{type:'rune1',index:0});rt.save();const restored=harness(run.storage).t.get();assert.equal(restored.heroes[0].runes[1],'rune-reach');assert.equal(restored.inventory[4],null);
const legacy={version:3,area:0,gold:0,inventory:[],heroes:[0,2,3,4].map(classId=>({classId,level:5,xp:0,weapon:classId+'-fire',attributes:{str:1,dex:1,int:2}}))};
const upgraded=harness({'bramblebound-v3':JSON.stringify(legacy)});assert.equal(upgraded.t.get().heroes[0].sp,4);upgraded.t.save();assert.equal(harness(upgraded.storage).t.get().heroes[0].sp,4,'SP top-up does not repeat on reload');
// Town starts the journey; paths unlock on completion, including the trader detour.
const world=harness(),wt=world.t;wt.startTown();assert.equal(wt.get().state,'service');assert.equal(wt.get().currentNode,'town');assert.equal(wt.travel('a3'),false);assert.equal(wt.travel('trader'),false);
const wh=wt.get().heroes[0];wh.hp=17;wt.xp(190);assert.equal(wh.hp,17,'Leveling never heals');wt.allocate('str');assert.equal(wh.hp,17,'Spending LP-increasing stats never heals');assert.ok(wt.travel('a0'));assert.equal(wh.hp,17);wt.clearRegion();assert.ok(wt.unlockedNodes().has('a1'));assert.ok(!wt.unlockedNodes().has('a2'));assert.ok(wt.travel('a1'));assert.equal(wh.hp,17);wt.clearRegion();wt.travel('a2');wt.clearRegion();assert.ok(wt.unlockedNodes().has('a3'));assert.ok(wt.unlockedNodes().has('trader'));assert.equal(wh.hp,17);
wt.travel('trader');assert.equal(wt.healTown(),false);wt.setGold(100);assert.ok(wt.buyRune('rune-leech'));assert.equal(wt.get().gold,20);assert.equal(wt.buyRune('rune-ward'),false);wt.setPicked({type:'bag',index:0});assert.ok(wt.sellItem());assert.equal(wt.get().inventory[0],null);assert.equal(wt.get().gold,45);assert.equal(wt.sellItem(),false);
wt.travel('town');assert.equal(wh.hp,17,'Visiting town alone does not heal');wt.get().heroes[1].hp=0;wt.healTown();assert.equal(wh.hp,wh.maxHp);assert.equal(wt.get().heroes[1].hp,wt.get().heroes[1].maxHp);
wh.hp=19;wt.get().heroes[1].hp=0;wt.save();const healthReload=harness(world.storage).t;assert.equal(healthReload.get().heroes[0].hp,19);assert.equal(healthReload.get().heroes[1].hp,0);assert.ok(healthReload.unlockedNodes().has('trader'));
// Five-percent potions are independent from item drops and heal only the grounded collector.
const pot=harness(),pt=pot.t;pt.start();pot.math.random=()=>.05;pt.damage(pt.get().enemies[0],9999);assert.equal(pt.get().potions.length,0);pot.math.random=()=>.04999;pt.damage(pt.get().enemies[1],9999);assert.equal(pt.get().potions.length,1);assert.equal(pt.get().loot.length,0);const potion=pt.get().potions[0];pt.get().heroes.forEach((h,i)=>{h.hp=10;h.x=20+i*10;h.y=226});const collector=pt.get().heroes[2];collector.x=potion.x;collector.y=potion.y-30;pt.pickPotions();assert.equal(pt.get().potions.length,1,'Airborne heroes cannot consume ground potions');collector.y=potion.y;pt.pickPotions();assert.equal(pt.get().potions.length,0);assert.equal(collector.hp,10+Math.ceil(collector.maxHp*.3));assert.equal(pt.get().heroes[0].hp,10);assert.equal(pt.get().heroes[1].hp,10);assert.equal(pt.get().heroes[3].hp,10);
pt.setPotion({x:collector.x,y:collector.y});collector.hp=collector.maxHp-1;pt.pickPotions();assert.equal(collector.hp,collector.maxHp);pt.setPotion({x:collector.x,y:collector.y});collector.hp=0;pt.pickPotions();assert.equal(pt.get().potions.length,1,'Potion cannot revive a corpse');
// Hovering uses the left panel and does not change selection.
wt.inspect('0-fire');assert.equal(world.elements.get('#hover-info').hidden,false);assert.equal(world.elements.get('#character-info').hidden,true);wt.inspectHero(2);assert.equal(wt.get().selected,0);assert.equal(world.elements.get('#class-name').textContent,'Mage');wt.restoreInfo();assert.equal(world.elements.get('#hover-info').hidden,true);

// Bound sockets follow individual weapon copies through swaps and saves.
const bind=harness(),bt=bind.t;bt.start();bt.setItem(0,'rune-might');assert.ok(bt.moveItem({type:'bag',index:0},{type:'rune0',index:0}));bt.setItem(1,'rune-reach');assert.equal(bt.moveItem({type:'bag',index:1},{type:'rune0',index:0}),false);
bt.setItem(2,'0-basic');assert.ok(bt.moveItem({type:'bag',index:2},{type:'gear',index:0}));assert.equal(bt.get().heroes[0].runes[0],null);assert.equal(bt.get().inventoryRunes[2][0],'rune-might');bt.save();const br=harness(bind.storage).t;assert.equal(br.get().inventoryRunes[2][0],'rune-might');assert.ok(br.moveItem({type:'bag',index:2},{type:'gear',index:0}));assert.equal(br.get().heroes[0].runes[0],'rune-might');
const stages=harness(),st=stages.t;st.start();for(let a=0;a<9;a++){st.setArea(a);assert.ok(st.stageCount()>=5&&st.stageCount()<=8);st.setStage(0);st.enter();assert.ok(!st.get().enemies.some(e=>e.type==='boss'));st.setStage(st.stageCount()-1);st.enter();assert.equal(st.get().enemies.filter(e=>e.type==='boss').length,1)}
const sh=harness(),shp=sh.t;shp.startTown();assert.ok(shp.shopStock().every(w=>w.tier===0));shp.openMap();assert.ok(!sh.elements.get('#map-nodes').innerHTML.includes('Woodland'));shp.travel('a0');shp.clearRegion();shp.travel('town');assert.ok(shp.shopStock().every(w=>w.tier===0));shp.setGold(1000);assert.equal(shp.buyRune('0-steel'),false);

// Enemy attacks have physical trajectories; a missed target is not damaged.
const combat=harness(),ct=combat.t;ct.start();const ch=ct.get().heroes[0];ct.get().heroes.forEach((h,i)=>{h.x=90+i*25;h.y=226;h.hp=h.maxHp});
const shooter=ct.enemy('spitter',300);let projectile=ct.launchHazard(shooter,ch,'bullet',0,30);const originalAngle=Math.atan2(projectile.vy,projectile.vx);ch.y=100;const dodgeHp=ch.hp;for(let i=0;i<100;i++)ct.tickHazards(.01);assert.equal(ch.hp,dodgeHp,'Moving out of straight bullet path dodges it');assert.equal(Math.atan2(projectile.vy,projectile.vx),originalAngle);
ch.x=200;ch.y=226;projectile=ct.launchHazard(shooter,ch,'bullet',0,30);const hitHp=ch.hp;for(let i=0;i<80;i++)ct.tickHazards(.01);assert.ok(ch.hp<hitHp,'Bullet collides with body');
projectile=ct.launchHazard(shooter,ch,'arrow');const vy=projectile.vy;ct.tickHazards(.1);assert.ok(projectile.vy>vy,'Arrows fall under gravity');
projectile=ct.launchHazard(shooter,ch,'missile');const heading=Math.atan2(projectile.vy,projectile.vx);ch.y=40;ct.tickHazards(.1);const change=Math.abs(Math.atan2(Math.sin(Math.atan2(projectile.vy,projectile.vx)-heading),Math.cos(Math.atan2(projectile.vy,projectile.vx)-heading)));assert.ok(change>0&&change<=.150001,'Homing turn is limited so missiles can be outmaneuvered');
const bombs=harness(),btwo=bombs.t;btwo.start();const bh=btwo.get().heroes[0];btwo.get().heroes.forEach((h,i)=>{h.x=20+i*15;h.y=226});const bomb=btwo.launchHazard(btwo.enemy('boss',300),bh,'bomb',0,40);bomb.x=bh.x;bomb.y=bh.y-3;bomb.vx=bomb.vy=0;bomb.fuse=.2;const beforeBomb=bh.hp;btwo.tickHazards(.1);assert.equal(bh.hp,beforeBomb);btwo.tickHazards(.11);assert.equal(bh.hp,beforeBomb-39.2,'Bomb only damages when its fuse expires');assert.ok(btwo.get().blasts.length);
const pattern=btwo.enemy('boss',350);pattern.specialCooldown=0;btwo.tickSpecial(pattern,bh,.01);assert.ok(pattern.warning);const countBefore=btwo.get().hazards.length;btwo.tickSpecial(pattern,bh,.5);assert.equal(btwo.get().hazards.length,countBefore);btwo.tickSpecial(pattern,bh,.5);assert.equal(btwo.get().hazards.length,countBefore+7,'Telegraph precedes seven-shot fan');
const thrower=harness(),tt=thrower.t;tt.start();const th=tt.get().heroes[0];th.x=100;th.y=160;th.vx=th.vy=0;tt.setHeld(th);tt.moveHeld(160,100,200);assert.equal(th.x,100,'Pointer movement sets target without teleporting body');for(let i=0;i<10;i++)tt.stepHeld(th,.01);assert.ok(th.x>100&&th.x<160&&th.y<160&&th.y>100,'Body lags behind dragged target');const releaseX=th.x,releaseY=th.y,throwVX=th.vx,throwVY=th.vy;tt.release({timeStamp:200});assert.equal(th.vx,throwVX);assert.equal(th.vy,throwVY);tt.stepBody(th,.05);assert.ok(th.x>releaseX&&th.y<releaseY,'Release carries spring momentum');for(let i=0;i<200;i++)tt.stepBody(th,.01);th.y=100;th.vy=300;for(let i=0;i<80&&th.vy!==0;i++)tt.stepBody(th,.01);assert.ok(th.crouch>0,'Landing compresses the body');
const air=harness(),at=air.t;at.start();const ah=at.get().heroes[0],ae=at.get().enemies[0];ah.x=ae.x-10;ah.y=100;ah.vy=0;ah.cooldown=0;const enemyHealth=ae.hp;at.update(.01);assert.equal(ah.strike,null);assert.ok(!at.get().shots.some(s=>s.attack?.owner===ah));ah.strike={left:0,target:ae,amount:50,token:at.attackToken(ah),range:100};at.resolveStrike(ah,.01);assert.equal(ae.hp,enemyHealth,'Airborne pending melee hit is cancelled');
const inn=harness(),it=inn.t;it.startTown();const ih=it.get().heroes[0];ih.hp-=21;assert.equal(it.innCost(),3);it.setGold(2);assert.equal(it.healTown(),false);assert.equal(ih.hp,ih.maxHp-21);assert.equal(it.get().gold,2);it.setGold(10);assert.ok(it.healTown());assert.equal(it.get().gold,7);assert.equal(ih.hp,ih.maxHp);assert.equal(it.innCost(),0);it.healTown();assert.equal(it.get().gold,7);
tt.select(3);const priest=tt.get().heroes[3];priest.attributes.str=6;priest.attributes.dex=11;tt.stats(priest);tt.inspectHero(3);assert.match(thrower.elements.get('#priest-aura').textContent,/AT \+10% · DEF \+3/);tt.inspectHero(0);assert.equal(thrower.elements.get('#priest-aura').hidden,true);

const slowDrag=harness().t,fastDrag=harness().t;for(const d of [slowDrag,fastDrag]){d.start();const h=d.get().heroes[0];h.x=100;h.y=150;h.vx=h.vy=0;h.dragSample={x:100,y:150,t:0};d.setHeld(h)}slowDrag.moveHeld(160,100,1000);fastDrag.moveHeld(160,100,50);for(let i=0;i<8;i++){slowDrag.stepHeld(slowDrag.get().heroes[0],.01);fastDrag.stepHeld(fastDrag.get().heroes[0],.01)}assert.ok(fastDrag.get().heroes[0].x>slowDrag.get().heroes[0].x+8,'Fast cursor movement produces faster follow at equal distance');

const mechanics=harness(),mt=mechanics.t;mt.start();assert.deepEqual(Array.from({length:16},(_,i)=>mt.areaHealth(i)),[20,40,60,80,100,130,160,190,220,250,290,330,370,410,450,500]);for(let i=0;i<9;i++){mt.setArea(i);assert.equal(mt.enemy('boss',300).maxHp,mt.areaHealth(i)*10)}assert.deepEqual(Array.from({length:13},(_,i)=>mt.weaponPrice(i)),[100,250,500,750,1000,1500,2000,2500,3000,3500,4000,4500,5000]);assert.equal(mt.weaponPrice(22),10000);assert.equal(mt.weaponPrice(23),11000);assert.equal(mt.buyPrice(mt.items['0-ice']),1000);assert.equal(mt.needed(1),190);
mt.setArea(1);mt.setStage(0);mt.enter();assert.ok(mt.terrainHit(160,215,200,215),'A terrain wall blocks a low shot');const wallTarget=mt.get().enemies[0];wallTarget.x=210;wallTarget.y=226;wallTarget.hp=100;const wallShooter=mt.get().heroes[0];wallShooter.x=160;wallShooter.y=226;mt.shoot(wallShooter,wallTarget,'bullet',40,mt.attackToken(wallShooter));mt.tickShots(.3);assert.equal(wallTarget.hp,100);assert.equal(mt.get().shots.length,0);
const climber=mt.get().heroes[0];climber.x=179.9;climber.y=226;climber.vy=0;climber.vx=33;climber.drive=33;mt.stepBody(climber,.01);assert.ok(climber.y>220,'Hero does not snap 19 pixels up hill');for(let i=0;i<150;i++){climber.drive=33;mt.stepBody(climber,.01)}assert.ok(climber.x>180&&Math.abs(climber.y-207)<1,'Hero finishes stepping onto ledge');
const ec=mt.enemy('slime',179.9);mt.moveEnemy(ec,.3,.01);assert.ok(ec.y>220);for(let i=0;i<150;i++)mt.moveEnemy(ec,.17,.01);assert.ok(ec.x>180&&Math.abs(ec.y-207)<1,'Enemy steps onto ledge');
mt.setArea(0);mt.setParty([4,0,0,0]);mt.enter();const priestPulse=mt.get().heroes[0];priestPulse.x=260;priestPulse.y=219;priestPulse.weapon='4-fire';priestPulse.attributes.int=2;mt.stats(priestPulse);priestPulse.cooldown=0;mt.get().heroes.slice(1).forEach(h=>{h.x=20;h.cooldown=99});mt.get().enemies.forEach((e,i)=>{e.x=i<2?280+i*20:480;e.y=219;e.hp=e.maxHp=100;e.cooldown=99;e.specialCooldown=99});mt.update(.001);assert.ok(mt.get().enemies[0].hp<100&&mt.get().enemies[1].hp<100);assert.equal(mt.get().enemies[2].hp,100);assert.equal(priestPulse.mp,2,'Aura pulse charges MP once for multiple enemies');const ally=mt.get().heroes[1];ally.x=priestPulse.x;ally.y=priestPulse.y-200;assert.equal(mt.aura(ally).attack,1,'Above the aura gets no buff');ally.y=priestPulse.y;assert.ok(mt.aura(ally).attack>1);


const resurrection=harness(),rv=resurrection.t;rv.start();const corpse=rv.get().heroes[0];corpse.level=3;rv.stats(corpse);corpse.hp=0;rv.setGold(29);rv.select(0);assert.equal(rv.revivalCost(corpse),30);assert.equal(rv.revive(),false);assert.equal(corpse.hp,0);assert.equal(resurrection.elements.get('#revive').hidden,false);rv.setGold(1000);assert.equal(rv.revivalCost(corpse),100);assert.ok(rv.revive());assert.equal(rv.get().gold,900);assert.equal(corpse.hp,Math.ceil(corpse.maxHp*.1));assert.equal(rv.revive(),false);rv.get().heroes.forEach(h=>h.hp=0);rv.update(.01);assert.equal(rv.get().state,'service');assert.equal(rv.get().currentNode,'town');assert.ok(rv.get().heroes.every(h=>h.hp===Math.ceil(h.maxHp*.05)));assert.equal(rv.get().gold,900);assert.equal(rv.revive(),false);assert.equal(resurrection.elements.get('#result').hidden,true);
const closeCombat=harness().t;closeCombat.start();assert.ok(closeCombat.get().enemies.some(e=>e.type==='slasher'));const slashEnemy=closeCombat.enemy('slasher',250),dodgeHero=closeCombat.get().heroes[0];closeCombat.get().heroes.forEach(h=>{h.x=20;h.y=226});dodgeHero.x=225;dodgeHero.y=slashEnemy.y;slashEnemy.slash={left:.18,life:.32,face:-1,hit:false};const initialLP=dodgeHero.hp;closeCombat.tickSlash(slashEnemy,.1);assert.equal(dodgeHero.hp,initialLP);dodgeHero.y-=60;closeCombat.tickSlash(slashEnemy,.09);assert.equal(dodgeHero.hp,initialLP,'Lifting hero dodges slash');closeCombat.tickSlash(slashEnemy,.2);assert.equal(slashEnemy.slash,null);
dodgeHero.y=slashEnemy.y;slashEnemy.slash={left:.18,life:.32,face:-1,hit:false};closeCombat.tickSlash(slashEnemy,.19);assert.ok(dodgeHero.hp<initialLP);const afterSlash=dodgeHero.hp;closeCombat.tickSlash(slashEnemy,.01);assert.equal(dodgeHero.hp,afterSlash,'Slash damages only once');
const bombBoss=closeCombat.enemy('boss',350);bombBoss.warning={left:0,pattern:'BOMBS',x:100,y:226};closeCombat.tickSpecial(bombBoss,dodgeHero,.01);assert.equal(closeCombat.get().hazards.filter(p=>p.kind==='bomb').length,1);const shortMissile=closeCombat.launchHazard(bombBoss,dodgeHero,'missile');assert.equal(shortMissile.life,1.6);for(let i=0;i<170;i++)closeCombat.tickHazards(.01);assert.ok(!closeCombat.get().hazards.includes(shortMissile));closeCombat.attackMotion(dodgeHero);assert.equal(dodgeHero.swingV,48);assert.equal(dodgeHero.swing,-.8);


const auraUI=harness(),au=auraUI.t;au.start();au.setParty([0,4,4,0]);au.enter();const ahh=au.get().heroes;ahh[0].x=200;ahh[0].y=219;ahh[1].x=210;ahh[1].y=219;ahh[2].x=215;ahh[2].y=219;ahh[1].attributes.str=46;ahh[2].attributes.str=46;au.stats(ahh[1]);au.stats(ahh[2]);au.inspectHero(0);assert.equal(auraUI.elements.get('#attack').textContent,Math.round(ahh[0].atMin*2)+'–'+Math.round(ahh[0].atMax*2));ahh[2].x=500;au.inspectHero(0);assert.equal(auraUI.elements.get('#attack').textContent,Math.round(ahh[0].atMin*1.5)+'–'+Math.round(ahh[0].atMax*1.5));ahh[1].hp=0;au.inspectHero(0);assert.equal(auraUI.elements.get('#attack').textContent,ahh[0].atMin+'–'+ahh[0].atMax);
const slowBomb=au.launchHazard(au.enemy('spitter',400),ahh[0],'bomb');assert.ok(Math.abs(slowBomb.vx)<110);assert.equal(slowBomb.fuse,2.6);assert.equal(au.enemy('slasher',300).range,22);assert.equal(au.enemy('slime',300).range,12);
console.log('PASS: automatic town recovery, live stacked-aura AT, shorter starter reach, slower bombs, revival costs/defeat recovery, brief dodgeable slashes, single bombs, short missiles, HP/price curves, slower XP, terrain collision, stepping, priest area damage, manual single-character stage exit, stopped cleared party, speed-sensitive dragging, enemy projectiles/dodging, telegraphs, bombs, homing turn limits, throw momentum, priest aura totals, permanent weapon sockets, 5–8 stages and bosses, hidden map nodes, gated shop stock,  map locks/branches, town healing, trader buy/sell, persistent HP, no level-up healing, 5% tactical potions, left-panel hover, and all combat/rune regressions.');
